### ISSUE TITLE
Lost pictures on the documentation page

### ISSUE THREAD

**Issue by boonya** [ets-labs/python-dependency-injector#131]
Seems like you lost some pictures on the documentation page https://github.com/ets-labs/python-dependency-injector/blob/master/docs/containers/declarative.rst

Proof: ![python-dependency-injector-declarative rst at master ets-labs-python-dependency-injector 2016-08-19 00-21-39](https://cloud.githubusercontent.com/assets/779184/17791338/507024a2-65a3-11e6-8d4f-cc08514e033c.png)

**Comment by rmk135** [comment]
Hey Sergii,

Thanks a lot for this, but pictures are in place. Please, take a look on http://python-dependency-injector.ets-labs.org/en/stable/containers/declarative.html

The think here is that GitHub's rst pages viewer doesn't work as well as Shpinx does, so images could not be included.

Thanks,
Roman
