### ISSUE TITLE
Provider extension not working as expected

### ISSUE THREAD

**Issue by SimoneBronzini** [ets-labs/python-dependency-injector#156]
Executing the example found [here](http://python-dependency-injector.ets-labs.org/providers/custom.html#writing-of-custom-providers), I get

`Traceback (most recent call last):
  File "injector.py", line 36, in <module>
    user1 = users_factory()
  File "src/dependency_injector/providers.pyx", line 97, in dependency_injector.providers.Provider.__call__ (src/dependency_injector/providers.c:2652)
  File "src/dependency_injector/providers.pyx", line 197, in dependency_injector.providers.Provider._provide (src/dependency_injector/providers.c:4580)
NotImplementedError`

as if the `_provide` method was not overridden. The peculiar behaviour is that if I explicitly call `users_factory._provide()` it works as expected, if I call `users_factory()` (which implies passing through the `__call__` method) it raises `NotImplemented`. For instance, in the following code, when I call `users_factory._provide()` it prints `test`, when I call `users_factory()` it raises `NotImplemented`.

```import dependency_injector.providers as providers


class User(object):
    """Example class User."""


class UsersFactory(providers.Provider):
    """Example users factory."""

    __slots__ = ('_factory',)

    def __init__(self):
        """Initializer."""
        self._factory = providers.Factory(User)
        super(UsersFactory, self).__init__()

    def _provide(self, *args, **kwargs):
        """Return provided instance.

        :param args: tuple of context positional arguments
        :type args: tuple[object]

        :param kwargs: dictionary of context keyword arguments
        :type kwargs: dict[str, object]

        :rtype: object
        """
        print('test')
        return self._factory(*args, **kwargs)


# Users factory:
users_factory = UsersFactory()

users_factory._provide()
# Creating several User objects:
user1 = users_factory()
user2 = users_factory()

# Making some asserts:
assert isinstance(user1, User)
assert isinstance(user2, User)
assert user1 is not user2
```

**Comment by rmk135** [comment]
Hello Simone,

It looks really abnormal, I will take a look during the weekends.

Thank you for feedback,
Roman

**Comment by rmk135** [comment]
I don't know why, but this bug reveals that Cython ``cpdef`` methods could not be overridden by Python classes, at least in current case.

As an interim solution, I have updated example below to just override ``__call__`` method and added ``Provider.last_overriding`` read-only property:

```python
"""Custom `Factory` example."""

import dependency_injector.providers as providers


class User(object):
    """Example class User."""


class UsersFactory(providers.Provider):
    """Example users factory."""

    __slots__ = ('_factory',)

    def __init__(self):
        """Initializer."""
        self._factory = providers.Factory(User)
        super(UsersFactory, self).__init__()

    def __call__(self, *args, **kwargs):
        """Return provided object.

        Callable interface implementation.
        """
        if self.last_overriding is not None:
            return self.last_overriding._provide(args, kwargs)
        return self._factory(*args, **kwargs)


# Users factory:
users_factory = UsersFactory()

# Creating several User objects:
user1 = users_factory()
user2 = users_factory()

# Making some asserts:
assert isinstance(user1, User)
assert isinstance(user2, User)
assert user1 is not user2
```

It's the best way I found for removing this confusion.

This patch has been already productized under version ``3.4.4``: https://pypi.python.org/pypi/dependency_injector/3.4.4

**Comment by rmk135** [comment]
@SimoneBronzini, I close this issue as for now, but, please, fill free to reopen it or continue conversation if you have any other questions or suggestions.

Thank you once more for your contribution,
Roman

**Comment by SimoneBronzini** [comment]
Thank you for time! I see your point, I hope a better solution will be found in the future. In the meantime, I think the example you posted should be changed from
```python
return self.last_overriding._provide(args, kwargs)
```
to
```python
return self.last_overriding._provide(*args, **kwargs)  # additional *s
```
also, how about changing `Provider` to `BaseProvider` (or something like that, as I guess `BaseProvider` is already in use) and creating a new `Provider` class which implements the new `__call__` logic, so that it can be extended without the extender having to handle the problem as you did in the example?

**Comment by rmk135** [comment]
Thanks for suggestion! Next must stay as it is now:

```
return self.last_overriding._provide(args, kwargs)
```

It is so because ``Provider._provide()`` accepts tuple and dictionary already consolidated positional and keyword arguments.

Regarding the ``BaseProvider`` - it's great idea. At the same time, I will take a small brake to think a bit about it. Ideally, I would try to contact Cython maintainers to get this fixed, because it really looks strange and non-expected. This example was there since *Dependency Injector*'s 1.x versions that were fully on pure Python. Looks like this problem appeared with 3.x versions when I implemented providers on Cython.

Thanks once more for your contribution and ideas,
Roman
