### ISSUE TITLE
Installation via pip failed

### ISSUE THREAD

**Issue by kosiek** [ets-labs/python-dependency-injector#157]
I cannot install the extension, running from the Admin Command Prompt. I have Visual Studio 2017 with MSBuild for VS2017 and VS2015. MSBuild directory added to Path.

At this moment, being forced to have a particular C compiler becomes a problem since I want this module to be usable on many platforms and the Readme is not quite clear on what build tools should I use, for Windows and Linux.

```
Requirement already satisfied: six<=1.10.0,>=1.7.0 in c:\program files\python36\lib\site-packages (from dependency_injector)
Installing collected packages: dependency-injector
  Running setup.py install for dependency-injector ... error
    Complete output from command "c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\me\\AppData\\Local\\Temp\\pip-build-najo6qe0\\dependency-injector\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\me\AppData\Local\Temp\pip-xg1rzhsa-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\dependency_injector
    copying src\dependency_injector\errors.py -> build\lib.win-amd64-3.6\dependency_injector
    copying src\dependency_injector\__init__.py -> build\lib.win-amd64-3.6\dependency_injector
    copying src\dependency_injector\containers.pxd -> build\lib.win-amd64-3.6\dependency_injector
    copying src\dependency_injector\providers.pxd -> build\lib.win-amd64-3.6\dependency_injector
    running build_ext
    building 'dependency_injector.containers' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\src\dependency_injector
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files\python36\include" "-Ic:\program files\python36\include" /Tcsrc/dependency_injector/containers.c /Fobuild\temp.win-amd64-3.6\Release\src/dependency_injector/containers.obj -O2
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\me\\AppData\\Local\\Temp\\pip-build-najo6qe0\\dependency-injector\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\me\AppData\Local\Temp\pip-xg1rzhsa-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\me\AppData\Local\Temp\pip-build-najo6qe0\dependency-injector\
```

**Comment by rmk135** [comment]
Hello @kosiek,

I would really enjoy to provide you some help, but, frankly speaking, I'm not sure if I can help with this, at least now... At the same time, I can give you some information that hopefully could help you in your future investigation:

1) Dependency Injector itself doesn't force you to use specific compiler. I think that compiler is chosen by ``setuptools`` based on OS type that you use.
2) ``pip`` doesn't see your compiler ``cl.exe`` - ``error: command 'cl.exe' failed: No such file or directory``, but ``cl.exe`` is something that you should definitely have while you're using Visual Studio.

Based on this, I would recommend to play a bit with our Visual Studio setup and environment configuration.

In addition, I think you would be interested in this SO answer - http://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed?answertab=active#tab-top

Please, let me know, if you had a chance to get this resolved. I would be able to make any experiments with installation on windows in next two weeks, but if there would be no luck for you - I will try to provide some more significant help later.

Thanks for your contribution,
Roman

**Comment by kosiek** [comment]
Hello, @rmk135 

The thing is, you should never use cl.exe, because this is not supported at all. Either the libraries should be already compiled or the Windows-targeted build should utilize Microsoft Visual Studio Developer Command Prompt with proper .vcxproj project.

I recommend the first option, because successfully resolving the dependencies on machine is tricky and may fail with various client environments. There will also be a situation where you deploy your solution to production and that kind of machines don't have compilers installed.

**Comment by rmk135** [comment]
Yep, I see, agree. We need to distribute already compiled extensions.

I will need to find windows machine somewhere... Anyway, I will not be able to work on this next two weeks.

Thanks for information and contributions,
Roman

**Comment by rmk135** [comment]
@kosiek 

Dependency Injector is distributed as a wheel.

First version that has wheels is 3.19.1. Wheels are available for the most of Python versions on the most of the platforms.
