### ISSUE TITLE
Create DependenciesContainer provider

### ISSUE THREAD

**Issue by rmk135** [ets-labs/python-dependency-injector#178]
Based on conversation in terms of #177 , there is a need to create ``DependenciesContainer`` provider.

Example:

```python
# Example code
class Adapters(containers.DeclarativeContainer):
    email_sender = providers.Singleton(SmtpEmailSender)

class TestAdapters(containers.DeclarativeContainer):
    email_sender = providers.Singleton(EchoEmailSender)

class UseCases(containers.DeclarativeContainer):
    adapters = providers.DependenciesContainer()  # Want to use container as dependency 

    signup = providers.Factory(SignupUseCase, email_sender=adapters.email_sender)

use_cases = UseCases(adapters=Adapters)
# or
use_cases = UseCases(adapters=TestAdapters)

# Another file, views.py
from .containers import use_cases

use_case = use_cases.signup()
use_case.execute()
```

**Comment by rmk135** [comment]
Release ``3.10`` is on PyPi.

- Example - http://python-dependency-injector.ets-labs.org/examples/use_cases_miniapp.html

**Comment by asyncee** [comment]
Awesome work, you implemented it so fast!

Kudos to you 👍

**Comment by rmk135** [comment]
U’re welcome! Thank for your feedback! It helped to make this tool better! :+1:

**Comment by rmk135** [comment]
PS: I have added you to the list of contributors: https://github.com/ets-labs/python-dependency-injector/blob/master/CONTRIBUTORS.rst

**Comment by asyncee** [comment]
Good to know, thanks, i’m happy to help ;j
