### ISSUE TITLE
Overriding a factory argument

### ISSUE THREAD

**Issue by vporton** [ets-labs/python-dependency-injector#182]
As I understand, there is no yet the following feature (please add it):

If we add a keyword argument to a factory provider, the keyword should be passed to the constructor of the object (overriding the corresponding arguments passed to the `Factory()` constructor).

```
processes_factory = providers.Factory(Process, logger=default_logger_factory, db=db_factory)
```

Now we would be able to call `processes_factory(logger=send_to_browser)`.

This is especially useful when one has many keyword arguments in `providers.Factory()` and want to change one or several of them without duplicating all unchanged arguments.

Note that for singletons this should throw an exception.

Note that I am a novice in python-dependency-injector. I do not warrant all this is right.

**Comment by vporton** [comment]
Sorry, I see it is already done:

> Keyword context arguments have priority on Factory keyword injections and will be merged over them.

from http://python-dependency-injector.ets-labs.org/providers/factory.html

**Comment by rmk135** [comment]
Hi Victor,

Yeah, it's already implemented. However, `Singleton` does not raise an exception when you try to get already initialized instance with another arguments.

PS: Please, don't hesitate to ask more questions, when needed - this place should be  the one where you could find support.

Thanks,
Roman
