### ISSUE TITLE
Callable singleton

### ISSUE THREAD

**Issue by vporton** [ets-labs/python-dependency-injector#185]
I propose to create `CallableSingleton` provider, a hybrid of `Callable` and `Singleton` which behaves as `Callable` but the callable is to be called only once.

**Comment by vporton** [comment]
I want to create a singleton which calls `logging.getLogger()` from Python standard library (once).

Is there a way to do this easily?

**Comment by rmk135** [comment]
You can just use ``Singleton`` provider:

```python
logger = providers.Singleton(logging.getLogger)
assert logger() is logger()
```

**Comment by rmk135** [comment]
Victor, I'm closing this question cause it looks like that it's answered. Please, feel free to reopen it, if needed.
