### ISSUE TITLE
Create an example being used with mypy/python3.6 enhancements for ClassVar

### ISSUE THREAD

**Issue by aventurella** [ets-labs/python-dependency-injector#188]
Per the mypy documentation:
http://mypy.readthedocs.io/en/latest/python36.html#syntax-for-variable-annotations-pep-526

I think it has to be done like this:

```python
import dependency_injector.containers as containers
import dependency_injector.providers as providers
from my_services import MyService
from my_drivers import MyDriver


class Services(containers.DeclarativeContainer):
    my_service = providers.Singleton(MyService, driver=MyDriver) # type: ClassVar[MyService]
```

Though I **think** this might also work:

```
class Services(containers.DeclarativeContainer):
    my_service: ClassVar[MyService] = providers.Singleton(MyService, driver=MyDriver)
```

I don't get completions in Visual Studio Code for the latter, so I don't know if that's actually the way to do it. The mypy docs don't show assignments here: http://mypy.readthedocs.io/en/latest/python36.html#syntax-for-variable-annotations-pep-526 unless it's done with the `# type: ` syntax.

**Comment by rmk135** [comment]
Hi @aventurella ,

The thing is that `providers.Singleton(MyService, driver=MyDriver)` is a callable that return instance of `MyService`, so proper way to add typing for it is:

```python
class Services(containers.DeclarativeContainer):
    my_service: ClassVar[Callable[..., MyService]] = providers.Singleton(MyService, driver=MyDriver)
```

PS: have never tried to use `dependency_injector` with mypy or typing, nice to know that you're doing this.

Thanks,
Roman

**Comment by aventurella** [comment]
Hmmmm it's either an issue in Jedi or in VSCode.. Anyway, it looks like we have to do this:

```
class Services(containers.DeclarativeContainer):
    my_service = providers.Singleton(MyService, driver=MyDriver)


... later ...
x = Services.my_service # type: MyService
```

**Comment by rmk135** [comment]
I see. Well, it wasn't designed with thinking about static typing... Need to think if things could be better...
