### ISSUE TITLE
Question: Singleton initialization

### ISSUE THREAD

**Issue by aventurella** [ets-labs/python-dependency-injector#191]
I'm curious if this is allowed re: best practice (it works, which is great for me, but I'd like to know how foolish it is)

So I have a case where I have some drivers for services. One of my drivers needs another service:

```python
class Foundation(containers.DeclarativeContainer):
    http_service = providers.Singleton(
        HttpService, timeout=6.05
    ) # type: Callable[[], HttpService]


class Drivers(containers.DeclarativeContainer):
    api_driver = providers.Singleton(
        ProductionAPIDriver,
        api_access_key='',
        cache_duration_seconds=600,
        http_service=Foundation.http_service
    ) # type: Callable[[], ProductionAPIDriver]

    data_driver = providers.Singleton(
        # --- !!! > RIGHT HERE < !!! ---
        # This Driver needs to be initialized with a service
        # The service in question needs to be initialized with
        # the driver defined above
        lambda: DataDriver(Services.api_service())
        # --- ^^^ > RIGHT HERE < ^^^ ---
    ) # type: Callable[[], APIDataDriver]

class Services:
    api_service = providers.Singleton(
        APIService,
        driver=Drivers.api_driver
    ) # type: Callable[[], APIService]

    data_service = providers.Singleton(
        DataService,
        driver=Drivers.data_driver
    ) # type: Callable[[], DataService]

```

So when I need `Services.data_service` that needs to go get`Drivers.data_driver`. `Drivers.data_driver` needs to be initialized with a `Services.api_service`. Because `Drivers.data_driver` needs to itself be initialized with a service, I can't reference the `Services` at that moment in time, as it's declared below `Drivers`. To work around that, I have wrapped the `Singleton` initialization in a `lambda`. This allows it to run successfully since the `Services` name binding inside the `lambda` is effectively deferred until runtime.

So this is a bit of a hopscotch around but it **does** work. Now aside from making the flow more difficult to understand from a maintenance perspective, all the bouncing around, are there any other downsides to this approach?

The docs for the [Singleton](http://python-dependency-injector.ets-labs.org/providers/singleton.html) provider state:

> `Singleton` provider creates new instance **of specified class** (emphasis mine) on first call and returns same instance on every next call.

Of specific note is **of specified class**. In my case above, the **specificed class** is a callable in the form of a lambda. Is it safe to assume the docs really just mean **of specified CALLABLE**?

**Comment by rmk135** [comment]
Hi @aventurella,

Thanks a lot for your question, I will try to take a detailed look on weekend.

Thanks,
Roman

**Comment by rmk135** [comment]
> Is it safe to assume the docs really just mean of specified CALLABLE?

Yeah, absolutely.

Some time ago there was a check that `Factory` and `Singleton` providers accept only `type` instances, but later this check was removed with a reason to cover cases like this.

Documentation requires corrections, I will take care of it.

You also might be interested in using `DependenciesContainer` provider that gives you a chance to make late static binding. Please, take a look on next example:

```python
class Drivers(containers.DeclarativeContainer):
    services = providers.DependenciesContainer()

    data_driver = providers.Singleton(
        DataDriver,
        api_services=services.api_service
    ) # type: Callable[[], APIDataDriver]

class Services:
    api_service = providers.Singleton(
        APIService,
        driver=Drivers.api_driver
    ) # type: Callable[[], APIService]

    data_service = providers.Singleton(
        DataService,
        driver=Drivers.data_driver
    ) # type: Callable[[], DataService]


# In a runtime...

services = Services()
drivers = Drivers(services=services)

data_driver = drivers.data_driver()
```

Hope it helps!

Thanks,
Roman

**Comment by aventurella** [comment]
Hey-o! that is pretty slick! I also like that I can use that to provide a definite initialization point in the app startup.

Adding relevant links for notes to myself when I have to google this again =)

http://python-dependency-injector.ets-labs.org/examples/use_cases_miniapp.html?highlight=DependenciesContainer

http://python-dependency-injector.ets-labs.org/api/providers.html#dependency_injector.providers.DependenciesContainer

**Comment by rmk135** [comment]
> I don't know that it would be needed, but does that work with `DynamicContainer`'s also?

Well, not sure what did you mean... Generally, when you create `DeclarativeContainer(name=provider)`, it creates a `DynamicContainer`, copy all providers from declarative container to a newly created dynamic one and then make an overriding of these newly created providers with ones that were passed as a kwargs to `DeclarativeContainer`. So, basically, you can do the same by your own:

```
container = DynamicContainer()
container.dependencies = DependenciesContainer()
container.provider = Factory(..., dependency=container.dependencies.dependency)

# and then
container.dependencies.override(another_container)
```

**Comment by user-name-name** [comment]
So, as I understood this code is valid

```python
from dependency_injector.providers import (
    Callable,
    Factory,
    Dependency,
    Singleton,
)
from dependency_injector.containers import DeclarativeContainer

class App: pass

class Service: pass

def handler(app: App, service: Service, value: int):
    return app


class AppContainer(DeclarativeContainer):
    app = Singleton(App)


class ServiceContainer(DeclarativeContainer):
    service = Factory(Service)


class UseCaseContainer(DeclarativeContainer):
    value = Dependency()

    handler = Callable(
        handler,
        app=AppContainer.app,
        service=ServiceContainer.service,
        value=value,
    )


factory = UseCaseContainer(value=2)
app = factory.handler()

assert app != AppContainer.app()
assert AppContainer.app() == AppContainer.app()
```

and this happens because of this 

> when you create DeclarativeContainer(name=provider), it creates a DynamicContainer, copy all providers from declarative container to a newly created dynamic one

Correct me if I'm wrong

**Comment by rmk135** [comment]
> and this happens because of this

>> when you create DeclarativeContainer(name=provider), it creates a DynamicContainer, copy all providers from declarative container to a newly created dynamic one

> Correct me if I'm wrong

Yeah, you're right.

In your example, you would need to use `Dependency` provider for `AppContainer.app` & `ServiceContainer.service` like you do now for `value`, or you `DependenciesContainer` provider - http://python-dependency-injector.ets-labs.org/examples/use_cases_miniapp.html.
