### ISSUE TITLE
Update Singleton documentation

### ISSUE THREAD

**Issue by rmk135** [ets-labs/python-dependency-injector#193]
The docs for the Singleton provider state:

> Singleton provider creates new instance of **specified class** on first call and returns same instance on every next call.

However, the true statement is that not only class, but any callable could be provided. This needs to be corrected.

**Comment by shaunc** [comment]
Nice to know! I was just wondering if I had to create my own provider if I wanted to memoize the result of a Callable() provider to have a singleton not created by `__Init__()`. Would be helpful to have in the docs!

**Comment by rmk135** [comment]
Hi @shaunc ,

I'm now working on docs update. I'm sorry it's not yet there. I'll definitely add this.
