### ISSUE TITLE
How to inject something on a function argument?

### ISSUE THREAD

**Issue by adaliszk** [ets-labs/python-dependency-injector#194]
First of all, great work!

I'm coming from the PHP world where I'm used to having method level injections so if something only used in 1-2 methods then it doesn't necessarily need to get injected on the class level. I trying to figure out how could I do this but I'm getting lost in the documentation.

I wish to do something like this:
```python
from dependency_injector.containers import DeclarativeContainer
from dependency_injector.providers import Factory
from django.http import HttpRequest, HttpResponse
from django.views.generic import View


class MyContainer(DeclarativeContainer):
    response = Factory(HttpResponse)


class MyView(MyContainer, View):
    
    def get(self, request: HttpRequest, response: HttpResponse)
        return response.write('Hello, World!')
```

So something like upon calling a method the unprovided arguments get instances from the factories based on their name.

Does something similar exists in this framework?

**Comment by adaliszk** [comment]
Thank you for your answer, In the meantime, I did some experiments and I found https://github.com/suned/serum where this problem is solved by a decorator. In my current experiment, it seems I can use serum's injector and your framework together very nicely :wink:

**Comment by rmk135** [comment]
Hi @adaliszk ,

Nice! Really glad to hear.

> In my current experiment, it seems I can use serum's injector and your framework together very nicely 😉

It's very interesting. Just in case you would have some time and inspiration - it would be super beneficial for others if you can share what you did and how it works.

Thanks,
Roman

**Comment by adaliszk** [comment]
@rmk135 Will do, I just I have to create an Open Source demo for that, it will take some time because I want to create a proper article about it :slightly_smiling_face:

**Comment by rmk135** [comment]
Sounds great! Ok, let me know if any help needed 😄
