### ISSUE TITLE
Use DeclarativeContainer and Factory together to get a specific provider

### ISSUE THREAD

**Issue by Arrowana** [ets-labs/python-dependency-injector#196]
Hi,

Here is a container, the goal is to be able to group providers in a container, while still being able to have a factory to provide the right one to the end user.
```
from dependency_injector import providers, containers

class Numbers(containers.DeclarativeContainer):
	int = providers.Singleton(
		int,
		1234
	)
	float = providers.Singleton(
		float,
		1.2345
	)
```

1.
```
number_factory = providers.Callable(
	Numbers.providers.__getitem__,
	get_number_required_from_db()
)
```

vs

2.

```
number_factory = providers.FactoryAggregate(
	int=Numbers.int_provider, 
	float=Numbers.float_provider
)
```

In 1. it looks hacky but probably does the job.

In 2. I don't want to have each provider directly in the FactoryAggregate, that could make things messy if there are a lot of injections.
Also, I don't want to have them declared one by one, as in not grouped into a DeclarativeContainer.
2. involves repeating each keyword argument in the FactoryAggregate which is not great.

Is there a better way to do what I am trying to achieve, am I missing something?

Thank you

**Comment by rmk135** [comment]
Hi @Arrowana ,

Thanks for the question, I don't have a clear answer right now, so, need to think about it a bit. I will get back to you later.


Thanks,
Roman

**Comment by rmk135** [comment]
Hi again,

Long time no see, but finally I got back, sorry for the delay. If I understood you right, I think the most elegant way to do what you're doing is next:

```python
from dependency_injector import providers, containers


class Numbers(containers.DeclarativeContainer):

    int = providers.Factory(int, 1234)
    float = providers.Factory(float, 1.2345)


numbers_factory = providers.FactoryAggregate(**Numbers.providers)


if __name__ == '__main__':
    int_number = numbers_factory('int')
    float_number = numbers_factory('float')
    print(int_number, float_number)
```

This does not require to make any additional movements except of declaring new providers in `Numbers` container.

How does it look to you? Does it help?

Thanks,
Roman

**Comment by rmk135** [comment]
Closing this for now. Please, feel free to reopen if needed.

**Comment by Arrowana** [comment]
Sorry for the long delay, yes that is exactly what I needed. It addresses all the problems great.

Even if it is quite simple, should this make its way to the documentation? I find it extremely useful

**Comment by rmk135** [comment]
Hi @Arrowana ,

Thanks for the feedback, glad that you found what you needed.

Regarding the documentation, there is an example in place - http://python-dependency-injector.ets-labs.org/providers/factory.html#factory-aggregate-providers

However, I'm not sure how visible it is... Need to think how it could be better highlighted.
