### ISSUE TITLE
No need for instance attribute

### ISSUE THREAD

**Issue by nedbat** [ets-labs/python-dependency-injector#199]
Here (https://github.com/ets-labs/python-dependency-injector/blob/master/src/dependency_injector/providers.pyx#L90) you don't need to make an object attribute:
```
self.__overriding_lock = self.__class__.overriding_lock
```
You can simply access `self.overriding_lock` in your methods, since you aren't assigning to it, only calling its method.

(Sorry for the drive-by code review. Feel free to close if you don't want to change it.)

**Comment by rmk135** [comment]
Hey @nedbat ,

Feel really proud to get a code review from you 👍 Thanks for the comment, make sense, will definitely  refactor it :)

Thanks,
Roman

**Comment by rmk135** [comment]
Done at [3.12.4](https://pypi.org/project/dependency_injector/3.12.4/).

Thanks again, @nedbat!
