### ISSUE TITLE
How to create a factory with an argument and default arguments?

### ISSUE THREAD

**Issue by vporton** [ets-labs/python-dependency-injector#201]
I want to create a factory which calls the constructor `NoDownloader(state, parse_content, subclasses)` where `state` must be explicitly specified on every factory call, but `parse_context` and `subclasses` have default values (when calling the factory).

That is I want my factory `f` work for such calls:

* `f(state)`
* `f(state, parse_context=..., subclasses=...)`

It is also desirable that `state` is the _first_ argument of `NoDownloader`, to be able to specify it as a positional argument even when there are other arguments (`parse_context`, `subclasses`). However, this is not very important because `NoDownloader` constructor should be called just in one point of the program (the factory `f`).

**Comment by rmk135** [comment]
Hi @vporton ,

I think you can do it like this:

```python
no_downloader = Factory(NoDownloader, parse_context=..., subclasses=...)

no_downloader(state)
no_downloader(state, parse_context=custom_parse_context)
no_downloader(state, subclasses=custom_subclasses)
```

Please, take a look on that chapter of documentation - http://python-dependency-injector.ets-labs.org/providers/factory.html#factory-providers-and-init-injections

If I'm not wrong, example there also demonstrates exactly what you need.

> Positional context arguments will be appended after Factory positional injections.
> Keyword context arguments have priority on Factory keyword injections and will be merged over them.

**Comment by rmk135** [comment]
Closing this question... Please, feel free to reopen, if needed.
