### ISSUE TITLE
Parametrized factory (reusable factory)

### ISSUE THREAD

**Issue by arturoribes** [ets-labs/python-dependency-injector#203]
I have different Service Objects which have a Database object injected in order to abstract from the ORM (better testability). 
The default implementation is an SqlAlchemy implementation, which has 2 parameters, a base_class and a session.

I have these two factories:

    tokens = providers.Factory(services.TokenService,
                               id_generator=id_generator,
                               database=providers.Factory(
                                   services.SqlAlchemyDatabaseService,
                                   session=session,
                                   base_class=models.Token)
                               )

    users = providers.Factory(services.UserService,
                               id_generator=id_generator,
                               database=providers.Factory(
                                   services.SqlAlchemyDatabaseService,
                                   session=session,
                                   base_class=models.User)
                               )

As you can see, the ```database``` factory should be moved away, so the parameters that are the same for all usages are in only one place. Ideally, I would like to have something like:

    database = providers.Factory(services.SqlAlchemyDatabaseService,
                                 session=session)

    tokens = providers.Factory(services.TokenService,
                               id_generator=id_generator,
                               database=database.extend(base_class=models.Token)

So database lacks one parameter, which could be provided by some decorator like that hypothetical ```extend()``` method. Is it something that is already implemented?

**Comment by arturoribes** [comment]
Ok, I found it. There are the ```add_whatever``` methods. It would be cool to add some examples about this features. I find them darn useful. It ends up like this:

    database = providers.Factory(services.SqlAlchemyDatabaseService,
                                 session=session)

    tokens = providers.Factory(services.TokenService,
                               id_generator=id_generator,
                               database=database.add_kwargs(base_class=models.Token))

    users = providers.Factory(services.UserService,
                               id_generator=id_generator,
                               database=database.add_kwargs(base_class=models.User))

**Comment by arturoribes** [comment]
The temporal solution I found is to use a static method and a base class for the services container (in case you use them):
```
def database_factory(base_class):
    return providers.Factory(services.SqlAlchemyDatabaseService,
                             session=session
                             base_class=base_class)

tokens = providers.Factory(services.TokenService,
                           id_generator=id_generator,
                           database=database_factory(base_class=models.Token))

users = providers.Factory(services.UserService,
                           id_generator=id_generator,
                           database=database_factory(base_class=models.User))
```
Maybe there is a better solution, but I leave this in case someone finds it useful.

**Comment by rmk135** [comment]
Hi @arturoribes ,

Sorry for a delay in response, but I'm finally here. First of all, let me say, that your temporary solution looks good and I do like design approach you use.

Regarding of how Dependency Injector can handle it, I think that it might be done without writing extra function following next way:

```python
database = providers.Factory(SqlAlchemyDatabaseService, session=session)

tokens = providers.Factory(
    TokensService,
    id_generator=id_generator,
    database=providers.Factory(database, base_class=Token),
)

users = providers.Factory(
    UsersService,
    id_generator=id_generator,
    database=providers.Factory(database, base_class=User),
)

tokens_service = tokens()
assert tokens_service.database.base_class is Token

users_service = users()
assert users_service.database.base_class is User
```

This is sort of "micro-pattern" of Dependency Injector, I call it "Chained Providers". Main idea of "Chained Providers" is next: `Factory(Factory(..., *args, **kwargs), *args, **kwargs)`. I think that the best explanation here could be provided by following code:

```python
# 1. Keyword arguments of upper level factory are added to lower level factory
chained_dict_factory = providers.Factory(
    providers.Factory(dict, arg1=1),
    arg2=2,
)
print(chained_dict_factory())  # prints: {'arg1': 1, 'arg2': 2}


# 2. Keyword arguments of upper level factory have priority
chained_dict_factory = providers.Factory(
    providers.Factory(dict, arg1=1),
    arg1=2,
)
print(chained_dict_factory())  # prints: {'arg1': 2}

# 3. Keyword arguments provided from context have most priority
chained_dict_factory = providers.Factory(
    providers.Factory(dict, arg1=1),
    arg1=2,
)
print(chained_dict_factory(arg1=3))  # prints: {'arg1': 3}
```

Hope it helps and thanks for the question,
Roman

**Comment by rmk135** [comment]
BTW, I have just realized that it's possible to do another trick:

```python
database_factory = providers.Factory(
    providers.Factory,
    SqlAlchemyDatabaseService,
    session=session,
)

tokens = providers.Factory(
    TokensService,
    id_generator=id_generator,
    database=database_factory(base_class=Token),
)

users = providers.Factory(
    UsersService,
    id_generator=id_generator,
    database=database_factory(base_class=User),
)

tokens_service = tokens()
assert tokens_service.database.base_class is Token

users_service = users()
assert users_service.database.base_class is User
```

I would be calling this "trick" something like "Factory of Factories". It works, it also looks good to me, but, subjectively I like first-one more.

Roman

**Comment by zulrang** [comment]
@rmk135 Is there any way to make that last example work with overriding?  The problem is that the `database_factory(...)` methods resolve immediately, whereas the `database=providers.Factory(database_factory, ...)` way to doing it does not.
