### ISSUE TITLE
Issues with python -m pip install -U discord.py[voice]

### ISSUE THREAD

**Issue by DevCold211** [ets-labs/python-dependency-injector#216]
Command "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Michael\\AppData\\Local\\Temp\\pip-install-3xgvoykz\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Michael\AppData\Local\Temp\pip-record-gmbritcf\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Michael\AppData\Local\Temp\pip-install-3xgvoykz\PyNaCl\

What do i do?

**Comment by rmk135** [comment]
Hi @DevCold211 ,

Does not look like a question related to Dependency Injector :) What is that?

**Comment by DevCold211** [comment]
well when i pasted the code into google it brought me to this page up Im guess do to similar issues like this but I have no idea what the error it is

**Comment by rmk135** [comment]
I see. Well, I unfortunately, can not help you with this and this is not a right place for posting this question.

However, as it stated in topic, it looks like that you're trying to install `discord.py` so, basically, I think you can try to create similar issues with question in this project on GitHub - please, follow that link for that - https://github.com/Rapptz/discord.py

I'm closing this issue while not sure if I could provide any additional help with this.

Thanks,
Roman
