### ISSUE TITLE
How to implement method injection for the given scenario

### ISSUE THREAD

**Issue by umaparvat** [ets-labs/python-dependency-injector#223]
Could you please provide some sample for dependency injection

Here is the scenario which i'm looking for .
There are two tables (cmdb and account). I've to check count of entries for the given user should not exceed the allowed quota entry in the account table for the user.

Here i've to pass the contextmanager scoped session manager of sqlalchemy to the AccountQuery and CMDBQuery class .
 These tables have to be injected in method level.
I didn't not have clarity of how to pass it via containers.
Please provide a sample for method injection.

`
class DbQuery:

    def __init__(self, model_name):
        self._model = model_name

    def find_all(self):
        raise NotImplementedError

    def find(self):
        raise NotImplementedError

class CMdbQuery(DbQuery):

    def __init__(self, model_name, session, condt= None):
        self.condt = condt
        self.db = session
        super().__init__(model_name)

    def _query_all(self):
         with self.db as session:
             reslist = session.query(self._model).all()
         return reslist

    def _query_with_condt_all(self):
        with self.db as session:
            reslit = session.query(self._model.user_id, func(self._model.user_id.max .label('count').filter(self.condt).all()
        return reslit

    def find_all(self):
        if self.condt:
            data = self._query_all()
        else:
            data = self._query_with_condt_all()
        return [dt.to_dict() for dt in data if dt]

class AccountQuery(DbQuery):

    def __init__(self, model_name, session, condt= None):
        self.condt = condt
        self.db = session
        super().__init__(model_name)

    def _query_all(self):
         with self.db as session:
             reslist = session.query(self._model).all()
         return reslist

    def _query_with_condt_all(self):
        with self.db as session:
            reslit = session.query(self._model).filter(self.condt).all()
        return reslit

    def find_all(self):
        if self.condt:
            data = self._query_all()
        else:
            data = self._query_with_condt_all()
        return [dt.to_dict() for dt in data if dt]

class quotaChecker:

    @staticmethod
    def validate_quota(cmdb: DbQuery, account: DbQuery):
        """
        1.get the count of rows from cmdb table based on user id
        2. get the quota value from account table based on user id
        3. compare whether count is less than allowed quota, return true
           else return false
        4. if count of rows is 0, the user came for the first time, allow the user
           by returning true
        """
        count_cmdb = cmdb.find_all()
        user_quota = account.find_all()
        if count_cmdb and user_quota:
            if count_cmdb[0].count < user_quota[0].quota:
                return True
            else:
                return False
        else:
            return True # first time user

class DbModuleContainer(containers.DeclarativeContainer):

    finder_abs = providers.AbstractFactory(DbQuery, model_name=CMDBModel)

class cmdbContainer(DbModuleContainer):

    finder_abs = providers.Factory(DbQuery, model_name=CMDBModel, condt=f'cmdb.user_id == {id}')

class AccountContainer(DbModuleContainer):

    finder_abs = providers.Factory(DbQuery, model_name=AccountModel, condt=f'account.user_id == {id}')
    
class modulecontainer(containers.DeclarativeContainer):

    quotaprovider = providers.Factory(quotaChecker, DbQuery=cmdbContainer, DbQuery=AccountContainer)`

**Comment by rmk135** [comment]
Hi @umaparvat ,

I'm terribly sorry for late response - it took a while to pass most intensive development phase on one of commercial projects I was working on.

I didn't go too far in details of your questions, but I plan to make it in a couple of days. My apologies again for the delay, now help is on the way :)

Thanks,
Roman

**Comment by rmk135** [comment]
Hi @umaparvat ,

Well, the short answer is that there is no way to make method injections with Dependency Injector now.

I went through your example in details and I would propose to leave your containers structure "as is". 

Long story. Method injections were there in 1st version of Dependency Injector as well as couple of more different features like `@inject` decorator. However, after several years of usage it was revealed, that method injections were not used a lot and 2nd major version of Dependency Injector was distilled to keep only constructor injections (read `__init__` injections in Python world). At the same time, such distillation gave a perfect chance to simplify injections semantics. So, now we are at the point where Dependency Injector does not support this feature and it is done intentionally.

From my experience I would suggest to keep your structure in the way it is now.

PS: I'm closing this thread, but, please, feel free to comment / re-open if needed.

Thanks,
Roman
