### ISSUE TITLE
Use this package with orator ORM

### ISSUE THREAD

**Issue by handhikadj** [ets-labs/python-dependency-injector#230]
I want to use this package but I don't know how to collaborate this package with [orator-orm](https://orator-orm.com/) . on the Orator's model, I must extend the Model class on a class

e.g

User Class
```python
from orator import Model

class User(Model):
    pass
```

with this package:

```python
import dependency_injector.containers as containers

class User(containers.DeclarativeContainer):
    pass
```

Can I just:

```python
import dependency_injector.containers as containers
from orator import Model

class User(containers.DeclarativeContainer, Model):
    pass
```

???

**Comment by rmk135** [comment]
Hello @handhikadj ,

No, doing like that is a bad idea. `DeclarativeContainer` will add a meta class to your `User` class that 99% will conflict with `orator.Model`.

There are no example currently related to using `Dependency Injector` and `OratorORM`, but it might have sense to add some - I'll open another issue for that (#232).

Thanks,
Roman
