### ISSUE TITLE
Question: Is it possible to use root logger?

### ISSUE THREAD

**Issue by vella-nicholas** [ets-labs/python-dependency-injector#244]
Is it possible to use the root logger instead of a named one? If I have specific configuration for the root logger won't I be able to use them if I load a named logger?

**Comment by rmk135** [comment]
Hi Nicholas,

You definitely can.

Dependency Injector doesn't have any constraints on the loggers. Take a look on the next example:

```python
"""Example of dependency injection in Python."""

import logging

from dependency_injector import containers, providers


class IocContainer(containers.DeclarativeContainer):
    """Application IoC container."""

    ...

    logger = providers.Singleton(logging.getLogger, name='root')

    # or just

    logger = providers.Singleton(logging.getLogger)

    ...

Roman

**Comment by rmk135** [comment]
Please, reopen if needed.
