### ISSUE TITLE
Can't use DependenciesContainer with Configuration provider

### ISSUE THREAD

**Issue by FallenWarrior2k** [ets-labs/python-dependency-injector#247]
I think the issue is best explained with a code sample:
```
>>> from dependency_injector.containers import DeclarativeContainer
>>> from dependency_injector.providers import Configuration, DependenciesContainer
>>> class ConfigContainer(DeclarativeContainer):
...   config = Configuration('config')
... 
>>> from dependency_injector.providers import Callable
>>> def _foo(nested_key):
...   print(nested_key)
... 
>>> class OtherContainer(DeclarativeContainer):
...   root = DependenciesContainer()
...   foo = Callable(_foo, nested_key=root.config.deeply.nested.key)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in OtherContainer
AttributeError: 'dependency_injector.providers.Dependency' object has no attribute 'deeply'
>>> ConfigContainer.config.deeply.nested.key
<dependency_injector.providers.Configuration('config.deeply.nested.key') at 0x7f6ceb7d8770>
```

As you can see, trying to access a nested key (or rather, any key) on a Configuration provider behind a DependenciesContainer fails at declaration time with an AttributeError. Is there a way around this with the current API, and whether or not there is, what would you suggest as an alternative. For now, I went with a second Configuration provider on OtherContainer that is initialized to the relevant subobject of the Configuration in ConfigContainer.

**Comment by rmk135** [comment]
Hi,

Yep, that's known issue.

> For now, I went with a second Configuration provider on OtherContainer that is initialized to the relevant subobject of the Configuration in ConfigContainer.

That's the best workaround for now.

---

There is no way to fix it with current API. I'll see what I can do - this needs to be re-designed.

**Comment by FallenWarrior2k** [comment]
Alright. Thank you for your swift response, really appreciated.

**Comment by rmk135** [comment]
Dependency Injector has evolved. With the most recent version `4.25.0` example code could look like this:

```python
from dependency_injector.containers import DeclarativeContainer
from dependency_injector.providers import Configuration, DependenciesContainer, Callable


def _foo(nested_key):
    print(nested_key)


class ConfigContainer(DeclarativeContainer):
    config = Configuration('config')


class OtherContainer(DeclarativeContainer):
    root = DependenciesContainer(config=Configuration())  # <-- specify dependency explicitly
    foo = Callable(_foo, nested_key=root.config.deeply.nested.key)


if __name__ == '__main__':
    container = OtherContainer(
        root=ConfigContainer(
            config={
                'deeply': {
                    'nested': {
                        'key': 'foo',
                    },
                },
            },
        ),
    )
    container.foo()  # Output: foo
```

It took a while to get there. My apologies about that. Not sure if that is still relevant for you @FallenWarrior2k. May be it will help others. Closing this issue for now. Feel free to comment.

**Comment by FallenWarrior2k** [comment]
Thank you very much for your hard work. The workaround from back then is indeed still in place, so I'll get around to upgrading and changing it to the proposed solution.
