### ISSUE TITLE
Distributing package as a wheel

### ISSUE THREAD

**Issue by jamescurtin** [ets-labs/python-dependency-injector#248]
Currently, this package is only distributed as a sdist. Please consider distributing as a wheel so that end users do not need to manage the C dependencies themselves. PyPA provides a [manylinux](https://github.com/pypa/manylinux) docker image that can be incorporated into a CI pipeline to automate this process for you & there are similar examples for building macOS and windows wheels as well. Thank you!

**Comment by rmk135** [comment]
Hi James,

Thanks for the suggestion. I've not heard of [manylinux](https://github.com/pypa/manylinux). It could help a lot.

**Comment by kinow** [comment]
There are two projects I use at $work that I think ship wheels/binaries for different platforms, `protobuf` and `pyzmq`. Not too familiar with `protobuf`, but had had to learn a bit about `pyzmq`. The build toolchain is quite elaborate.

It appears they also use `manylinux` - https://github.com/zeromq/pyzmq/blob/dd4dac055152d47c829034224cdecf594c7b3f12/tools/tasks.py#L239. I never had to use it, as the Python code I maintain is mainly for Linux. But maybe using `pyzmq` as reference could be useful.

They also automate build/deploy through Travis/appveyor.

**Comment by rmk135** [comment]
The day has come.

Dependency Injector is distributed as a wheel.

Wheels are available for the most of Python versions on the  most of the platforms. It became possible with a help [Travis CI](https://travis-ci.org/) and [cibuildwheel](https://github.com/joerick/cibuildwheel).

@jamescurtin thanks for bringing up the idea and suggesting `manylinux`.
@kinow thanks for the `pyzmq` link. I used it a lot.
