### ISSUE TITLE
Does the `from_ini` method of the Configuration provider always return a str even when the value is an int?

### ISSUE THREAD

**Issue by zborowa** [ets-labs/python-dependency-injector#262]
I just started working with the newest version of the dependency injector and I'm curious about the Configuration provider and its return types. Using `from_dict` seems to return the correct values and correct types of those values, e.g.: 

```python
config.from_dict(
    {
        'section1': {
            'option1': 1, # returns int as value type
            'option2': 2, # returns int as value type
        },
    },
)
```

Using the `from_ini` method has a different result from the same structure, e.g.:
```ini
[section1]
option1 = 1 # returns str as value type
option2 = 2 # returns str as value type
```

Is there something I'm overlooking in the documentation or is there something that can be done to make `from_ini` return its values in the same way as the `from_dict` method?

As an intermediate solution, I'm casting all the values from the dict to their appropriate (int or float) value in a new dict because the original dict is unassignable.
For each section I currently have the following snippet:
```python
sec1 = {k: float(v) if '.' in v else int(v)
             for (k, v) in Core.config.section1().items()}
```

Also, how does the Configuration provider handle changes in the source file? Let's say I already used `from_ini` once and then updated the file with new configurations, will the `from_ini` method load the file again or maybe does the `provider.Configuration.section1` auto-magically have updated values?

**Comment by rmk135** [comment]
Hi @zborowa ,

Yes, there is a problem with ini files and option data types.

From the Python docs on [`configparser` module](https://docs.python.org/3.8/library/configparser.html#supported-datatypes):

> Config parsers do not guess datatypes of values in configuration files, always storing them internally as **strings**. This means that if you need other datatypes, you should **convert on your own**

For solving this problem `configparser` module provide `.getboolean()`, `getint()`, and `getfloat()` methods. This is not implemented in `Configuration` provider.

What to do?
=========

I would suggest to use YAML files for configuration.

```python
from dependency_injector import providers


config = providers.Configuration()

config.from_yaml('examples/providers/config.yml')

assert config.section1.option1() == 1
assert config.section1.option2() == 1.0
assert isinstance(config.section1.option2(), float)
```

Where the `config.yml` is:

```
section1:
  option1: 1
  option2: 1.0
```

Used YAML parser is smart enough to assign data types and more - [docs](https://pyyaml.org/wiki/PyYAMLDocumentation).

Live configuration reloading
====================

No, this doesn't work. No magic. If you'd like to reload the configuration you need to call `config.from_yaml()` again.

Are you looking for this feature to ease the development loop?

**Comment by rmk135** [comment]
This use case is covered in version ``3.32.0``.

See: http://python-dependency-injector.ets-labs.org/providers/configuration.html#specifying-value-type
