### ISSUE TITLE
Adding type hints to dependency-injector

### ISSUE THREAD

**Issue by awaizman1** [ets-labs/python-dependency-injector#268]
Hi,

Now that python typing (type hints) is very common, it would be great that dependency-injector will have type hints / annotations.
Currently when using Container / Provider classes mypy complains since it doesn't have information about a provider returned type, etc.

For example:
```python
provider: Provider[Animal] = providers.Factory(Cat)

animal = provider()  # mypy can know that animal is of type Animal
```

My current workaround is to put ```type: ignore``` in many places but it is less desired since I won't get errors at type checking time.

Thanks

**Comment by rmk135** [comment]
Hi @awaizman1 ,

Yep, that will be useful. I've faced the same problem on the own projects.

Fairly saying I did an attempt to make it work but there was some problem with generics I couldn't solve. I'll try to make it work again.

**Comment by agates4** [comment]
I will also say that this is the exact feature that I am looking for. Type hinting is very useful and will put this library above and beyond!

+++++1

**Comment by rmk135** [comment]
Got it. Thanks for feedback. Dependency Injector will have typing support.

**Comment by JarnoRFB** [comment]
I am not at all familiar with the code base, so I don't now how to implement this as a feature, but I was able to add correct type inference for the return type with

```python
T = TypeVar("T")


class TypedFactory(providers.Factory, Generic[T]):

    def __init__(self, cls: Type[T], *args, **kwargs):
        super().__init__(cls, *args, **kwargs)

    def __call__(self, *args, **kwargs) -> T:
        return super().__call__(*args, **kwargs)
```

What I would really look forward to would be type safety when creating the object graph / the providers. I believe that should be possible once [ParamSpec](https://www.python.org/dev/peps/pep-0612/) lands in Python. Then one could consider doing something like.

```python
P = ParamSpec("P")
R = TypeVar("R")

def factory(cls: Callable[P, R]) -> Callable[P, R]
```

and use it like

```python
a = providers.factory(A)(arg1, kwarg1=42)
```

**Comment by rmk135** [comment]
Hey @JarnoRFB ,

This code sample will help a lot. I did something similar experimenting with the generics and mypy. It didn't work when I tried. I'm glad to know that it works now.

The ``ParamSpec`` is exactly what is needed. I didn't know it's coming. That's very good. Thanks for the sharing.

**Comment by rmk135** [comment]
Typing stubs are added at `3.33.0`.

I've used the generics-based approach provided by @JarnoRFB:

```python
provider = providers.Factory(Cat)
animal = provider()  # mypy knows that animal is of type Cat
```

I've also added new ``types`` module. It contains ``Provider[T]`` generic type. This generic is useful when you need to specify the type explicitly. It can be used with any provider.

```python
from dependency_injector import providers, types


provider: types.Provider[Animal] = providers.Factory(Cat)

animal = provider()  # mypy know that animal is of type Animal

```

**Comment by awaizman1** [comment]
Hi @rmk135,

Thanks a lot for quick feature addition.

I tried using it but still can't make it work as expected (and a bit confused).

I saw the library now has 2 competing files:
- type stubs: providers.pyi
- types.py - holds Provider[Generic[T]]

Consider the following example:
```python
class Foo:
    pass

provider: Provider[Foo] = providers.Factory(Foo)
provider.override(providers.Singleton(Foo))
```

When using the type stubs (```from dependency_injector.providers import Provider```), the Provider defined there has all the methods as expected (i.e. override, delegate, etc.) but lacks the Generic type info thus getting this mypy error:
```
error: "Provider" expects no type arguments, but 1 given  [type-arg]
```

When using type.py (```from dependency_injector.types import Provider```) the Provider lacks all methods (i.e. override, etc.) thus getting this mypy error:
```
 error: "Provider[Foo]" has no attribute "override"  [attr-defined]
```

I think it would be great to enhance the type stubs (```providers.pyi```) to include the type argument - from a user perspective this is expected behavior when working with typed objects in python (as opposed to have this info in a separate different module)

**Comment by rmk135** [comment]
Hi @awaizman1 ,

I've faced a technical limitation implementing this feature. Let me show it.

1st part. When you do `from dependency_injector import providers`:

- `mypy` uses stubs from `providers.pyi`
- Python uses real `providers` module

2nd part of the puzzle is that there is no way to build in typing support into the `providers` module. Dependency Injector still supports Python 2.7. I'm also not yet sure how to add the typing to the Cython module. I assume it should work, but have not tried to make it.

Moving of the generic `types.Provider` to the stubs module will make `mypy` happy, but will not work when you run the code. `providers.Provider` is not a real generic and it will fail in the Python runtime.

Stubs `providers.pyi` and module `types.py` were not designed to be competitive. They serve different purpose. Stubs should cover the providers definition cases. `Provider` from the `types.py` is for the case when a provider is an argument of some function.

---

> One thing I can do as a temporary solution is to add the `.override()` definition to the `types.py` so it doesn't cause an error.

---

Another issue with the `types.Provider` module is that the check `isinstance(providers.Provider, types.Provider)` will return `False`. That's not nice. I don't yet know how to fix it. Need to think of it. 

Appreciate your and others thoughts.

**Comment by rmk135** [comment]
I think I have found a solution - https://www.python.org/dev/peps/pep-0560/#id22

This will help to remove `types` module and make `providers.Provider` behave like generic.

**Comment by rmk135** [comment]
Alright, I've done with it.

Stubs of the ``providers`` module is fully functional in `3.44.0`. Module `types` is deprecated. Next code should work without issues:

```python
from dependency_injector import providers


provider: providers.Provider[Animal] = providers.Factory(Cat)

animal = provider()  # mypy know that animal is of type Animal
```

@awaizman1 , Thanks a lot for reporting the problem. I'm sorry it required 2nd round.

**Comment by rmk135** [comment]
I'm closing the issue considering it as done. Please, leave a comment in case of any other issues.

**Comment by languitar** [comment]
Is this already release? I still see things like
> Provider[XXX] has no attribute "provided"

**Comment by rmk135** [comment]
Hey @languitar. Yes, it's released.

Can you, please, provide a code sample of what doesn't work?

**Comment by languitar** [comment]
It seems this issue only appears if you explicitly state the variable type:

```python
from typing import List

from dependency_injector import containers, providers


class Container(containers.DeclarativeContainer):

    service: providers.Provided[List[str]] = providers.Singleton(list, ["test"])

    client_factory = providers.Factory(list, service.provided)
```

Line 8 results in the aforementioned error message. Not explicitly stating the type avoids the warning.

**Comment by rmk135** [comment]
Thanks for the sample, got it.
There is a mistake / typo at `service: ....`. Take a look on screenshot:

<img width="749" alt="Screenshot 2020-10-19 at 12 19 53" src="https://user-images.githubusercontent.com/1742049/96478435-ad814a00-1205-11eb-8ad6-3e4a33553002.png">

Here is update code sample:

```python
from dependency_injector import containers, providers


class Container(containers.DeclarativeContainer):

    service = providers.Singleton(list, ["test"])

    client_factory = providers.Factory(list, service.provided)
```

I created a little gif how that should work:

![ezgif-2-9c540cf55e1c](https://user-images.githubusercontent.com/1742049/96478480-b96d0c00-1205-11eb-9400-d68be2ef4a01.gif)

**Comment by languitar** [comment]
Oops. in my real code this typo doesn't exist. yet I still get that error:

![image](https://user-images.githubusercontent.com/1336287/96479882-cd326580-1239-11eb-8252-8b56870993a4.png)

**Comment by rmk135** [comment]
Got it. Ok, that's explainable.

The typing stub for `providers.Provider` has no `.provided` attribute defined. Attribute `.provided` is only defined for providers that suppose to provide instances (see https://python-dependency-injector.ets-labs.org/providers/provided_instance.html).

<img width="498" alt="Screenshot 2020-10-19 at 13 51 23" src="https://user-images.githubusercontent.com/1742049/96493114-939a3400-1212-11eb-8334-c111bad83d92.png">

I can update the typing stub for `providers.Provider` so it has `.provided` attribute. It will cover that case.

Can you try if there is any error without explicit type definition for `service`? There should be no mypy errors when you do the same with `providers.Singleton` cause its stub has `.provided` attribute.

**Comment by languitar** [comment]
Great. Sounds like a Protocol or ABC is needed then to mark those providers that can offer this attribute.

There's no error when not using explicit typing.

**Comment by languitar** [comment]
Btw, the mypy page would also need an update if there was a special type of providers with the `provided` attribute.

**Comment by rmk135** [comment]
I think I will just move `.provided` attribute to `Provider` class and stub without a separate interface for this family.

General idea is that `Provider` is a base class that should carry all common functionality. I feel like I did a "over-specialization" mistake moving it to just specific provider subclasses.

I'll get it fixed in next 24 hours. Thanks for bringing this up @languitar .

**Comment by rmk135** [comment]
Fix is published on PyPI in version `4.0.5`.

@languitar , appreciate you brought up the issue. Thanks again.

I'm closing the issue. Please, feel free to comment or re-open if needed.

**Comment by dbertouille** [comment]
For type hinting the arguments to a provider, was the decision, and perhaps the only option, to wait until Python 3.10 and the ParamSpec feature? Taking the below example, it would be useful to be able to use mypy to ensure all arguments and proper types are supplied to ApiClient and Service.

```
    config = providers.Configuration()

    api_client = providers.Singleton(
        ApiClient,
        api_key=config.api_key,
        timeout=config.timeout.as_int(),
    )

    service = providers.Factory(
        Service,
        api_client=api_client,
    )

**Comment by rmk135** [comment]
@dbertouille , right. I’ll create a separate issue to not make this one endless.

**Comment by rmk135** [comment]
FYI @dbertouille , @JarnoRFB

Created new issue #314. Referencing you suggestions there.
