### ISSUE TITLE
Question about typing

### ISSUE THREAD

**Issue by izinihau** [ets-labs/python-dependency-injector#299]
Hello o/
So Im working with this dependency-injector(4.0.0) and pycharm latest version.
And im trying to understand why the auto-completion does not work as expected.

Here is an example of what I tried but only the last example allow me to have autocompletion:

first try:
```
from dependency_injector import providers
from mongo import MongoRepository

test = providers.Singleton(MongoRepository)
test().[expect_autocompletion_from_ide_here]
```

second try:
```
from dependency_injector import providers
from mongo import MongoRepository

test: providers.Provider[MongoRepository] = providers.Singleton(MongoRepository)
test().[expect_autocompletion_from_ide_here]
```

third try (working):
```
from dependency_injector import providers
from mongo import MongoRepository
from typings import Callable

test: Callable[[], MongoRepository] = providers.Singleton(MongoRepository)
test().[here_we_have_autocompletion]
```

Am i doing something wrong ? 
Thx in advance.

**Comment by rmk135** [comment]
Hello @izinihau ,

You are running into PyCharm issue https://youtrack.jetbrains.com/issue/PY-30869 (see duplicates as well).

I use PyCharm and experience the same. Hope they will get it fixed soon.

Best,
Roman

**Comment by izinihau** [comment]
Thanks for the quick answer! (and for the lib btw)
Well lets hope intellij fixes this some day :)
