### ISSUE TITLE
Use a configuration provider within a nested data structure

### ISSUE THREAD

**Issue by JonnyWaffles** [ets-labs/python-dependency-injector#309]
Hi friends,

I'm trying to figure out if it is possible to use the Configuration provider to provide a lazy value to a factory, but as a member of a nested data structure.

For example, I have a factory function that has a keyword parameter whose value is a dictionary. I would like to inject a configuration value into the dictionary during construction.

```python
class ExampleContainer(containers.DynamicContainer):
    config = providers.Configuration()
    template= providers.Factory(
            MyTemplateClass,
            template_kwarg_one=config.template_kwarg_one,
            params=dict(inner_value=config.inner_values)
        )
```

Here, I would like the config inner values to be injected into the params dictionary. Unfortunately, "inner_value" is the <class 'dependency_injector.providers.ConfigurationOption'> itself, not the provided value.

I read through the source code the best I could, but couldn't figure out exactly how the config value late binding works. Any suggestions?

**Comment by JonnyWaffles** [comment]
Oh man it is so obvious in hindsight. I just need to use another provider to provide the params object. Duh! 

The above becomes

```
class ExampleContainer(containers.DynamicContainer):
    config = providers.Configuration()
    template = providers.Factory(
            MyTemplateClass,
            template_kwarg_one=config.template_kwarg_one,
            params=providers.Callable(dict, inner_value=config.inner_values)
        )
```

**Comment by rmk135** [comment]
Hey @JonnyWaffles ,

Thanks for opening an issue and glad that you've figured it out. There was a similar use case some time ago with a ``list`` that resulted in creating a new provider - `List` (https://python-dependency-injector.ets-labs.org/providers/list.html). I think this use case is worth to create a new ``Dict`` provider similar to the ``List``.

I re-open the issue and mark it as a feature. I'm going to get a new ``Dict`` provider out of the door by the end of the week. You're welcome to watch the issue progress and upgrade to a newer version when it's available on PyPI.

Your example will look like:

```python
class ExampleContainer(containers.DynamicContainer):
    config = providers.Configuration()
    template = providers.Factory(
            MyTemplateClass,
            template_kwarg_one=config.template_kwarg_one,
            params=providers.Dict(inner_value=config.inner_values),
        )
```

**Comment by rmk135** [comment]
Done in `4.1.0`. Here is link to the docs - https://python-dependency-injector.ets-labs.org/providers/dict.html

Btw, there is another new provider: https://python-dependency-injector.ets-labs.org/providers/resource.html.

Closing the issue. Comment / re-open if neede.
