### ISSUE TITLE
ImportError: cannot import name 'Container' from 'dependency_injection'

### ISSUE THREAD

**Issue by KyryloAntoshyn** [ets-labs/python-dependency-injector#316]
Hi, I have the import problem.

I have the dependency_injection.py module:
```
from dependency_injector import containers, providers
import services


class Container(containers.DeclarativeContainer):
    """
    Dependency injection container class.
    """
    configuration_provider = providers.Configuration()
    initialization_service_provider = providers.Singleton(services.InitializationService)
```

Also, I have widgets.py module and I try to import the Container:
```
from PyQt5 import QtWidgets, QtCore, QtGui
from dependency_injection import Container
```

However, I am receiving following error:
![image](https://user-images.githubusercontent.com/26432700/97816311-202a0500-1c9d-11eb-91ad-28b5efd512ea.png)

Here is my project structure:
![image](https://user-images.githubusercontent.com/26432700/97816325-291ad680-1c9d-11eb-8ec4-1f766b816eea.png)

**I am using dependency-injector 4.3.2 and Python 3.7.9.**

How can I fix it? 

Thanks in advance!

**Comment by KyryloAntoshyn** [comment]
I assume that problem is connected with circular dependencies.

**Comment by KyryloAntoshyn** [comment]
This problem is resolved.  It was connected with circular dependencies of my modules.

**Comment by rmk135** [comment]
Hi @KyryloAntoshyn , glad you have figured it out.
