### ISSUE TITLE
Test example - Parametrize combined with fixtures

### ISSUE THREAD

**Issue by newtoniumx3** [ets-labs/python-dependency-injector#321]
This might be more of a python specific question though if there is a different way to connect this it could still be relevant.

**I was looking at this example:**

https://github.com/ets-labs/python-dependency-injector/blob/master/examples/miniapps/flask/githubnavigator/tests.py

```
@pytest.fixture
def app():
    app = create_app()
    yield app
    app.container.unwire()


def test_index(client, app):
    github_client_mock = mock.Mock(spec=Github)
```

How would I use python parametrize on test_index for such example?
```
import pytest
@pytest.mark.parametrize("test_input,expected", [
    ("3+5", 8),
    ("2+4", 6),
    ("6*9", 42),
])
def test_index(test_input, expected):
    assert eval(test_input) == expected
```

Also is it ok if we are not using app.test_client() that flask provides? I read about
```
app.test_client()
app.testing = True
```

**Comment by rmk135** [comment]
Hey @newtoniumx3 ,

Regarding ``@pytest.mark.parametrize``, no issues with using it. You just add needed params:

```python
@pytest.mark.parametrize("test_input,expected", [
    ("3+5", 8),
    ("2+4", 6),
    ("6*9", 54),
])
def test_index(test_input, expected, client, app):
    assert eval(test_input) == expected

    github_client_mock = mock.Mock(spec=Github)
    ...
```

**Comment by rmk135** [comment]
Regarding 

> Also is it ok if we are not using app.test_client() that flask provides?

I didn't get the question completely.

Generally, it's ok if you use any kind of Flask testing approach.

**Comment by rmk135** [comment]
Closing this issue. Please, don't hesitate to comment or re-open if needed.
