### ISSUE TITLE
Achieving DI during run time

### ISSUE THREAD

**Issue by ShravanVarma** [ets-labs/python-dependency-injector#323]
I have a python CLI application toolkit that other apps can use through a docker image. I want to use this library to achieve DI. I want to understand how to achieve DI during run time as my toolkit needs to read the YAML configuration from the application, perform some operations, and then decide which path to take. For example, few applications can specify SQLite and few applications can specify MSSql in their config files. Currently, I call an object responsible for figuring out the DB inside main, and then I am using factory methods to build the required object. How can I achieve this using this library?

**Comment by rmk135** [comment]
Hey @ShravanVarma. Take a look at next example.

There are two yaml configuration files. One for SQLite and another for MSSql.

File `config-with-sqlite.yml`:
```yaml
database:
  type: sqlite
  params:
    param1: abc
    param2: xyz
    param3: qwe
```

File `config-with-mssql.yml`:
```yaml
database:
  type: mssql
  params:
    param1: abc
    param2: xyz
    param3: qwe
```

Here is a sample Python code:

```python
from dependency_injector import containers, providers


class SQLite:
    def __init__(self, params):
        self._params = params


class MSSql:
    def __init__(self, params):
        self._params = params


class Service:
    def __init__(self, db):
        self._db = db

    def do_work(self):
        print(f'Using {self._db.__class__.__name__} database')


class Container(containers.DeclarativeContainer):

    config = providers.Configuration()

    sqlite = providers.Factory(
        SQLite,
        params=config.database.params,
    )

    mssql = providers.Factory(
        MSSql,
        params=config.database.params,
    )

    db_selector = providers.Selector(
        config.database.type,
        sqlite=sqlite,
        mssql=mssql,
    )

    service = providers.Factory(
        Service,
        db=db_selector,
    )


if __name__ == '__main__':
    container = Container()

    # SQLite

    container.config.from_yaml('config-with-sqlite.yml')
    service1 = container.service()
    service1.do_work()

    db = container.db_selector()
    print(f'Using {db.__class__.__name__} database')

    # MSSql

    container.config.from_yaml('config-with-mssql.yml')
    service2 = container.service()
    service2.do_work()

    db = container.db_selector()
    print(f'Using {db.__class__.__name__} database')
```

The key thing here is `db_selector` provider. It selects the db provider based on the current value of configuration option `config.database.type`. Having that you can use ``db_selector`` provider as an injection provider for other providers (see `Container.service`) or you can just get the db instance from the container `db = container.db_selector()`.

- More info on Selector provider https://python-dependency-injector.ets-labs.org/providers/selector.html#selector-provider
- You might also be interested in injecting invariants of config provider https://python-dependency-injector.ets-labs.org/providers/configuration.html#injecting-invariants

Appreciate you feedback and can provide more help if needed.

**Comment by rmk135** [comment]
Btw, take a look at https://github.com/ets-labs/python-dependency-injector/tree/master/examples/miniapps/movie-lister example. It also uses Selector provider for similar task. Config switch is implemented with environment variable.

**Comment by ShravanVarma** [comment]
Hey, @rmk135 thank you for the explanation. Appreciate it. For my use case, I will not have a configuration file ready without doing some operations during runtime. Does it sound like I can use `DynamicContainer`, prepare the config file, and then create the correct service?

**Comment by rmk135** [comment]
@ShravanVarma , yes, `DynamicContainer` should work fine for this.

Regarding the configuration, when you have it ready you  can do:

```python
    container.config.from_dict(
        {
            'database': {
                'type': 'sqlite',
                'params': {
                    'param1': 'abc',
                    'param2': 'xyz',
                    'param3': 'qwe',
                },
            },
        }
    )
```

**Comment by rmk135** [comment]
Closing this for now. Don't hesitate to comment or re-open if needed.
