### ISSUE TITLE
feature: document DependenciesContainer; take instance_of= initializer

### ISSUE THREAD

**Issue by shaunc** [ets-labs/python-dependency-injector#325]
I see DependenciesContainer in the API -- looks to be what I need to group together a set of dependencies which a few different containers depend on.

However, how do I type it? Perhaps it could take `instance_of=Container` in constructor and be of type Provider[Container]?

[Also -- what do the current **providers kw arguments do -- provide default values for providers?]

**Comment by rmk135** [comment]
Hey @shaunc ,

Can you check if any of these two examples is what you're looking for?

- https://python-dependency-injector.ets-labs.org/examples/application-multiple-containers.html
- https://python-dependency-injector.ets-labs.org/examples/decoupled-packages.html

**Comment by shaunc** [comment]
I like the examples, but neither [tells me how to type a DependenciesContainer provider](https://python-dependency-injector.ets-labs.org/providers/typing_mypy.html) -- and I suspect the DependenciesContainer itself should probably have some way of knowing what types its providing (if only to declare it as Generic[T] where T is used somewhere) -- hence the suggested "instance_of".

**Comment by rmk135** [comment]
Ok, got it. I suggest to use ``Container`` provider https://github.com/ets-labs/python-dependency-injector/blob/master/examples/miniapps/application-multiple-containers/example/containers.py#L66

Here is its typing stub https://github.com/ets-labs/python-dependency-injector/blob/master/src/dependency_injector/providers.pyi#L306

As for the DependenciesContainer, you can also type it explicitly in the container like this:

```python
class Services(containers.DeclarativeContainer):

    gateways: Gateways = providers.DependenciesContainer()
```

> [Also -- what do the current **providers kw arguments do -- provide default values for providers?]

Yes, **providers kw arguments  will be the default providers for this container.

**Comment by shaunc** [comment]
Ok -- thanks!

Hmm... so the difference is if I use DependenciesContainer, it is "collection of things that have to be provided", while using providers.Container, I specify a default for everything (though I can use provider.Dependency() in the provided container if I want to force provision), but then I can override it?

**Comment by shaunc** [comment]
Given I have a working work-around, I'd be fine if you close, or keep open if you want an issue for tracking typing support for DependenciesContainer.

**Comment by rmk135** [comment]
> Ok -- thanks!
> 
> Hmm... so the difference is if I use DependenciesContainer, it is "collection of things that have to be provided", while using providers.Container, I specify a default for everything (though I can use provider.Dependency() in the provided container if I want to force provision), but then I can override it?

Yes, exactly.

You use ``providers.Container()`` when you want to make a dependency on the particular container.

The ``providers.DependenciesContainer`` is kind of different. It represents a group of dependent providers. Imagine modules ``A`` and ``B`` depending on ``Core`` module. Module ``A`` needs providers ``foo, bar``. Module ``B`` needs providers ``bar, baz``. Module ``Core`` is a superset of all needed providers. It contains ``foo, bar, and baz``.

I have also added additional test to check that ``.provided`` attribute works for ``DependenciesContainer`` provider:

```python
from dependency_injector import providers


# Test 1: to check the getattr type
provider1 = providers.DependenciesContainer(
    a=providers.Provider(),
    b=providers.Provider(),
)
a1: providers.Provider = provider1.a
b1: providers.Provider = provider1.b
c1: providers.ProvidedInstance = provider1.c.provided
```

**Comment by rmk135** [comment]
> Given I have a working work-around, I'd be fine if you close, or keep open if you want an issue for tracking typing support for DependenciesContainer.

Ok, good, closing for now.

Let me know if you find any issues or need any other help.
