### ISSUE TITLE
How to handle circular dependency [non-string keys for Dict provider]

### ISSUE THREAD

**Issue by ijalalfrz** [ets-labs/python-dependency-injector#327]
so i have handler class to be injected by container to get repositry object

service/handler.py
```
from ... import Container
from dependency_injector.wiring import inject, Provide
from .rating_repository import RatingRepository
from ..domain.commands import SaveRating
from ..domain.models import RunnerRating


class CommandHandler:
    # Dep Injector
    @inject
    def __init__(self, rating_repo: RatingRepository =
                 Provide[Container.repo.rating]):
        self.rating_repo = rating_repo
```
this handler is included in messagebus module like this

service/messagebus.py
```
from .handler import CommandHandler

Message = Union[Command, Event]

logger = logging.getLogger(__name__)
command_handler = CommandHandler()


COMMAND_HANDLERS = {
    SaveRating: command_handler.save_rating,
}

class MessageBus:

    def __init__(self):
        pass

    # rest methods...
```

but i also add MessageBus class on container that make me include `service/messagebus.py` to `container.py`

container.py

```
from .runner_rating.service import messagebus

'''
    Dependency injector for application
'''


class MessageBusContainer(containers.DeclarativeContainer):

    bus = providers.Container(
        messagebus.MessageBus
    )

```
when i run the app, it shows ImportError on `container.py` because i imported `messagebus` and inside it there is a handler object that import `container.py`

what should i do to solve this? because message bus will be injected to other module in future

**Comment by rmk135** [comment]
Hi @ijalalfrz ,

I think that it is a typical circular dependency problem. In your case it seems like the loop is: `handler -> container -> messagebus -> handler`.

The quick solution is to move ``CommandHandler`` in the runtime. Here is some sample code:

File `service/messagebus.py`:

```python
from .commands import Command, SaveRating, DoSomethingElse


class MessageBus:

    COMMAND_HANDLERS = {}

    def __init__(self):
        from .handler import CommandHandler
        command_handler = CommandHandler()

        self.COMMAND_HANDLERS = {
            SaveRating: command_handler.save_rating,
            DoSomethingElse: command_handler.something_else,
        }

    def handle(self, command: Command):
        self.COMMAND_HANDLERS[command]()
```

File `service/containers.py`:

```python
from dependency_injector import containers, providers

from . import repositories, messagebus


class Container(containers.DeclarativeContainer):

    rating_repository = providers.Singleton(repositories.RatingRepository)

    message_bus = providers.Factory(messagebus.MessageBus)
```

And a sample code to run it:

```python
from .containers import Container
from .commands import SaveRating, DoSomethingElse


if __name__ == '__main__':
    container = Container()
    message_bus = container.message_bus()

    message_bus.handle(SaveRating)
    message_bus.handle(DoSomethingElse)
```

---

### The other way

The other way is to pull `CommandHandler` into the container. 

File `service/handler.py`:

```python
from .repositories import RatingRepository


class CommandHandler:
    def __init__(self, rating_repo: RatingRepository):
        self.rating_repo = rating_repo

    def save_rating(self):
        print('Saving rating')

    def something_else(self):
        print('Doing something else')
```

File `service/messagebus.py`:

```python
from typing import Dict, Callable, Any

from .commands import Command


class MessageBus:

    def __init__(self, command_handlers: Dict[str, Callable[..., Any]]):
        self.command_handlers = command_handlers

    def handle(self, command: Command):
        self.command_handlers[command]()
```

File `service/containers.py`:

```python
from dependency_injector import containers, providers

from . import repositories, handler, messagebus, commands


class Container(containers.DeclarativeContainer):

    rating_repository = providers.Singleton(repositories.RatingRepository)

    command_handler = providers.Singleton(
        handler.CommandHandler,
        rating_repo=rating_repository,
    )

    message_bus = providers.Factory(
        messagebus.MessageBus,
        command_handlers=providers.Dict({
            commands.SaveRating: command_handler.provided.save_rating,
            commands.DoSomethingElse: command_handler.provided.something_else,
        }),
    )
```

Sample code for running is the same.

Note: this option can not be implemented cause ``providers.Dict`` support only string keys in master. I will make a quick release to fix that.

**Comment by rmk135** [comment]
I have released version `4.5.0`. It supports non-string keys for `Dict` provider.

I've also included this example in the mini application examples: https://github.com/ets-labs/python-dependency-injector/tree/master/examples/miniapps/commands-and-handlers

**Comment by ijalalfrz** [comment]
> I have released version `4.5.0`. It supports non-string keys for `Dict` provider.
> 
> I've also included this example in the mini application examples: https://github.com/ets-labs/python-dependency-injector/tree/master/examples/miniapps/commands-and-handlers



> I have released version `4.5.0`. It supports non-string keys for `Dict` provider.
> 
> I've also included this example in the mini application examples: https://github.com/ets-labs/python-dependency-injector/tree/master/examples/miniapps/commands-and-handlers

Wow thank you @rmk135 for your fast reply and solution, i'm glad to contribute for this feature in this project 👏

**Comment by rmk135** [comment]
Thank you for bringing up the issue @ijalalfrz . Appreciate you contribution.

Let me know if you face other issues or need any other help.

**Comment by krunaldodiya** [comment]
I am also facing the same issue:

```
from dependency_injector import containers, providers

from trader.core.args_manager import ArgsManager
from trader.core.api import Api


class Container(containers.DeclarativeContainer):
    config = providers.Configuration()

    args_manager = providers.Singleton(
        ArgsManager,
    )

    api = providers.Singleton(
        Api,
    )
```

```
from dependency_injector.wiring import Provide, inject

class ArgsManager:
     @inject
     def __init__(self, api = Provide["api"]):
            print(api)
```

```
class Api:
     def __init__(self):
            pass
```

`print(api)` gives instance of dependency_injector.wiring.Provide instead of Api


### if I add wire, it gives circular import error.
### ArgsManager requires Container and Container requires ArgsManager

```
from dependency_injector.wiring import Provide, inject

class ArgsManager:
     @inject
     def __init__(self, api = Provide["api"]):
            print(api)

if __name__ == "__main__":
    container = Container()
    container.wire(modules=[__name__])
```

How to solve this ?
