### ISSUE TITLE
Injection return provide object not actual dependency object

### ISSUE THREAD

**Issue by ijalalfrz** [ets-labs/python-dependency-injector#328]
i have a class to be injected
src/runner_rating/api/rating/controller.py

```
class Rating():
    @inject
    def __init__(
                self,
                repo: RatingRepository = Provide[Container.repo.rating]):
        self.repo = repo

    def get_by_id(self, id):
        data = self.repo.get_by_id(id)
        if not data:
            raise HTTPNotFoundException(self.repo.index_name)

```
this is my container looks like:
src/container.py
```
class ESContainer(containers.DeclarativeContainer):
    config = providers.Configuration()
    client = providers.Singleton(
        elasticsearch_client.ElasticsearchClient,
        config=config.elasticsearch
    )

class RepositoryContainer(containers.DeclarativeContainer):

    config = providers.Configuration()
    db = providers.DependenciesContainer()

    rating = providers.Singleton(
        RatingRepository,
        db=db.client
    )

class Container(containers.DeclarativeContainer):

    config = providers.Configuration()
    es = providers.Container(
        ESContainer,
        config=config
    )

    repo = providers.Container(
        RepositoryContainer,
        config=config,
        db=es
    )
```
this is when Container were called:
src/application.py
```
from src import runner_rating
def main():
    # register dependency
    di_container = Container()
    di_container.config.from_dict(config.get_config())
    di_container.wire(modules=[runner_rating])


```
when i try Rating.get_by_id it shows error that:
```
 data = self.repo.get_by_id(id)
AttributeError: 'Provide' object has no attribute 'get_by_id'
```
Why? i'am using v2.5.1

**Comment by rmk135** [comment]
Hi @ijalalfrz , I will take a look later today.

**Comment by ijalalfrz** [comment]
> Hi @ijalalfrz , I will take a look later today.

Thank you, i figured that if i put ```@inject``` not in ```__init__``` method it works, i don't know why(?), first time i use this package it is sucessfully injected in ```__init__``` (if you remember when i post issue several days ago then i close the issue myself)

**Comment by rmk135** [comment]
@ijalalfrz , try to change `di_container.wire(modules=[runner_rating])` to `di_container.wire(packages=[runner_rating])`.

**Comment by ijalalfrz** [comment]
i' ve changed to package it also doesn't work

**Comment by rmk135** [comment]
Ok, got it. I'll debug it.

**Comment by rmk135** [comment]
I have an idea what is the root cause.

I have reproduced the file structure. Here is how it looks on my env:

<img width="286" alt="Screenshot 2020-11-25 at 21 35 19" src="https://user-images.githubusercontent.com/1742049/100301499-44a89280-2f66-11eb-83ab-0f2c5c716697.png">

I also use `di_container.wire(packages=[runner_rating])` instead of `modules=[...]`.
Injection works in this setup.

----

The way to break it is to remove `__init__.py` in one of the packages.
<img width="286" alt="Screenshot 2020-11-25 at 21 35 19 2" src="https://user-images.githubusercontent.com/1742049/100301666-a0731b80-2f66-11eb-99dc-625016bfa7b3.png">

It breaks because introspection does not count the directory without `__init__.py` as a package. Confusing part is that Python imports still work.

Can you check if all you packages have `__init__.py`?

**Comment by ijalalfrz** [comment]
i have ```__init__.py``` for every package, actually i put the Rating class on ```rating/__init__.py```

![Screenshot from 2020-11-26 09-49-41](https://user-images.githubusercontent.com/29910565/100302522-1dd17700-2fcd-11eb-8082-c143f6eee3fe.png)

**Comment by rmk135** [comment]
Ok. Can you share how do you use `Rating` in `views.py`?

**Comment by ijalalfrz** [comment]
> Ok. Can you share how do you use `Rating` in `views.py`?

it looks like this:
```

from fastapi import APIRouter
from . import Rating

controller = Rating()
router = APIRouter()


@router.get('/{id}', tags=['runner_rating'])
async def get_by_id(id: str):
    data = controller.get_by_id(id)

    return {
        'code': 200,
        'data': data,
        'message': 'Runner rating data'
    }

```

**Comment by rmk135** [comment]
Got it, thanks.

Injection into ``Rating.__init__()`` does not work because ``Rating`` is called before wiring is complete. You need to try to move objects creation into the runtime. Split runtime and declarative phases.

```
# Declarative phase
from fastapi import APIRouter
from . import Rating


router = APIRouter()


@router.get('/{id}', tags=['runner_rating'])
async def get_by_id(id: str):
    # Runtime phase
    controller = Rating()

    data = controller.get_by_id(id)

    return {
        'code': 200,
        'data': data,
        'message': 'Runner rating data'
    }
```

**Comment by ijalalfrz** [comment]
> Got it, thanks.
> 
> Injection into `Rating.__init__()` does not work because `Rating` is called before wiring is complete. You need to try to move objects creation into the runtime. Split runtime and declarative phases.
> 
> ```
> # Declarative phase
> from fastapi import APIRouter
> from . import Rating
> 
> 
> router = APIRouter()
> 
> 
> @router.get('/{id}', tags=['runner_rating'])
> async def get_by_id(id: str):
>     # Runtime phase
>     controller = Rating()
> 
>     data = controller.get_by_id(id)
> 
>     return {
>         'code': 200,
>         'data': data,
>         'message': 'Runner rating data'
>     }
> ```

ah i see, runtime ruin my life, so ```the get by id``` method works because it is inside the runtime right? we can close this issue, thank you very much for your support. amazing that you're alone maintain this project :+1:

**Comment by rmk135** [comment]
Yes, ‘get_by_id()’ works because you call it in the runtime.

Thank you. My pleasure to help.

Best,
Roman
