### ISSUE TITLE
How to deal with async resources

### ISSUE THREAD

**Issue by mxab** [ets-labs/python-dependency-injector#332]
Hi,
for my usecase I want to use [aio_pika](https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/1-introduction.html)

And my singleton resource connection is created via:

```
connection = await connect(
        "amqp://guest:guest@localhost/", loop=loop
    )
```

and shutdown via 
```
await connection.close()
```

but it looks like something like this is not supported yet:

```
async def aio_pika_connection():
 connection = await connect(
        "amqp://guest:guest@localhost/", loop=loop
    )
 yield connection
 await connection.close()

class Container(containers.DeclarativeContainer):

    config = providers.Configuration()

    aio_pika_connection= providers.Resource(
        aio_pika_connection
    )
```` 

Any hints how to deal with this?

**Comment by rmk135** [comment]
Hi @mxab , very good question. That's exactly what I'm working on right now :) That's how it will look like:

```python
import asyncio
import random
import sys

from dependency_injector import containers, providers, resources
from dependency_injector.wiring import inject, Provide, Closing


async def init_resource_1():
    await asyncio.sleep(random.randrange(1, 5) / 10)
    print('Resource 1 initialized')
    return 1


async def init_resource_2():
    await asyncio.sleep(random.randrange(1, 5) / 10)
    print('Resource 2 initialized')

    yield 2

    await asyncio.sleep(random.randrange(1, 5) / 10)
    print('Resource 2 shutdown')


class Resource3(resources.AsyncResource):

    async def init(self, *args, **kwargs) -> int:
        await asyncio.sleep(random.randrange(1, 5) / 10)
        print('Resource 3 initialized')
        return 3

    async def shutdown(self, resource: init) -> None:
        await asyncio.sleep(random.randrange(1, 5) / 10)
        print('Resource 3 shutdown')


class Container(containers.DeclarativeContainer):

    resource_1 = providers.Resource(init_resource_1)

    resource_2 = providers.Resource(init_resource_2)

    resource_3 = providers.Resource(Resource3)


@inject
async def main(
        resource_1: int = Provide[Container.resource_1],
        resource_2: int = Closing[Provide[Container.resource_2]],
        resource_3: int = Closing[Provide[Container.resource_3]],
) -> None:
    await asyncio.sleep(0.1)
    print('--------------')
    print('Resource 1 injected:', resource_1)
    print('Resource 2 injected:', resource_2)
    print('Resource 3 injected:', resource_3)
    print('--------------')


if __name__ == '__main__':
    container = Container()
    container.wire(modules=[sys.modules[__name__]])

    asyncio.run(main())
```

Adding asynchronous injections brought quite a few interesting challenges and resulted in "asynchronous injections mode". That's a feature that can prepare the injections fully asynchronously. In the example above there is a random sleep for each resource. If you run it a couple of times you will notice the resources are initialized in different order, and injected once all are ready.

The scope of work is large. It involves not only how resources work, but also wiring and general injections mechanism. I already have concept working, but need to add more tests to make sure I didn't brake anything. I would say that it's 70% done. ETA: early next week.

**Comment by mxab** [comment]
Very nice, looks promising!

I'm just tinkering arround at the moment, for now as a workarround I guess I can do something like:

````
# this is a resource provider function
def create_foo():
    foo = Foo()
    asyncio.run(foo.startup())
    yield foo
    asyncio.run(foo.shutdown())
´´´´

**Comment by rmk135** [comment]
Yep, `asyncio.run()` is something I used too.

**Comment by rmk135** [comment]
Update: this will take a few extra days. I've upgraded ``Factory`` and ``Callable`` providers to make async injections properly and added tests for that. That was the complex part. Now need to deal with ``Singleton`` and other providers.

**Comment by rmk135** [comment]
Update: still in progress. Done with `Singleton`, `ThreadSafeSingleton`, `ThreadLocalSingleton`, `Dependency`, `.provided` attributes and items. Now working on async mode for provider overriding.

**Comment by mxab** [comment]
Looking forward to it, but don't forget to enjoy the holiday season! :)

**Comment by rmk135** [comment]
Thanks! Trust me I will :) 👍  Same to you! :)

**Comment by rmk135** [comment]
I have published version ``4.6`` that supports async resources and adds async mode. See the docs for more info:

- [Resource async initializers](https://python-dependency-injector.ets-labs.org/providers/resource.html#resource-async-initializers)
- [Wiring async injections](https://python-dependency-injector.ets-labs.org/wiring.html#async-injections-wiring)
- [Providers async injections](https://python-dependency-injector.ets-labs.org/providers/async.html#async-injections)
- [FastAPI + Redis example](https://python-dependency-injector.ets-labs.org/examples/fastapi-redis.html#fastapi-redis-example)

**Comment by rmk135** [comment]
Closing the issue. Re-open if needed.

**Comment by mxab** [comment]
Very nice, the FastAPI + Redis is more or less exactly what I was looking for. Thank you very much!

**Comment by mxab** [comment]
@rmk135 one question regarding the Container creation in the FastAPI example, would it make sense to put this in the "startup" event listener ?

**Comment by rmk135** [comment]
@mxab yep, that's not a bad idea. You will need to link the container to the app so you can get the container instance in tests. I'll try to apply this and post in the next release. Thanks!

**Comment by mortyspace** [comment]
I have an issue that with FastAPI Depends + Closing not working

```
async def create_content(
    content_in: ContentIn,
    query: ModelTableService = Depends(
        Closing[Provide[ContentContainer.query]]
    ),
):

class ContentContainer(containers.DeclarativeContainer):
    connection = providers.Resource(get_db_connnection)
    db = providers.Factory(ModelDBService, connection, Content)
    
async def get_db_connnection():
    connection = await POSTGRES.connect()
    await connection.begin()
    print('begin')
    yield connection
    print('closed')
    await connection.close()
```

at the end -> `await connection.closed()` not called after func is done, so I can't close or release connection from connection pool
