### ISSUE TITLE
No manylinux wheel on pypi

### ISSUE THREAD

**Issue by RichardDRJ** [ets-labs/python-dependency-injector#333]
It looks like as of 4.3.7, the manylinux wheel is no longer being uploaded to PyPi.

* [4.3.6 artifacts](https://pypi.org/project/dependency-injector/4.3.6/#files) include the manylinux wheel;
* [4.3.7 artifacts](https://pypi.org/project/dependency-injector/4.3.7/#files) don't (and nor do subsequent ones, e.g. [4.3.8](https://pypi.org/project/dependency-injector/4.3.8/#files), [4.4.0](https://pypi.org/project/dependency-injector/4.4.0/#files), or [the latest](https://pypi.org/project/dependency-injector/#files)).

I didn't see any obvious changes between 4.3.6 and 4.3.7 which would cause this

**Comment by rmk135** [comment]
Hey @RichardDRJ , indeed, nice  catch. Thanks for reporting this.

Wheels are built on CI for all tags. Here is the most recent one: https://travis-ci.com/github/ets-labs/python-dependency-injector/jobs/455057934

All is built, but nothing is uploaded cause of exception on the very last step. What is really bad is that this exception was silenced by CI.

<img width="1680" alt="Screenshot 2020-12-09 at 14 56 25" src="https://user-images.githubusercontent.com/1742049/101680750-272bfc00-3a2f-11eb-92c7-89c1414b41e2.png">

Preliminary it looks like a ``twine`` or Tracis CI issue. I'll get that fixed.

**Comment by RichardDRJ** [comment]
Great, thanks very much!

**Comment by rmk135** [comment]
Found this issue on Tracis CI forum https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494

Seems like the issue has been fixed on .org, but still in place on .com.

Working on hotfix now.

**Comment by rmk135** [comment]
Manylinux wheels are back as of `4.5.4`.

@RichardDRJ , thank you for reporting the issue.
