### ISSUE TITLE
doc: override by derived container class

### ISSUE THREAD

**Issue by shaunc** [ets-labs/python-dependency-injector#334]
I would like a derived container class to be able to provide a dependency for a base container. It would seem that this isn't possible now:
```python
class Base(containers.DeclarativeContainer):
  to_override = providers.Dependency(instance_of=str)

# method 1 -- override attribute
class Derived1(Base):

    other_dependency = providers.Dependency(instance_of=Foo)
    to_override = other_dependency.provided.some_string_attr

# method 2 -- use constructor
class Derived2(Base):

    def __init__(self, other_dependency: Foo, **kw):
        super_kw = kw.copy()
        if 'to_override' not in super_kw:
            super_kw['to_override'] = other_dependency.some_string_attr
        super().__init__(other_dependency=other_dependency, **super_kw)

    other_dependency = providers.Dependency(instance_of=Foo)
```
In either case I get `dependency_injector.errors.Error: Dependency is not defined` when I build a derived object and attempt to access `to_override`.

**Comment by rmk135** [comment]
Hey @shaunc . I’m away from computer right now, will take a look soon.

**Comment by rmk135** [comment]
Hey @shaunc , take a look at this sample:

```python
from dependency_injector import containers, providers


class Service:
    def __init__(self, some_string):
        self.some_string = some_string


class Foo:
    def __init__(self, some_string):
        self.some_string_attr = some_string


FOO1 = Foo('one')
FOO2 = Foo('two')


class Base(containers.DeclarativeContainer):
    to_override = providers.Dependency(instance_of=str)
    depends_on_to_override = providers.Factory(Service, some_string=to_override)


@containers.copy(Base)
class Derived1(Base):

    other_dependency = providers.Dependency(instance_of=Foo)
    to_override = other_dependency.provided.some_string_attr


@containers.copy(Base)
class Derived2(Base):

    other_dependency = providers.Dependency(instance_of=Foo)
    to_override = other_dependency.provided.some_string_attr


if __name__ == '__main__':
    derived1 = Derived1(other_dependency=Foo('one'))
    dependency1 = derived1.depends_on_to_override()
    print(dependency1.some_string)

    derived2 = Derived2(other_dependency=Foo('two'))
    dependency2 = derived2.depends_on_to_override()
    print(dependency2.some_string)
```

The work is  done by ``@containers.copy`` decorator. It copies providers from ``Base`` to decorated container with replacing by reference the providers from the decorated container.

This decorator is undocumented right now. It lives from the 3rd version for backward compatibility. Since it looks like a needed tool I'll add a note to get the documentation back.

PS: there's also another container decorator - ``@containers.override``. Details https://python-dependency-injector.ets-labs.org/containers/overriding.html

**Comment by shaunc** [comment]
@rmk135 -- Thanks so much! :) You can use this for the doc issue if you want or close if you want to track otherwise....

**Comment by rmk135** [comment]
@shaunc -- u're welcome. Yep, will leave it opened to track docs update.

**Comment by rmk135** [comment]
Added docs for the ``@containers.copy()`` decorator: https://python-dependency-injector.ets-labs.org/containers/copying.html. Closing the issue.

PS: @shaunc , appreciate your review if you would have some time. Please, drop me a line if there are any improvements on your mind.

**Comment by shaunc** [comment]
Thanks! In the doc,

1. When might you not want to use it? / A sentence or two explanation/example of what normally happens without. (Without copy, overridden providers are available in the derived container, but base class dependencies continue to be bound to the base class providers.)
2. Perhaps, an example with providing a default value for a dependency with override. (Or something else of the sort.)

Although I haven't needed it, in theory one might want to copy just some providers -- `copy()` could take an optional list of provider names to restrict copy to just them.

---

In general dependency-injector is working well enough for me that I've pretty much turned to getting everything else to work! I'm very grateful for all the fixes and extensions!

**Comment by rmk135** [comment]
Thanks for the feedback Shaun. I have updated the docs with an extra description and example. Hope it looks better now.

> In general dependency-injector is working well enough for me that I've pretty much turned to getting everything else to work! I'm very grateful for all the fixes and extensions!

I'm glad to hear that. I was going to look for testimonials at some point of time. If you wouldn't mind I would like to ask you about the one. I have a feeling that you're building something great and I believe people would be interested to hear about it.
