### ISSUE TITLE
Unable to inject dependencies in Django Graphene project

### ISSUE THREAD

**Issue by juanmarin96** [ets-labs/python-dependency-injector#335]
Hi, I have tried to setup dependecy-injector in order to use in a project with Django and Graphql using [Graphene](https://graphene-python.org/). but I am get `Provide' object has no attribute 'execute_strategy`, I follow these steps [https://python-dependency-injector.ets-labs.org/examples/django.html](url) for Django setup, however the dependency doesn't work... I have somenthing like:

![image](https://user-images.githubusercontent.com/19893284/102096981-50fc6e80-3df3-11eb-9418-9c59cd7856c1.png)

Where `resolve_get_dashboard_data` is a tipycal Graphql resolver

**Comment by juanmarin96** [comment]
After debug it, I saw that I was committing and error in module wiring, Sorry I can fix it, thanks a lot.

**Comment by rmk135** [comment]
Hey @juanmarin96 , I was disrupted by something else while was trying to respond here. I was going to ask you to check wiring configuration. Glad things work 👍

Don't hesitate to ask if you have any other questions or something not working.

Best,
Roman
