### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by shaunc** [ets-labs/python-dependency-injector#336]
I am trying to create a container that optionally takes a dependency, and otherwise provides a value derived from another provider. The (IMO) hacky solution I have so far is a custom provider which either provides a Callable, or a default value if the callable has an error. Then I use this with the Callable being the dependency provider.

My questions are (1) is there a better way? and (2) even using this method, `DefaultCallable` defined below seems like a hack -- how can I improve?
```python

T = TypeVar("T")

class DefaultCallable(providers.Provider):

    __slots__ = ("_callable", "_default")

    def __init__(
        self, callable: Callable[..., T], default: T, *args, **kwargs
    ):
        self._default = default
        self._callable = providers.Callable(callable, *args, **kwargs)

        super().__init__()

    def __deepcopy__(self, memo):
        copied = memo.get(id(self))
        if copied is not None:
            return copied

        # TODO: type?
        copied = self.__class__(
            cast(Callable[..., T], self._callable.provides),
            providers.deepcopy(self._default, memo),
            *providers.deepcopy(self._callable.args, memo),
            **providers.deepcopy(self._callable.kwargs, memo),
        )
        self._copy_overridings(copied, memo)
        return copied

    def _provide(self, args, kwargs):
        try:
            return self._callable(*args, **kwargs)
        except Exception:
            # TODO: why do we need to check if is provider?
            # type?
            if getattr(cast(Any, self._default), "__IS_PROVIDER__", False):
                return cast(Any, self._default)()
            else:
                return self._default

# Used like

class Foo(containers.DeclarativeContainer):

    #: specify dv for pattern discovery (optional)
    dv_in: Provider[xr.DataArray] = providers.Dependency(
        instance_of=xr.DataArray
    )

    #: dv for pattern discovery (specified or default)
    dv: Provider[xr.DataArray] = DefaultCallable(
        # cast(Callable[..., xr.DataArray], dv_in), type??
        cast(Any, dv_in),
        problem.training.provided["dv"],
    )
```

**Comment by rmk135** [comment]
Hey @shaunc , will need some time to answer.

**Comment by rmk135** [comment]
Hey @shaunc , check this sample:

```python
from dependency_injector import containers, providers


class DataArray:
    ...


class DefaultDataArray(DataArray):
    ...


class ExtraDataArray(DataArray):
    ...


class DependencyWithDefault(providers.Dependency):

    def __init__(self, instance_of=object, default=None):
        super().__init__(instance_of)
        if default:
            self.override(default)


class Foo(containers.DeclarativeContainer):

    problem_training = providers.Dict({"dv": DefaultDataArray()})

    dv_in: providers.Provider[DataArray] = DependencyWithDefault(
        instance_of=DataArray,
        default=problem_training.provided["dv"],
    )


if __name__ == '__main__':
    container_with_default = Foo()
    default_dv_in = container_with_default.dv_in()

    container_with_extra = Foo(dv_in=ExtraDataArray())
    extra_dv_in = container_with_extra.dv_in()

    assert isinstance(default_dv_in, DefaultDataArray)
    assert isinstance(extra_dv_in, ExtraDataArray)
```

If I got it right, the cornerstone idea is to have a default provider for the dependency. If so, the easiest way to make it is to override the dependency provider in the declarative container.

You can achieve this by extending the ``Dependency`` provider like in the sample above, or even without that:

```python
class Foo(containers.DeclarativeContainer):

    problem_training = providers.Dict({"dv": DefaultDataArray()})

    dv_in: providers.Provider[DataArray] = providers.Dependency(instance_of=DataArray)
    dv_in.override(problem_training.provided["dv"])
```

Appreciate your feedback.

PS: the idea of adding a ``default`` argument like in the first sample seems reasonable. I'll add it to the backlog.

**Comment by shaunc** [comment]
@rmk135 -- excellent -- I suspected I might be able to derive from Dependency, but the docs on it are a bit sparse and I shied away from diving into the source code. 

I like the simple provision of the default, and will look forward to its arrival if you incorporate it into the core! :)

**Comment by rmk135** [comment]
> I like the simple provision of the default, and will look forward to its arrival if you incorporate it into the core! :)

Wonderful! I'll incorporate that in one of the next releases. The implementation is simple, but still need to add tests, docs, examples, etc.

> [Update -- Also interesting that "override" -- e.g. in the 2nd example inside the declarative container is itself overridden if the Dependency is specified -- maybe would be good to document on the Dependency provider.... I could guess that "last override wins" but not necessarily that specifying a dependency takes precedence over a previous override.]

Got it. Yep, it makes sense to describe this better. I'll do the homework :) As of "last override wins" -- yes, that's the way how overriding works. When you create a container instance ``container_with_extra = Foo(dv_in=ExtraDataArray())`` it does an overriding of the provider:

```python
container_with_extra = Foo(dv_in=ExtraDataArray())

# The same as:

container_with_extra = Foo()
container_with_extra.dv_in.override(ExtraDataArray())
```

So the default-like behaviour is achieved by overriding. Default state here is when the dependency is overridden once, and extra is when it is overridden twice.

The pieces of that knowledge could be found in the bottom of these two pages:

- https://python-dependency-injector.ets-labs.org/providers/overriding.html
- https://python-dependency-injector.ets-labs.org/containers/declarative.html

----

> I suspected I might be able to derive from Dependency, but the docs on it are a bit sparse and I shied away from diving into the source code.

Reasonable. The Cython code adds some difficulties and the framework is growing. I sometimes have to spend a while to understand how some pieces work :)

----

Thanks again for raising up an issue.

**Comment by shaunc** [comment]
Just a note for when you improve the docs. Not having looked at the internals, my guessed mental model of how it would work was that "override" was a "higher priority layer" than "normally specified" (sort of like css !important). There is nothing in the current documentation that says this, but the name ("override") probably led me to think along those lines. Given that, I would have expected that one override overrides another, but also would have expected that, once there is an override, a "normal specification" wouldn't have any effect.

**Comment by rmk135** [comment]
Hey @shaunc ,

I have release version ``4.13.0`` with the ``default`` argument for the ``Dependency`` provider.

```python
class Container(containers.DeclarativeContainer):

    cache = providers.Dependency(instance_of=Cache, default=InMemoryCache())


if __name__ == '__main__':
    container = Container()
    cache = container.cache()  # provides InMemoryCache()
```

I didn't use overriding feature for the default argument in favour of true default implementation. I've also updated the docs and appreciate if you could take a look: https://python-dependency-injector.ets-labs.org/providers/dependency.html.

**Comment by shaunc** [comment]
Great -- thank you very much! Hmm... maybe the new docs aren't on the site yet (don't see "default" there)?
Also, does it make sense to provide defaults for DependenciesContainer as well?

**Comment by rmk135** [comment]
@shaunc I guess updated docs were not deployed at time you were checking. Try again, please: https://python-dependency-injector.ets-labs.org/providers/dependency.html

Btw, I've got a new CI https://github.com/ets-labs/python-dependency-injector/actions/runs/521728453 :) Docs build is in very end of the pipeline, so I should been waiting until the job is done. Sorry about my hustling.

As of the DependenciesContainer, let me clarify. Now there are two use cases:

- dependent container structure is unknown (then use ``providers.DependenciesContainer``, provide defaults as kwargs)
- dependent container structure is known (then use ``providers.Container``, defaults are provided for all providers from wrapping container)

Here is an example:

```python
class Container(containers.DeclarativeContainer):

    # Container structure unknown
    container1 = providers.DependenciesContainer(
        provider=providers.Dependency(default=providers.Factory(...))
    )

    # Container structure known
    container2 = providers.Container(FooBarContainer)
```

Is there any other default on your mind?

**Comment by shaunc** [comment]
The docs look good for Dependency -- thanks! 👍 .

For DependenciesContainer I was thinking of the kwargs as the "form" of the providers and not the content per se -- so e.g. if I specify `providers.DependenciesContainer(foo=providers....)` then any instantiating instance would be required to have a foo provider of the specified type. A default, on the other hand, would fill in a missing `foo`. 
(Both of these possibilities I was thinking of as different than `providers.Container` where the overall container automatically has a subcontainer when instantiated without anything being provided. 

So defaults are something in between to provide defaults for individual providers while still possibly requiring that others be passed in. I guess its not urgent to have this, though -- especially as it doesn't seem that the kwargs currently are checked on provision.

**Comment by rmk135** [comment]
Thanks for checking the docs.

As of the dependencies container. There are two things you can do:

```python
class Container(containers.DeclarativeContainer):

    container = providers.DependenciesContainer(
        provider1=providers.Dependency(instance_of=..., default=providers.Factory(...))  # Dependency with a default, controls instance type
        
        provider2=providers.Factory(...),  # Replaces dependency provider
    )
    
    assert isinstance(container.provider2, providers.Factory) is True
```

That should sort of cover your use cases.
However, there is no way to verify that all required dependencies (that have no defaults) are provided when you create a container. Missing dependency reveals only in runtime, when you try to use it first time.

**Comment by shaunc** [comment]
Ok -- very good. Yes -- I was already trying to do what you suggested with overrides. Now with the defaults on the individual Dependency its cleaner. Checking dependencies would be nice, but I guess that by design you are able to provide them "incrementally" so requiring them all up front would break other use cases. Perhaps a `containers.checkDependencies( instance )` would be nice at some point. Thanks. 

I guess we are all set as far as I'm concerned on this issue. Closing, and thank you!

**Comment by rmk135** [comment]
> Checking dependencies would be nice, but I guess that by design you are able to provide them "incrementally" so requiring them all up front would break other use cases. Perhaps a containers.checkDependencies( instance ) would be nice at some point.

Right, totally agree. I'll create an issue for `containers.checkDependencies( instance )`.

Thanks @shaunc .
