### ISSUE TITLE
Q: How to avoid circular dependencies in containers.py?

### ISSUE THREAD

**Issue by aestene** [ets-labs/python-dependency-injector#339]
I'm developing a project in Flask (with flask-restx) and I have the following dependency in my system:
Telemetry -> TelemetryService -> Sensor

I would like to use dependency injection to inject `Sensor` into `TelemetryService`, and to inject `TelemetryService` into `Telemetry`. However, I'm having issues with circular dependencies as both `Telemetry` and `TelemetryService` imports `Container` from containers.py in order to use `Provide[Container.sensor]` and `Provide[Container.telemetry_service]`.

telemetry_service.py
```python
from dependency_injector.wiring import inject, Provide
from api.containers import Container
from api.services.service_connections.robot_api.crawler_api.sensor import Sensor

class TelemetryService:
    @inject
    def __init__(self, sensor: Sensor = Provide[Container.sensor]):
        self.sensor = sensor
```

telemetry.py
```python
from dependency_injector.wiring import Provide, inject
from api.containers import Container
from api.services.telemetry.telemetry_service import TelemetryService

class CurrentPose(Resource):
    @inject
    def __init__(
        self,
        telemetry_service: TelemetryService = Provide[Container.telemetry_service],
    ):
        self.telemetry_service = telemetry_service
```

containers.py
```python
from dependency_injector import containers, providers
from api.services.service_connections.robot_api.crawler_api.sensor import Sensor
from api.services.telemetry.telemetry_service import TelemetryService

class Container(containers.DeclarativeContainer):
    config = providers.Configuration()
    sensor = providers.Factory(Sensor)
    telemetry_service = providers.Factory(TelemetryService)
```

Then I setup the container in __init__.py, where I've placed my Flask app initialization.
```python
def create_app(test_config=False):
    container = Container()
    container.wire(modules=[sys.modules[__name__]])
    app = Flask(__name__)
    return app
```
Where I've removed some of the Flask specific setup to illustrate the example. Running my application I get the following trace:
```
Traceback (most recent call last):
  File "/home/arnts/Documents/Github/Robotics/eq_robot_public_api/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/arnts/Documents/Github/Robotics/eq_robot_public_api/main.py", line 1, in <module>
    from api import create_app
  File "/home/arnts/Documents/Github/Robotics/eq_robot_public_api/api/__init__.py", line 11, in <module>
    from api.apis import api_blueprint
  File "/home/arnts/Documents/Github/Robotics/eq_robot_public_api/api/apis/__init__.py", line 17, in <module>
    from api.apis.telemetry.telemetry import api as telemetry_api
  File "/home/arnts/Documents/Github/Robotics/eq_robot_public_api/api/apis/telemetry/telemetry.py", line 7, in <module>
    from api.containers import Container
  File "/home/arnts/Documents/Github/Robotics/eq_robot_public_api/api/containers.py", line 6, in <module>
    from api.services.telemetry.telemetry_service import TelemetryService
  File "/home/arnts/Documents/Github/Robotics/eq_robot_public_api/api/services/telemetry/telemetry_service.py", line 9, in <module>
    from api.containers import Container
ImportError: cannot import name 'Container' from partially initialized module 'api.containers' (most likely due to a circular import)
```
Which makes sense as attempting to import the container requires importing of `TelemetryService` to setup the provider for `TelemetryService`. And since `TelemetryService` has to import `from api.containers import Container` in order to inject `Provide[Container.sensor]`. Thus we have a circular dependency.

In essence, is it possible to solve this issue while still constructing all providers and containers in the same file?
- I was able to resolve the issue by creating separate containers for `Sensor` and `TelemetryService` in separate files, but I would like to know if there is a better solution?

**Comment by rmk135** [comment]
Hi @aestene ,

The way to resolve the circular import is to move the `TelemetryService -> Sensor` dependency injection inside of the container.

Module `telemetry_service`:

```python
from .sensor import Sensor


class TelemetryService:
    def __init__(self, sensor: Sensor):
        self.sensor = sensor
```

Module `containers`:

```python
from dependency_injector import containers, providers

from .sensor import Sensor
from .telemetry_service import TelemetryService


class Container(containers.DeclarativeContainer):
    config = providers.Configuration()
    sensor = providers.Factory(Sensor)
    telemetry_service = providers.Factory(TelemetryService, sensor=sensor)
```

And here is some sample code to run it:

```python
import sys

from .containers import Container
from .telemetry_service import TelemetryService
from .telemetry import CurrentPose


if __name__ == '__main__':
    container = Container()
    container.wire(modules=[sys.modules[__name__]])

    # Build Flask app, add resources, etc.

    resource = CurrentPose()
    assert isinstance(resource.telemetry_service, TelemetryService)
```

The idea is to keep most of the code unaware about the framework. Keep the components and their dependencies in the container and use wiring feature to make in-place injections in the endpoints (`CurrentPose` resource in the example). Following this approach will give you the container that you could use like a map of your domain model. You would be able to have multiple instances of the same class with different dependencies, override `TelemetryService` for testing the resources etc.

**Comment by aestene** [comment]
Thank you for the quick response @rmk135! A simple solution which worked very well.

**Comment by rmk135** [comment]
You're welcome. Thanks for raising a question. Let me know if you need any other help or see something could be better.

Best,
Roman
