### ISSUE TITLE
Q: Can Configuration values be made required?

### ISSUE THREAD

**Issue by ms-lolo** [ets-labs/python-dependency-injector#341]
Couldn't find an example of this in the docs but I am trying to ensure that the system fails fast if the container hasn't been properly configured when the necessary provider is called. For example:

```python
class MyContainer(DeclarativeContainer):

    config = Configuration()

    some_client = Singleton(SomeClient, config.something_important)
```

Right now, if I forget to set `mycontainer.config.something_important` before calling `mycontainer.some_client()`, then `SomeClient` will be given `None` as its parameter which is actually worse than forgetting to pass the argument at all because Python will allow it even if it's not an optional parameter. I don't want to sprinkle my classes with `something_important is None` checks.

What I really want is to be able to specify the exact keys I would expect in a Configuration provider and have the Container initialization fail if those values are not provided. Do you have any suggestions?

**Comment by ms-lolo** [comment]
I wonder if maybe what I want is a custom provider that behaves as a stricter version of `Configuration`.

**Comment by rmk135** [comment]
Hey @ms-lolo , that doesn't work out of the box, but that's a good idea. I'll think how it could be implemented. The wild guess I have now is to make something like this:

```python
class MyContainer(DeclarativeContainer):

    config = Configuration()
    config.something_important.required()

    some_client = Singleton(SomeClient, config.something_important)
```
There also could be a strict mode for `Configuration` provider that will prohibit using any undefined values.

**Comment by rmk135** [comment]
I have released version `4.10.0` with strict mode and required modifier features for the ``Configuration`` provider. Here is a doc: https://python-dependency-injector.ets-labs.org/providers/configuration.html#strict-mode-and-required-options

**Comment by rmk135** [comment]
Closing the issue. Reopen if needed.

**Comment by rmk135** [comment]
@ms-lolo , thanks for suggesting the feature!

**Comment by ms-lolo** [comment]
this seems to solve my problem, thank a lot!

**Comment by rmk135** [comment]
Glad to hear that! Thank you again
