### ISSUE TITLE
Please provide builds for ARM based systems

### ISSUE THREAD

**Issue by czukowski** [ets-labs/python-dependency-injector#342]
I wrote a program using the Dependency Injector and wanted to use it on an embedded system using Aarch64 architecture. Unfortunately though, it doesn't come with gcc to build it or any package manager to install the necessary prerequisites. Would you consider providing wheel builds for ARM based systems?

On [cibuildwheel](https://github.com/joerick/cibuildwheel) page there's a mention that Linux ARM builds are currently available only on Travis, which, considering the current situation around it, may prove problematic. But if you were going to migrate to GitHub Actions, I've found a PR https://github.com/joerick/cibuildwheel/pull/482 that seems to be on a good way to bring the ARM support via Qemu there.

**Comment by rmk135** [comment]
Hi @czukowski , of course, I would love to add the ARM builds. I'm currently on Travis CI and I negotiate them so they could sponsor the project in future. The negotiation is not yet over, but it goes positive fashion. If `cibuildwheel` supports ARM builds and Travis too I should be able to add this relatively easy. I'll add that to the backlog.

**Comment by rmk135** [comment]
@czukowski can you try to install dependency injector from here:

```
pip install -i https://test.pypi.org/simple/ dependency-injector==4.5.4b1
```

I have created a build of most recent version of dependency injector on test pypi. It has source code version and ARM builds: https://test.pypi.org/project/dependency-injector/4.5.4b1/#files

**Comment by czukowski** [comment]
```
Successfully installed dependency-injector-4.5.4b1
```

@rmk135 thank you, the installation was successful and the program is working!

**Comment by rmk135** [comment]
@czukowski , ok, very good. Use that one for now. This is a fully functional latest version. I'll include ARM builds to one of the future release. Please follow this issue to know when to make an upgrade to real PyPI.

**Comment by rmk135** [comment]
@czukowski you can upgrade version ``4.6.0`` from real PyPI. It goes with ARM wheels.

**Comment by rmk135** [comment]
Closing this issue. Re-open if needed.
