### ISSUE TITLE
Configuration scope matching provider scope

### ISSUE THREAD

**Issue by ssheng** [ets-labs/python-dependency-injector#346]
Is there a way to automatically match the configuration scope with the provider scope? To illustrate, consider the following providers and configuration in YAML format.

Container:
```python
class Module2:
  def __init__(self, key1: int):
    self.key1 = key1

class Module1:
  def __init__(self, module2: Module2):
    self.module2 = module2

class Container(containers.DeclarativeContainer):
  config = providers.Configuration()
  module1_factory = providers.Factory(
    Module1,
    module2 = providers.Factory(
      Module2,
      key1 = config.module1.module2.key1)
```

Configuration:
```yaml
module1:
  module2:
    key1: 1
```

Is this a way to automatically derive that key1 belongs to `module1.module2.key1` given the YAML and providers hierarchies so `key1 = config.module1.module2.key1)` does not need to be explicitly specified for Module2 factory?

Thanks,
Sean

**Comment by rmk135** [comment]
Hi @ssheng , nope, there is no good solution for this right now.

That's interesting case. I don't have any elegant solution on my mind at the moment, but I'll think of it more. I'll let you know if anything good comes to my mind. If you have any suggestions about the syntax, you're welcome too.
