### ISSUE TITLE
How to find the provided class type?

### ISSUE THREAD

**Issue by ms-lolo** [ets-labs/python-dependency-injector#347]
Been struggling to get this working today and I thought it was possible! I have a container instance and I want to loop through all the providers and see the class they are providing. This is my pseudo code:

```python
for name, provider in container.providers:
  print(provider.cls)
```
I thought `provider.cls` could have what I want, but it seems to just give me `<class 'abc.ABCMeta'>` for most things. What did I miss?

**Comment by ms-lolo** [comment]
ugh, sorry, ignore me! I had an extra `type()` around things :(

**Comment by rmk135** [comment]
@ms-lolo , glad you've figured it out. Don't hesitate to open an issue in case you need any other help.
