### ISSUE TITLE
Providing dependencies across more than one level of inheritance

### ISSUE THREAD

**Issue by shaunc** [ets-labs/python-dependency-injector#350]
I have a derived chain of containers (say, `C1 -> C2 -> C3`). I want to instantiate `C3` with a dependency for `C1`, which is then used (directly and indirectly) in the derived containers.

In fact, I have found a way to do it, but it is ugly:
```
class C1(containers.DeclarativeContainer):
    a1 = providers.Dependency(instance_of=str)


class C2(C1):
    a1_ = C1.a1
    a1 = providers.Dependency(instance_of=str)
    a1_.override(a1)
    a2 = providers.Callable(C1.a1)


class C3(C2):
    a3 = providers.Callable(C2.a1)

c3 = C3(a1="foo")
print("c3", c3.a3())  # prints "foo"
```
I can't seem to get it to work without the intermediate redefinition of a1 ... is this a bug? E.g. if I don't have that and try to instantiate `C3(a1="foo")` I get an error:
```
AttributeError: 'DynamicContainer' object has no attribute 'a1'
```

(I tried fiddling with `@containers.copy()` as well, unsuccessfully).

**Comment by shaunc** [comment]
Hmm... this work-around seems insufficient in more complex situations, especially in cases where there are "optional" dependencies, implemented as in https://github.com/ets-labs/python-dependency-injector/issues/334#issuecomment-744497698.

I don't really have a simple case to post -- but if the above doesn't have a "good" resolution and you need more information, I can see what I can do to boil one down.

**Comment by rmk135** [comment]
Hey @shaunc , that's good example, I'll take a look.

**Comment by rmk135** [comment]
Hey @shaunc , #350, #351, #354, and #355 are on track and in the top of my backlog. I plan to process them in next 2 days. I'm sorry for the delay, a bit short on time cause some other things.

**Comment by shaunc** [comment]
Great -- thanks for the update! And thanks for picking off the easy ones! :)

**Comment by rmk135** [comment]
Confirming that's a bug. `C3` looses `a1`:

```python
from dependency_injector import containers, providers


class C1(containers.DeclarativeContainer):
    a1 = providers.Dependency(instance_of=str)


class C2(C1):
    a2 = providers.Callable(C1.a1)


class C3(C2):
    a3 = providers.Callable(C2.a1)


if __name__ == '__main__':
    print('C1 providers', C1.providers.keys())
    print('C2 providers', C2.providers.keys())
    print('C3 providers', C3.providers.keys())

    # Prints:
    # C1 providers dict_keys(['a1'])
    # C2 providers dict_keys(['a2', 'a1'])
    # C3 providers dict_keys(['a3', 'a2'])  <---- NO 'a1'

    c3 = C3(a1='foo')  # Raises AttributeError: 'DynamicContainer' object has no attribute 'a1'
```

**Comment by rmk135** [comment]
Working on a fix.

**Comment by rmk135** [comment]
Released a fix in `4.8.1`. 

```python
from dependency_injector import containers, providers


class C1(containers.DeclarativeContainer):
    a1 = providers.Dependency(instance_of=str)


class C2(C1):
    a2 = providers.Callable(C1.a1)


class C3(C2):
    a3 = providers.Callable(C2.a1)


if __name__ == '__main__':
    print('C1 providers', C1.providers.keys())
    print('C2 providers', C2.providers.keys())
    print('C3 providers', C3.providers.keys())

    # Prints:
    # C1 providers dict_keys(['a1'])
    # C2 providers dict_keys(['a2', 'a1'])
    # C3 providers dict_keys(['a3', 'a2', 'a1'])

    c3 = C3(a1='foo')  # No error
```

**Comment by rmk135** [comment]
@shaunc , thanks for finding this one. It was kind of tricky and there were no tests for 2+ levels of inheritance. Many thanks!

**Comment by rmk135** [comment]
Closing the issue. Re-open if needed.
