### ISSUE TITLE
inheritance & dependencies

### ISSUE THREAD

**Issue by shaunc** [ets-labs/python-dependency-injector#351]
Hello! You helped me out already more than once, but I admit I'm getting tremendously frustrated, as I just don't have an adequate insight to what is happening under the hood.

Let me sketch my problem -- my current code has gone through so many failed experiments I'm sure it looks ridiculous.

I have a `Problem` container (for a machine learning problem), and two hierarchies of other containers:

`ProblemView` -> `Conjoiner` -> `GroundConjoiner`

`ProblemView` -> `CutsContext`

Here, problem view refers to a problem via:

```python
class ProblemView(containers.DeclarativeContainer):

    problem = providers.DependenciesContainer()
```
And it takes optional dependencies that override parts of `Problem`, e.g.:
```python
    ...
    weight: Provider[xr.DataArray] = providers.Dependency(
        instance_of=xr.DataArray
    )
    weight.override(problem.training.provided.weight)
```
Then it redefines parts of problem based on possibly overridden values:
```python
    training = providers.Callable(
        override_weight, problem.training.provided, weight.provided
    )
```
ProblemView works on its own.

Next, Conjoiner is a problem view (Or has a problem view -- though I'd prefer is a problem view so it can inherit "has a problem" -- but either way I can't get it to work). It takes a CutsContext as a dependency.

```python

@container.copy(ProblemView)
class Conjoiner(ProblemView):
    cuts = providers.Container(CutsContext)
```
And `GroundConjoiner` (among others) is a `Conjoiner`; it provides a `CutsContext` to parent `Conjoiner` with given overall `problem` and `weights` (as well as some other customization specific to CutsContext).

```python
@container.copy(Conjoiner)
class GroundConjoiner(Conjoiner):
    problem = Conjoiner.problem    # or...?
    weight = Conjoiner.weight

    # also tried (and same for weight)
    # problem_ = Conjoiner.problem
    # problem = providers.DependenciesContainer()
    # problem_.override(problem)

    ground_cuts_context = providers.Container(
        Cuts,
        problem=problem, weight=weight
        ...
    )
    cuts_context = ground_cuts_context.provided 
```
Instantiation:
```python
gc = GroundConjoiner(problem=problem, weight=weight)
```
I have tried different permutations all weekend (under a looming deadline :(), and can generate many different errors (either some dependency not defined, or -- e.g. `src/dependency_injector/providers.pyx:1080: in dependency_injector.providers.ConfigurationOption.__init__: TypeError: cannot create weak reference to 'dependency_injector.providers.ProvidedInstance' object`), but I can't glean from the documentation any insight into what is going on sufficient to alight on a correct solution (or even a clear bug report). 

I'll be very grateful for any help!

**Comment by rmk135** [comment]
Hey @shaunc , I'll take a look. Will take some time for debugging. I'll get back as soon as I got something.

**Comment by shaunc** [comment]
Wonderful! -- Thanks!

**Comment by shaunc** [comment]
Just a thought -- perhaps it would be useful to provide a "container mixin base" -- whose derived classes wouldn't be containers themselves, but would contribute providers if/when they were mixed into a container. Untangling the logic when just the last step is actually a container might be easier.

**Comment by shaunc** [comment]
BTW -- Here is the overall diagram of my containers. 

A Conjoiner PatternFilter containers. A single Booster has multiple conjoiners sharing cuts and problem views. Subsequent Boosters derive new problem views and cuts.

[I've eliminated the ISA on ProblemView -- more natural as a "has" (though would be nice to have a mixin to define shortcuts to problem pieces), but GroundConjoiner and NextConjoiner should still be conjoiners, and the same with GroundBooster and NextBooster.]

I guess overall this is a bit different use case than a typical application setup... I thought it would be good for DI as, while there is a DAG for data flow, various things (diagnostics, parameters, which algorithm to use, etc) are customizable. I also thought with the persistent caching factory I could easily stop and restart. I also experimented with workflow engine (prefect) -- that is great for deploying to dask/kubernetes, but task-centric approach isn't so good for composing whole "tiles" of workflow. I guess stacking lots of tiles dynamically isn't typical for this package either.

[EMM Model Building Containers.pdf](https://github.com/ets-labs/python-dependency-injector/files/5805494/EMM.Model.Building.Containers.pdf)

**Comment by shaunc** [comment]
This issue is more a cry of frustration than a bug report. I think between your fixing the other bugs and my finding workarounds, I might have found a path to get things to work. You are welcome to close this in favor of the other more specific issues. I will try to create issues for any more specific bugs after you fix the current round.

**Comment by rmk135** [comment]
Hey @shaunc ,

I'm very sorry that Dependency Injector caused the frustration. Indeed, I have never tried to build applications like you build. All the examples you see in the docs far more naive. I've run through the issue and diagram several times and didn't get the problem. With all my willing to help, I don't understand the mechanics of the system you build. I have a feeling that problem solution is in one missing piece of the framework, but I haven't yet realized what piece it is.

Regarding the mechanics of the Dependency Injector. In documentation I focus on API description than on under-the-hood mechanics. I made this decision to don't confuse people with details they don't need. I think you're in different situation here. I don't hide any design decisions and I'm very positive to talk about them. If you have any particular questions - you're welcome. Just open an issue and provide a minimal example. I know that it's basically what you did with this issue. The problem with the current one is that I don't understand your example. I will try to go through the example again a couple of times. I have a feeling that there is a simple and effective solution.

What's on my mind now is that I feel some kind of overusing the `DependenciesContainer`. Let me try to explain its initial purpose. `DependenciesContainer` provider came to the game to be a list of dependencies for the container that doesn't look as any other existing container. It has a lazy interface where you can create the provider and use its attributes:

```python
class ProblemView(containers.DeclarativeContainer):

    problem = providers.DependenciesContainer()
    
    some_object = providers.Factory(SomeClass, problem.some_provider)
```

When you create a container like this you need to specify `problem.some_provider`. You can use instance of some other container or create a dynamic container:

```python
problem = DynamicContainer()
problem.some_provider = providers.Object('foo')

problem_view = ProblemView(problem=problem)

# or

class Problem1(containers.DeclarativeContainer):
    some_provider = providers.Object('foo1')
    

class Problem2(containers.DeclarativeContainer):
    some_provider = providers.Object('foo2')

problem_view = ProblemView(problem=Problem1())
problem_view = ProblemView(problem=Problem2())
```

Not depending on the way you provide dependencies to `DependenciesContainer`, when you use lazy mode, `DependenciesContainer` attributes will be `Dependency` provider overridden by what was provided on container initialization:

```python
problem = DynamicContainer()
problem.some_provider = providers.Object('foo')

problem_view = ProblemView(problem=problem)
assert isinstance(problem_view.problem.some_provider, providers.Dependency)
assert problem_view.problem.some_provider.last_overriding is problem.some_provider
```

You can also stay on explicit side and specify the dependencies for `DependenciesContainer`  when initialize it:

```python
class ProblemView(containers.DeclarativeContainer):

    problem = providers.DependenciesContainer(
        some_provider=providers.DependenciesContainer(
            other_provider=providers.Factory(...),
        ),
    )
    
    assert isinstance(problem.some_provider, providers.DependenciesContainer)
    assert isinstance(problem.some_provider.other_provider, providers.Factory)
```

The `Container` provider is an opposite of `DependenciesContainer`. It requires other container class to know the structure and provide actual provider types from this container.

A suggestion I have is to replace `DependenciesContainer` in your example with the individual `Dependency` provider:

```python
class ProblemView(containers.DeclarativeContainer):

    some_provider = providers.Dependency(instance_of=SomeClass)
    other_provider = providers.Dependency(instance_of=OtherClass)

ProblemView(some_provider=..., other_provider=...)
```

If that's possible, it will help to make more explicit dependencies and flatten the structure.

PS: Appreciate if you could continue this conversation in this or other issues. I'm interested in making Dependency Injector to be a useful tool. Your output can bring it to the next level.

**Comment by shaunc** [comment]
Regarding the concrete suggestion -- does converting a DependenciesContainer into a Dependency work if the dependency is a container? For one thing, instances of containers aren't actually instances of their Container classes -- this I can get around by using `instance_of=containers.DynamicContainer` ... but then I seem to have problems dereferencing elements -- especially if I have to go through more than one layer (`foo.provided.bar.provided ...`?).

---
Let me explain why I'm trying to use DI as I am trying to do. Machine learning requires the execution of a complex data flow graph in which many of the edges follow standard patterns, but often you want to modify/configure/extend when facing a given problem. Existing frameworks use "pipelines" which then compile into low-level operations. But this leaves a very big gap between high-level representation and low-level; also, while the compilers are very sophisticated, they are extremely hard to extend (I've tried! :)). 

My idea was to use DI to create composable "tiles" in a machine learning framework data flow graph which can be customized/configured before (or while) being run.  In a sense I am trying to use it as a very rudimentary version of [nGraph](https://docs.openvinotoolkit.org/latest/openvino_docs_nGraph_DG_Introduction.html).

I can flatten somewhat, but, as compositionality is a goal, I'd rather use the DI containers directly than create helper functions/classes/wrappers. (Though I can if that's really the best way forward.)

I started out trying to use [Prefect](https://docs.prefect.io) -- as distribution and running in Kubernetes is one of my goals. However, they require everything to be specified as tasks and workflow edges, and have limited capabilities for dynamically modifying their `flows`, while I do want to be able to directly manipulate & schedule larger chunks. On the other hand, I decided I would get more bang for my buck by concentrating on GPU use rather than distribution at first.

That said -- at some point I will want to distribute graphs. (Probably in the late spring/summer.) In conjunction with this it would be great if DI containers had some introspection capabilities. (For instance, for a provider, what other providers does it depend on ... eventually would be great to be able to access forward links as well; also, what container does a dependency live in -- even "anonymous" ones that are created on the fly as part of another.) 

That would be more of my roadmap -- but for the moment, compositionality is very important to me. I gather that, for typical application setup, much flatter structures suffice. As I said, I can flatten my current structures somewhat. But since composing containers is very much my goal, I do want it to work easily & transparently, regardless of whether, in certain cases, I could avoid it now.

I don't know if that makes sense to you -- or if you really do want to support my use case. But I thought I'd explain so you can understand where I'm coming from. Further questions appreciated, and thank you very much for your package, and your responsiveness!

**Comment by rmk135** [comment]
Does feature from #357 helps with resolving current one?

**Comment by shaunc** [comment]
I think so. I guess there are some situations involving inheritance that #357 doesn't exhibit. Once I unwind my current workarounds I should be able to say. Thank you!

**Comment by shaunc** [comment]
Ok -- I think my containers are basically working. I have some ideas for improvement -- I'll submit separately as feature requests. Thank you for your support, and your great package!

**Comment by rmk135** [comment]
Glad to help! Thanks for your patience and input to make Dependency Injector to be a better tool.
