### ISSUE TITLE
feature request: provider for "self"

### ISSUE THREAD

**Issue by shaunc** [ets-labs/python-dependency-injector#364]
I would like a provider to be able to pass a container as an argument:
```python
class Container(containers.DeclarativeContainer):

    foo = providers.Callable(calc_foo, containers.MarkerForContainer)
    bar = providers.Object('hello')

container = Container()
container.override_providers(container=container)

def calc_foo(container):
    print(container.bar())

container.foo()  # prints "hello" - ?
```
I assume that is impossible to do directly, right now? I guess perhaps I could do:
```python

class Container(containers.DeclarativeContainer):

    container = providers.DependenciesContainer()
    foo = providers.Callable(calc_foo, container)
    bar = providers.Object('hello')

container = Container()
container.override_providers(container=container)

def calc_foo(container):
    print(container.bar())

container.foo()  # prints "hello" - ?
```

But having the container work without having to put cheese in it (to use a mousetrap analogy) would be great... any chance of something like the former (if indeed it isn't possible)?

**Comment by rmk135** [comment]
Hey @shaunc , caught it.

**Comment by rmk135** [comment]
I'm working on this feature now. Already have prototype. Plan to release by Monday.

**Comment by shaunc** [comment]
Great -- thanks!

**Comment by rmk135** [comment]
Done: https://python-dependency-injector.ets-labs.org/containers/inject_self.html

**Comment by rmk135** [comment]
@shaunc  Closing this issue. Let me know if you have any questions.

**Comment by shaunc** [comment]
Just a small doc comment/suggestion -- if I didn't know about this feature, I might search for it in "providers." Having the main doc page under containers is fine, but maybe have a link to it on the main "providers" page?

**Comment by rmk135** [comment]
Hm,  that's a good idea, you're right. I think I'll just move it under "Providers."

**Comment by rmk135** [comment]
Moved: https://python-dependency-injector.ets-labs.org/providers/inject_self.html

**Comment by rmk135** [comment]
Thanks @shaunc
