### ISSUE TITLE
feature request: provider dependency introspection

### ISSUE THREAD

**Issue by shaunc** [ets-labs/python-dependency-injector#366]
I would like to have a way to get the dependent providers for a given provider. Traversing dependency links forward would also be nice (though not as important), as would getting the container for a given provider.

Uses cases:

1. I am writing containers as configurable "tiles" in a machine learning pipeline framework (explained elsewhere). Once I am able to build and run common pipelines, my next step will be to distribute the computation over several nodes. To do this I want to be able, for a given provider, trace back its dependencies to certain marked providers, whose outputs can be transformed into artifacts which I can distribute.
2. This issue would also be helped: https://github.com/ets-labs/python-dependency-injector/issues/195#issue-317750741
3. Just wrote a little testing tool to look for unfulfilled dependencies using the new `Container.dependencies`. Unfortunately, while it works for directly fulfilled dependencies, I don't know how to step into and inspect dependencies satisfied by other providers (which could depend on other dependencies).

**Comment by rmk135** [comment]
Hey @shaunc ,

I have released a feature to traverse container providers. Take a look at https://python-dependency-injector.ets-labs.org/containers/traversal.html

You can also use ``Provider.related`` attribute to get any related providers. This includes injections, dependencies, overridings, etc. Attribute ``Provider.related`` is implemented by all providers.

To traverse specific provider's graph use ``Provider.traverse()`` method. To get all provider dependencies you can use types filtering: ``Provider.traverse(types=[Dependency])``.

Finally, there is ``traverse()`` function in the ``dependency_injector.providers`` module. You can use it traverse several providers ``providers.traverse(provider1, provider2)``. It also supports types filtering ``providers.traverse(types=[...])``.

For now I have only documented container traversal feature. I appreciate to get your feedback before publishing the providers API part.

**Comment by shaunc** [comment]
Wonderful -- thanks! I'll take a look. 

It will probably be a week before I try to use `Provider.traverse()` -- will give you feedback when I do.

**Comment by rmk135** [comment]
Got it, sounds good!

**Comment by shaunc** [comment]
Ok -- looking good on a first run-though! In fact, I'm probably a couple months away from actually using this to distribute my workflows. So you've gotten ahead of me! :) 👍 

I guess I'll close for the moment. If I run into problems when I start using it more extensively, I can open up issues then. Thank you!

**Comment by rmk135** [comment]
Sounds good. Thank you @shaunc .
