### ISSUE TITLE
Cannot import name 'Container' from 'dependency_injector.containers'

### ISSUE THREAD

**Issue by ventaquil** [ets-labs/python-dependency-injector#386]
Hey!

I am trying to add type annotations to my Python code wherever I can. I created simple functions to init/shutdown resources in nested containers:

```py
from dependency_injector.containers import Container
from dependency_injector.providers import Container as ContainerProvider


def init_resources(container: Container) -> NoReturn:
    container.init_resources()
    for provider in container.providers.values():
        if isinstance(provider, ContainerProvider):
            init_resources(provider)


def shutdown_resources(container: Container) -> NoReturn:
    container.shutdown_resources()
    for provider in container.providers.values():
        if isinstance(provider, ContainerProvider):
            shutdown_resources(provider)
```

I see that `containers.pyi` declares `Container` class but it seems that containers don't have `Container` parent at all.

I can prepare PR with abstract `Container` class.

**Comment by rmk135** [comment]
Btw, starting from version  `4.14.0` you don't need to have these recursive functions. When you call `.init_resources()` on root container, it will initialize all nested resources. The same for shutdown. If you have other recursive functions, see new feature: https://python-dependency-injector.ets-labs.org/containers/traversal.html

**Comment by rmk135** [comment]
Fixed in ``4.16.0``. Thanks for reporting the problem. Closing  the issue, re-open if needed.

**Comment by ventaquil** [comment]
I haven't time yet to do it on my own 😢

Thank you for fix and recommendations about `.init_resources()`.

**Comment by rmk135** [comment]
> I haven't time yet to do it on my own 😢

No worries! Thanks for finding time to report the issue. It helps to improve Dependency Injector.
