### ISSUE TITLE
Q: Singleton Provider Referencing a Singleton Provider

### ISSUE THREAD

**Issue by cameroncurrey** [ets-labs/python-dependency-injector#387]
Amazing library! Thank you for building this!

One question I had was in regards to Singletons referencing other Singleton providers and how [reset](https://python-dependency-injector.ets-labs.org/api/providers.html?highlight=reset#dependency_injector.providers.Singleton.reset) comes into play.

For example if I have the following:

```
from dependency_injector import containers, providers

class MyContainer(containers.DeclarativeContainer):
    database = providers.Singleton(
         MyDatabase,
         connection_string="some connection string",
    )
    
    service = providers.Singleton(
        MyService,
        database=database,
    )
```

The singleton referenced by "MyService" will always be the same instance in "MyDatabase" unless [reset](https://python-dependency-injector.ets-labs.org/api/providers.html?highlight=reset#dependency_injector.providers.Singleton.reset) is called on the database and the service.

```
In [30]: id(MyContainer.database())
Out[30]: 4370026304

In [31]: id(MyContainer.database())
Out[31]: 4370026304 # <- Same reference. Good!

In [32]: id(MyContainer.service()._database)
Out[32]: 4370026304 # <- Still same reference. Good!

In [33]: MyContainer.database.reset()

In [34]: id(MyContainer.database())
Out[34]: 4370026355 # <- New reference, as expected.

In [35]: id(MyContainer.service()._database)
Out[35]: 4370026304 # <- Ruhoh. Still holding the same reference. Meaning we have two MyDatabase instances floating around.
```
Obviously if I don't call reset on database there is no problem, or if I do, I can reset database then reset the service.

My question is, does the library itself ever call "reset" on itself? If so, how and when would it do that? My concern is using Singletons like this may inadvertently keep multiple active connections to my database alive.

Thanks for any information you can provide!

**Comment by rmk135** [comment]
Hey @cameroncurrey ,

No, Dependency Injector doesn't  call ``.reset()`` by its own.

The problem you face is known and I'm willing to fix it. I have introduced new providers traversal API that unlock a lot of useful features. As a workaround you can do:

````python
for child_singleton in singleton.traverse(types=[providers.Singleton]):
    child_singleton.reset()
```

I will think how to incorporate this code into ``Singleton``. I believe it should be the default behaviour, but I worry that it's a contract-breaking change. I'm currently thinking about introducing a parameter. Something like:

```python
singleton.reset(full=True)
```

or a new method:

```python
singleton.full_reset()
```

If you have any ideas about the interface or naming - you're very welcome to share.

**Comment by cameroncurrey** [comment]
Hey @rmk135,

Your answer `No, Dependency Injector doesn't call .reset() by its own.` helps. My usage never actually calls `reset`, so for me it is not a problem. My concern was if it could happen from underneath the hood, which could cause all sorts of problems for my particular use case.

-If- I did have a need to call `reset`, I think the
```
singleton.full_reset()
```
option makes a lot of sense. It totally makes sense you wouldn't be able to change the existing implementation.

Thanks again for such an awesome library. I'm a fan.

**Comment by rmk135** [comment]
Hey @cameroncurrey ,

> My concern was if it could happen from underneath the hood, which could cause all sorts of problems for my particular use case.

Got it. No, it does not happen, so you're on a safe side.

--------

As of full reset I also prefer ``singleton.full_reset()``. I'll add the feature into the backlog.

--------

> Thanks again for such an awesome library. I'm a fan.

Thank you for the warm words. It motivates to support and improve it.

**Comment by rmk135** [comment]
I'm closing the issue. Feel free to re-open if needed.
