### ISSUE TITLE
Using dynamic containers with Fastapi endpoint.

### ISSUE THREAD

**Issue by marvfinsy** [ets-labs/python-dependency-injector#401]
I have not been able to find any documentation/examples on how to setup an endpoint using dynamic containers. All i've seen is: 
def create_transaction(
    dbengine: MyDbEngine = Depends(Provide[DiContainer.dbengine_provider])
    )
   
Of course this doesn't work for dynamic containers since i have no declarative container called DiContainer. Am i correct here? I'm sure i'm missing something here being new to python etc...

thx ~MarvinB

**Comment by rmk135** [comment]
@marvfinsy ,

Quick question: you're looking for something like that, correct?

```python
import sys

from fastapi import FastAPI, Depends
from dependency_injector import containers, providers
from dependency_injector.wiring import inject, Provide


class Service:
    async def process(self) -> str:
        return 'Ok'


container = containers.DynamicContainer()  # <-- Dynamic container
container.service = providers.Factory(Service)

app = FastAPI()


@app.api_route('/')
@inject
async def index(service: Service = Depends(Provide[container.service])):  # <-- Dynamic container
    result = await service.process()
    return {'result': result}


container.wire(modules=[sys.modules[__name__]])
```

**Comment by marvfinsy** [comment]
yes... the only concern i have is how to create the dynamic
container during startup. i would have to somehow have access to it later
during the endpoint call.

**Comment by rmk135** [comment]
>the only concern i have is how to create the dynamic
container during startup.

Right, I understand that it might be problematic.

Generally design goes to something like this:

```python
@app.api_route('/')
@inject
async def index(service: Service = Depends(Provide['service'])):  # <-- string id
    result = await service.process()
    return {'result': result}
```

I can implement `Provide[container.service]`  in a couple of days. String identifiers implementation will take more time. Let me know if you're interested having `Provide[container.service]` earlier. Otherwise I will release it with string identifiers.

**Comment by marvfinsy** [comment]
Morning... l like the idea of the string identifiers... it's well worth the wait...

**Comment by rmk135** [comment]
Good morning. Ok, sounds good. I'll keep working on it.

**Comment by rmk135** [comment]
Hey @marvfinsy ,

Wiring by string id is ready. You can find docs here: https://python-dependency-injector.ets-labs.org/wiring.html#strings-identifiers

Thanks for sharing the problem.

I'm closing the issue. Feel free to comment.

**Comment by marvfinsy** [comment]
cool... thx

**Comment by marvfinsy** [comment]
i've been trying to get things to work without the Container declaration.
no success... the Provide call is returning a object of type :
dependency_injector.wiring.Provide
object at 0x1061c3310>

in code.

def myfunc( dbengine: Provider['dbengine_provider'] )
the variable dbengine now has the type,  dependency_injector.wiring.Provide
object at xxxxxxxxx.
if i try dbengine.provider()... it crashes. looks like trying to run str()
on the object. see below:
Traceback (most recent call last): File "<string>", line 1, in <module>
TypeError: 'str' object is not callable


~Marvin Foster

**Comment by rmk135** [comment]
Looks like you improperly specified "Provide" marker. It should be specified as argument's default, not type annotation. Change `def myfunc( dbengine = Provider['dbengine_provider'] )`.

**Comment by marvfinsy** [comment]
No that was a typo on my part. Here is the endpoint method:

@router.get("/v1/sticky-settings/{userid}", response_model
=StickyDataResponse)
@inject
def get_setting(
userid: int,
dbengine: MyDbEngine = Depends(Provide['dbengine_provider']),
ourlogger: logging.Logger = Depends(Provide[DiContainer.logger_provider])
):

in this case the dbengine is set as mentioned above. ourlogger is using
standard way of doing things and is working fine.
This is the container declaration located in another module:

class DiContainer(containers.DeclarativeContainer):

config = providers.Configuration()

logger_provider = providers.Singleton(
MyLogger
)

app_config_provider = providers.Singleton(
ConfigSettings
)

dbengine_provider = providers.Singleton(
MyDbEngine,
config=app_config_provider()
)


One difference is with my container being in a separate module. The other
is this method is being called later in processing when the endpoint is
called via the framework.

~Marvin

**Comment by rmk135** [comment]
Alright, I’ll take a look. May be I missed something somewhere.

**Comment by rmk135** [comment]
@marvfinsy ,

Could you check how you call ``container.wire(...)``? Make sure you wire to the proper modules or packages.

<img width="403" alt="Screenshot 2021-02-24 at 10 06 38" src="https://user-images.githubusercontent.com/1742049/109020884-6100bc00-7688-11eb-8755-87d965d308d3.png">

Here is a sample application:
<img width="193" alt="Screenshot 2021-02-24 at 10 06 27" src="https://user-images.githubusercontent.com/1742049/109020907-665e0680-7688-11eb-841e-ab50bf91b2b7.png">

Endpoints module:
```python
import logging

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from dependency_injector.wiring import inject, Provide

from .containers import DiContainer
from .db import MyDbEngine


class Response(BaseModel):
    user_id: str


router = APIRouter()


@router.get("/{userid}", response_model=Response)
@inject
def get_setting(
        userid: int,
        dbengine: MyDbEngine = Depends(Provide['dbengine_provider']),
        ourlogger: logging.Logger = Depends(Provide[DiContainer.logger_provider])
):
    ourlogger.info('Handle request, user id: %s, use db engine: %s', userid, dbengine)
    return {'user_id': userid}
```

App module:

```python
from fastapi import FastAPI

from .containers import DiContainer
from . import endpoints


app = FastAPI()
app.include_router(endpoints.router)

container = DiContainer()
container.wire(modules=[endpoints])
```

Also verify that you're using version ``4.26.0`` or above.

**Comment by marvfinsy** [comment]
thx for all ur help... did get it working... "user error" (my error)...

when i updated to 4.26 i had not activated my virtual environment (still
new using this active virtualenv). also when i checked versions i had not
activated the virtual environment. Once i activated the environment i
realized i was still using 4.20. Upgraded active environment and all works.

thx again... ~Marvin

**Comment by rmk135** [comment]
Good, nice to hear it works! Thanks Marvin.

**Comment by mancioshell** [comment]
Hi, i'm using FastApi and dependency-injector 4.40.0.

I have this container:

`
class CQRSCustomerControllerContainer(containers.DeclarativeContainer):

    settings = AWSSettings()
    dynamodb_settings = AWSDynamoSettings()

    aws_client = providers.Factory(AWSClient, aws_service="dynamodb", settings=settings)

    aws_dynamo_service = providers.Factory(
        AWSDynamoService,
        settings=dynamodb_settings,
        aws_client=aws_client,
    )

    read_customer_controller = providers.Singleton(
        CqrsReadCustomerController, aws_dynamo_service=aws_dynamo_service
    )
`

and this router, where i try to inject my controller:

`
@router.get("/customers", response_model=list[ReadCustomer], tags=["customers"])
@inject
async def find_all(
    read_controller: CqrsReadCustomerController = Depends(
        Provide[CQRSCustomerControllerContainer.read_customer_controller]
    ),
) -> Any:

    print(read_controller)
    customers = await read_controller.find_all()
    return customers
`

This is main file:

`
from pltm021 import controllers
...
app = FastAPI(
        ...
    )
    
    app.include_router(controller.router)

    cqrs_container = CQRSCustomerControllerContainer()
    cqrs_container.wire(modules=[controllers])

`

when i try to access the CqrsReadCustomerController instance in my routing file, i obtain:
<dependency_injector.wiring.Provide object at 0x000001C44E0BFAF0> and not the real object i should use in my application.

Any hints where i'm doing something wrong ?

**Comment by chbndrhnns** [comment]
> Any hints where i'm doing something wrong ?

I am happy to take a look but usually prefer a small repo with the minimal (not) working example.
