### ISSUE TITLE
[Question] What does the @inject decorator do?

### ISSUE THREAD

**Issue by ecs-jnguyen** [ets-labs/python-dependency-injector#404]
Hi I am playing around with the dependency_injector library and I am trying to find out what the `@inject` decorator does. I have tried this sample program with and without the `@inject` decorator and noticed no difference. Is the `@inject` decorate necessary?

```
import sys
import uuid

from dependency_injector import containers, providers
from dependency_injector.wiring import inject, Provide


class Service:
    def __init__(self):
        self.uuid = uuid.uuid4()


class Container(containers.DeclarativeContainer):

    service = providers.Factory(Service)


@inject # Commenting this out has no effect on the program
def main(service: Service = Provide[Container.service]) -> None:
    print(service.uuid)


if __name__ == '__main__':
    container = Container()
    container.wire(modules=[sys.modules[__name__]])

    main()
```

**Comment by rmk135** [comment]
Hi @ecs-jnguyen ,

That's a very good question. My pleasure to provide an explanation.

Decorator ``@inject`` registers functions and methods in wiring module.

Why that's needed? The answer is in how wiring works. Wiring introspects a module and looks for any functions or methods that have ``Provide`` markers. That works fine, but there are some cases when it's impossible to introspect properly.

Case 1 is closures:

```python
def foo():
    @inject
    def bar(x = Provide[...]):  # no way to reach it with introspection
        ...
```

Case 2 is replacing class decorators. The example of this  is ``click`` library. Its decorator is class-based. This class based decorator hides the actual callable in the internals. No guarantee that it can be introspected:

```python
@click.command()
@click.option('-c', '--configuration-file', help='Configuration file path', default='config.yml')
@click.argument('test_key')
@inject  # Registers it in wiring module before the reference is masked by click class
def cli(test_key, configuration_file, config: Config = Provider[Container.config]) -> None:
    ...

print(type(cli))  # Output: <class 'click.core.Command'>
```

Case 3 is memorizing decorator. This is typical for web and api frameworks when defining the routes. Framework decorator memorizes a reference to the function before the wiring happens. Even when wiring passes later, other framework keeps reference to pre-wiring-decorated callable:

```python
from fastapi import APIRouter, Depends

router = APIRouter()


@router.get('/', response_model=Response)
@inject  # Registers it in wiring module before router has memorized pre-decorated function
async def index(
        query: Optional[str] = None,
        limit: Optional[str] = None,
        default_query: str = Depends(Provide[Container.config.default.query]),
        default_limit: int = Depends(Provide[Container.config.default.limit.as_int()]),
        search_service: SearchService = Depends(Provide[Container.search_service]),
):
    ...
```

Early versions of the Dependency Injector ``4`` didn't have ``@inject`` decorator. It worked fine when framework could introspect. I've added ``@inject`` after discovered cases above. To not confuse people with the rules, I recommend to use ``@inject`` all the time. It gives a guarantee that wiring will find the markers.

**Comment by ecs-jnguyen** [comment]
@rmk135 Thank you for answering my question! I appreciate the time and effort you guys put into all this!

**Comment by rmk135** [comment]
No problems, thanks for asking.

PS: When you say "you guys" it's actually only me for now.

**Comment by ecs-jnguyen** [comment]
@rmk135 Sorry to message you after you closed the issue. I have 1 more quick question.

I'm trying to find a way to use the `Provide[...]` as much as possible so that there is less setup for each application. I saw that in your I saw in your [application example](https://python-dependency-injector.ets-labs.org/examples/application-multiple-containers.html) that none of the classes in `example/services.py` and you are wiring everything inside the `Application` container. 

Do you recommend initializing multiple containers and calling the `container.wire(module=[...]` method like I have done below?

```
import sys

from dependency_injector import containers, providers
from dependency_injector.wiring import inject, Provide

import uuid


# This would be in ConfigContainer.py
class ConfigContainer(containers.DeclarativeContainer):
    config = providers.Configuration(default={'key': 'value'})


# This would be in ClientA.py
class ClientA:
    def __init__(self, config: dict = Provide[ConfigContainer.config]):
        self.uuid = uuid.uuid4()
        self.config = config


# This would be in ClientA.py
class ClientsContainer(containers.DeclarativeContainer):
    services = providers.Singleton(ClientA)


# This would be in ServiceA.py
class ServiceA:
    @inject
    def __init__(self, client_a: ClientA = Provide[ClientsContainer.services]):
        self.client_a = client_a

    def print(self):
        print(self.client_a.uuid)
        print(self.client_a.config)


# main python script
class ApplicationContainer(containers.DeclarativeContainer):
    services_container = providers.Container(ClientsContainer)


def main() -> None:
    app_container = ApplicationContainer()
    app_container.wire(modules=[sys.modules[__name__]])

    config_container = ConfigContainer()
    config_container.config.from_dict({'key': 'otherValue'})
    config_container.wire(modules=[sys.modules[__name__]])

    client_container = ClientsContainer()
    client_container.wire(modules=[sys.modules[__name__]])

    a = ServiceA()
    a.print()


if __name__ == '__main__':
    main()

```

**Comment by ecs-jnguyen** [comment]
Btw I edited the code. I just realized in my example the `ApplicationContainer` class does nothing in this case.

**Comment by rmk135** [comment]
> Do you recommend initializing multiple containers and calling the container.wire(module=[...] method like I have done below?

There's nothing bad in it, but I would recommend to gather everything in a single container. Wiring feature role is to ease the integration with other frameworks. Your own code typically could not use wiring. The idea is that you gather everything in the container and then use wiring to inject your components to the framework of your choice. That was an initial idea, but that's not a mandatory rule. You could have multiple containers and wire them to the any part of the code without any limitations.

Btw, in case you face circular imports problem you can use wiring with string identifiers https://python-dependency-injector.ets-labs.org/wiring.html#strings-identifiers

**Comment by ecs-jnguyen** [comment]
@rmk135 Thanks for getting back to me. using the 'string' identifiers should help. Hopefully i don't run into any circular dependencies lol

**Comment by rmk135** [comment]
I'm closing this issue. Open a new one if any help needed.

**Comment by solvit-team** [comment]
Hello,

Thank you for the detailed explanation about `@inject` and wiring in the Dependency Injector library.

> Case 1 is closures:
> ```python 
> def foo():
>     @inject
>    def bar(x = Provide[...]):  # no way to reach it with introspection
>         ...
> ```

I am trying to understand the limitation regarding closures and wiring. Here is a minimal example illustrating the issue:

```python
from dependency_injector import containers, providers
from dependency_injector.wiring import Provide, inject


class MyService:
    def get_message(self):
        return "Hello from MyService"


class MyContainer(containers.DeclarativeContainer):
    test_service = providers.Factory(MyService)


def outer_fn():
    @inject
    def hello_world(service=Provide[MyContainer.test_service]):
        print(service.get_message())

    return hello_world


container = MyContainer()
container.wire([__name__])


if __name__ == "__main__":
    outer_fn()  # The injected service is not provided here, causing an error
```

In this example, hello_world is defined inside outer_fn as a closure and decorated with @inject. However, when calling outer_fn(), the injection does not work because the wiring happens before hello_world is created, so it is not detected and wired properly.

I have a few questions:

- You mentioned that `@inject` was introduced to help solve such problems with closures, but since wiring must happen before the closure is created, how does `@inject` actually help in this scenario?
- What are some concrete, real-world use cases where injecting dependencies into closures or dynamically created functions is necessary or beneficial?
- How do you recommend handling dependency injection in such cases where the function does not exist at module load time and wiring cannot detect it?

Thank you very much for your help and clarification

**Comment by PunchyRascal** [comment]
@solvit-team I feel like the closures work only if they are brought to the outer level and THEN wired.

For example in case of decorators (@wraps), that works fine - only you need to wire the call sites, not the decorator definition. Because unless the closure is brought to light so to speak, the DI does not see it.

So in your example, changing it like so:
```python
def outer_fn():

    @inject
    def hello_world(service = Provide["test_service"]):
        print("Closure inject: " + service.get_message())

    return hello_world


if __name__ == "__main__":
    container = MyContainer()
    xxx = outer_fn()
    container.wire(modules=["scratch", "__main__"])
    xxx()


# gives: Closure inject: Hello from MyService
```

Whether that is helpful for you case is another matter.
