### ISSUE TITLE
Using aws session to create clients results in "TypeError: client() missing 1 required positional argument: 'self'"

### ISSUE THREAD

**Issue by ecs-jnguyen** [ets-labs/python-dependency-injector#405]
Hi I'm trying to use the boto3 session in a container to create new boto3 clients. I'm running into the error `"TypeError: client() missing 1 required positional argument: 'self'"`. Am I setting this up correctly?

```python
import boto3.session

class Boto3ContainerWorking(containers.DeclarativeContainer):
    config = providers.Configuration()

    session = providers.Singleton(
        boto3.session.Session,
        aws_access_key_id=config.aws_access_key_id,
        aws_secret_access_key=config.aws_secret_access_key,
        aws_session_token=config.aws_session_token
    )

    s3_client = providers.Singleton(
        session().client,  # <------ this works
        service_name='s3'
    )


class Boto3ContainerNotWorking(containers.DeclarativeContainer):
    config = providers.Configuration()

    session = providers.Singleton(
        boto3.session.Session,
        aws_access_key_id=config.aws_access_key_id,
        aws_secret_access_key=config.aws_secret_access_key,
        aws_session_token=config.aws_session_token
    )

    s3_client = providers.Singleton(
        session.provides.client,   # <------ this doesn't work
        service_name='s3'
    )


def main_not_working():
    container = Boto3ContainerNotWorking()
    container.init_resources()
    container.wire(modules=[sys.modules[__name__]])

    s3_client = container.s3_client()  # breaks here with "TypeError: client() missing 1 required positional argument: 'self'"


def main_working():
    container = Boto3ContainerWorking()
    container.init_resources()
    container.wire(modules=[sys.modules[__name__]])

    s3_client = container.s3_client()  # This passes
```

**Comment by rmk135** [comment]
Try to replace ``session.provides.client`` with ``session.provided.client``.

**Comment by ecs-jnguyen** [comment]
@rmk135 I got a different issue `TypeError: __init__() got an unexpected keyword argument 'service_name'`

**Comment by rmk135** [comment]
Alright. I’m away from computer now. Will take a look in the morning.

**Comment by rmk135** [comment]
@ecs-jnguyen here is a working code sample:

```python
import boto3.session
from dependency_injector import containers, providers


class Service:
    def __init__(self, s3_client, sqs_client):
        self.s3_client = s3_client
        self.sqs_client = sqs_client


class Boto3Container(containers.DeclarativeContainer):

    config = providers.Configuration()

    session = providers.Resource(
        boto3.session.Session,
        aws_access_key_id=config.aws_access_key_id,
        aws_secret_access_key=config.aws_secret_access_key,
        aws_session_token=config.aws_session_token,
    )

    s3_client = providers.Resource(
        session.provided.client.call(),
        service_name='s3',
    )

    sqs_client = providers.Resource(
        providers.MethodCaller(session.provided.client),  # Alternative syntax
        service_name='sqs',
    )

    service1 = providers.Factory(
        Service,
        s3_client=s3_client,
        sqs_client=sqs_client,
    )

    service2 = providers.Factory(
        Service,
        s3_client=session.provided.client.call(service_name='s3'),    # Alternative inline syntax
        sqs_client=session.provided.client.call(service_name='sqs'),  # Alternative inline syntax
    )


def main():
    container = Boto3Container()
    container.init_resources()

    s3_client = container.s3_client()
    print(s3_client)

    sqs_client = container.sqs_client()
    print(sqs_client)

    service1 = container.service1()
    print(service1, service1.s3_client, service1.sqs_client)
    assert service1.s3_client is s3_client
    assert service1.sqs_client is sqs_client

    service2 = container.service1()
    print(service2, service2.s3_client, service2.sqs_client)
    assert service2.s3_client is s3_client
    assert service2.sqs_client is sqs_client


if __name__ == '__main__':
    main()
```

Dependency Injector can call provided object methods and fetch attributes. You can read more about this feature here: https://python-dependency-injector.ets-labs.org/providers/provided_instance.html

I also added an example to the docs with similar example.

PS: A note on ``service2``. Session returns singleton object for the same client ``session.client(service_name='s3') is session.client(service_name='s3')``. It's a reason why last two asserts work.

**Comment by ecs-jnguyen** [comment]
In your example I saw you used `Resource`. Is there a reason why you chose `Resource` over `Singleton` or `Factory`?

**Comment by rmk135** [comment]
There is no specific reason for using resources in this example.

``Resource`` is like ``Singleton`` with two differences:

1) ``Resource`` could have some shutdown code. This is useful when you'd like to close connections, free resources, etc.
2) You can init and shutdown all resources using container API: ``container.init_resources()`` and ``container.shutdown_resources()``.

Resource provider doc: https://python-dependency-injector.ets-labs.org/providers/resource.html

**Comment by ecs-jnguyen** [comment]
Thank you for clarifying. I was curious because the boto3 objects don't have an `__enter__` or `__exit__` implementation.

Sorry this question is a bit off topic from this issue. What is the difference between `Callable` and `Factory`? From my understanding `Callable` should be used for methods and `Factory` should be used for classes. However they seem to do the same thing because the constructors for classes are essentially "callable" as well. Is there anything under the hood that is different between them?

**Comment by rmk135** [comment]
> Sorry this question is a bit off topic from this issue. What is the difference between Callable and Factory? From my understanding Callable should be used for methods and Factory should be used for classes. However they seem to do the same thing because the constructors for classes are essentially "callable" as well. Is there anything under the hood that is different between them?

``Factory`` is a ``Callable`` with the difference that ``Factory`` can inject attributes:

```python
factory = providers.Factory(...)
factory.add_attributes(foo='bar')
```

> From my understanding Callable should be used for methods and Factory should be used for classes.

Your understanding is correct in historical meaning. It was the original idea. With time the restriction on ``Factory`` to accept only classes was removed because there could be factory functions, methods etc

**Comment by rmk135** [comment]
There's no documentation on `factory.add_attributes(foo='bar')`. I'll backlog a note to add it.

**Comment by ecs-jnguyen** [comment]
Thank you! This helped me a lot!
