### ISSUE TITLE
Config passed in as dict

### ISSUE THREAD

**Issue by wackazong** [ets-labs/python-dependency-injector#410]
When I use the config object in the container definitions I can use it like an object but when I pass it trough ```Provide``` I get a dict. How can I also get an object here?

**Comment by rmk135** [comment]
You can use different type of marker `Provider`. It will inject provider object. To get a value from the config you need to call the option: `config.option()`.

**Comment by wackazong** [comment]
Great, thanks!

**Comment by rmk135** [comment]
You're welcome!
