### ISSUE TITLE
Should provider benefit from a context manager like override to reset()?

### ISSUE THREAD

**Issue by Arrowana** [ets-labs/python-dependency-injector#413]
The following https://python-dependency-injector.ets-labs.org/providers/overriding.html?highlight=context%20manager is convenient in testing, especially when someone wants to test then teardown. Especially since bad cleanup could pollute other tests.

Could a similar context manager be made for the bare provider so it calls reset() on __exit__ so that the cached instance can be cleaned up automatically https://python-dependency-injector.ets-labs.org/search.html?q=reset

```from dependency_injector import providers

class Potato:
    ....

class Salad:
    ....
    
potato_provider = providers.Singleton(Potato)
salad_provider = providers.Factory(
    Salad,
    potato=potato_provider
)

...

def test_that_my_singleton_is_usable():
    with potato_provider as p:  # Currently not possible, goal is to get rid of the cached instance at the end of the test, in a non convoluted manner
        self.assertIsInstance(p, Potato)
   

def test_something_else_by_hiding_underlying_dependency(): # Currently possible because override
    with potato_provider.override(create_autospec(Potato)) as potato_mock:
        salad = salad_provider()
        ...
```

Use case:
Unit testing of DI composition

Not sure if `with potato_provider as p` is the best interface though

**Comment by rmk135** [comment]
Hi @Arrowana ,

That's a good idea. I will add it to the backlog.

**Comment by rmk135** [comment]
> Not sure if `with potato_provider as p` is the best interface though

I think that the best approach is to expand existing `.reset()` method to return context manager:

```python
    with container.potato.reset():
        ...
```

It will reset singleton before and after the context block.

How does it look to you?

**Comment by Arrowana** [comment]
I feel that makes it a bit obscure, calling reset only to get the underlying object.
Is there anything that prevents the provider itself from having `__enter__` and `__exit__` ?

**Comment by rmk135** [comment]
Got it. Thanks.

>Is there anything that prevents the provider itself from having __enter__ and __exit__ ?

It's not an option. There are two reasons:

1) `with potato_provider as p:` doesn't say anything about what happens in the context. 
2) only singleton provider provider has `.reset()` method. Other providers will not benefit from this context manager.

I think that context manager interface should be designed in the next manner:

```
with object.<what_happens_in_the_context>() as ...:
    ...
```

Method `.reset()` is a good decision because:

1) It describes what will happen in the context.
2) It will make a consistent interface with ``.override()``:

```python
with provider.override() as ...:
    ...
    
with singleton.reset() as ...:
    ...
 ```
 
 Also there are three variations of resetting singletons now. All three could have a consistent interface:
 
 ```python
 with singleton_provider.reset() as p:  # reset only singleton_provider
     ... 

 with singleton_provider.full_reset() as p:  # reset singleton_provider and all underlaying singleton providers
     ...  
     
with container.reset_singletons():  # reset all singleton providers in the container
     ...  
```

The only alternative I see is to find a better name for ``<what_happens_in_the_context>`` in the context of ``with object.<what_happens_in_the_context>() as ...:``.

**Comment by Arrowana** [comment]
1. with override(...). So we are overriding and on exit we are resetting the override.
2. with reset(). So we are resetting and on exit we are resetting, oh wait no. We call reset() we get the provider result and on exit we are calling reset().

Understood that we cannot add a context manager directly on the provider since there are different `<what_happens_in_the_context>`

**Comment by rmk135** [comment]
Right, so my idea is to reset on enter and on exit. Is that the same you’re thinking about?

**Comment by rmk135** [comment]
@Arrowana ,

I have released it in `with singleton.reset()` form in version `4.29.0`. Here is the docs: https://python-dependency-injector.ets-labs.org/providers/singleton.html#resetting-memorized-object

I hope that could work for you. I'm closing this issue. Feel free to comment if any feedback or suggestions.

**Comment by Arrowana** [comment]
Cool thank you, that will do. I see, the usage is quite different from what i thought, not returning anything from `__enter__` makes sense.

**Comment by rmk135** [comment]
__enter__ returns the provider:

with container.user_service.reset() as user_service:
    ...

You probably didn’t notice the example because I put it as an extra use case after the main example with the context manager.

Roman

**Comment by Arrowana** [comment]
I did not see that, anyway thank you, great package

**Comment by rmk135** [comment]
Ok, just in case you're still interested:

<img width="1680" alt="Screenshot 2021-03-06 at 08 00 13" src="https://user-images.githubusercontent.com/1742049/110207547-2f3ee080-7e52-11eb-901d-6aadc2852b26.png">

Thank you
