### ISSUE TITLE
How to deal with multi-level dependencies

### ISSUE THREAD

**Issue by wackazong** [ets-labs/python-dependency-injector#415]
I have the following levels of dependencies in my project

usecases
repositories
gateways
config

These are organized in an approach which looks like the `Application example (multiple containers)`.

If I do unit tests of the usecases I do not want to override all the repositories and gateways. I just want to override the repositories container. How could I e.g. override all gateways in the example?

**Comment by wackazong** [comment]
I think it boils down to how to mock a `providers.Container`

**Comment by rmk135** [comment]
Hi @wackazong ,

You can override `providers.Container` with a container that has mocked provider:

```python
application.gateways.override(Gateways(s3_client=mock.Mock()))
application.gatewas.s3_client()  # returns mock
```

In testing you could compound overriding with a context manager to clean up the overriding:

```python
    with application.gateways.override(Gateways(s3_client=mock.Mock())):
        application.gateways.s3_client()  # returns mock
        
    # returns normal instance
```

The only problem is that context manager for `Container.override()` is not implemented. I'll go ahead and make it work in a day or two.

**Comment by rmk135** [comment]
This now works properly in version `4.29.0`:

```python
    with application.gateways.override(Gateways(s3_client=mock.Mock())):
        application.gateways.s3_client()  # returns mock
```

**Comment by rmk135** [comment]
> If I do unit tests of the usecases I do not want to override all the repositories and gateways. I just want to override the repositories container. How could I e.g. override all gateways in the example?

One more option if you're looking to override all repositories: you can create test repositories container subclass and use it with the override method.

```python
class TestRepositories(Repositories):
    repository1 = providers.Factory(TestRepository1)
    repository2 = providers.Factory(TestRepository2)
    
# in tests
with application.repositories.override(TestRepositories()):
    application.repositories.repository1()  # returns TestRepository1
```

**Comment by rmk135** [comment]
I'm closing the issue. Feel free to comment if anything.

**Comment by wackazong** [comment]
Very cool. Thank you, will try that out in the next tests.
