### ISSUE TITLE
Strange FastAPI request body mapping error when injecting an "@injected" method

### ISSUE THREAD

**Issue by mxab** [ets-labs/python-dependency-injector#426]
Hi,
I'm having a strange behavior when I use the `python-dependency-injector` `@inject` + `Provide` marker on a method that is used as a factory method for FastAPI's `Depends()`

```python


@inject
def valid_user(
    settings: AuthSettings = Provide[Container.settings],
    credentials: HTTPBasicCredentials = Depends(security),
):

    if (
        settings.username == credentials.username
        and settings.password == credentials.password
    ):
        return True
    raise Exception("not allowed")


@app.post("/books/{id}", response_model=Book)
@inject
def update_book(
    id: str,
    payload: UpdateBook,
    repo: Repo = Depends(Provide[Container.repo]),
    valid_user=Depends(valid_user),
):
```
when I test this method, it fails with a 422 status code. It looks like request body is not send to FastAPI then.

```python
def test_update(test_app: FastAPI, client: TestClient):

    test_app.dependency_overrides[security] = lambda: HTTPBasicCredentials(
        username="foo", password="bar"
    )
    assert client.post("/books/1", json={"title": "bar"}).status_code == 200
```

If I remove either the 
```python
valid_user=Depends(valid_user),
```
in the router signature or in the `valid_user`
the `settings: AuthSettings = Provide[Container.settings],` the request body is used.

You can see the full running example here
https://github.com/mxab/pdi-fastapi-body-demo/blob/main/tests/test_pdi_fastapi_body_demo.py#L138

Any ideas?

**Comment by mxab** [comment]
I noticed that if wrap `settings: AuthSettings = Provide[Container.settings],` with a `Depends` it seems to work
e.g.:
`settings: AuthSettings = Depends(Provide[Container.settings]),` but is this a requirement in that case?

**Comment by rmk135** [comment]
> I noticed that if wrap settings: AuthSettings = Provide[Container.settings], with a Depends it seems to work
e.g.:
settings: AuthSettings = Depends(Provide[Container.settings]), but is this a requirement in that case?

Hi @mxab ,

Yes, you need to use `settings: AuthSettings = Depends(Provide[Container.settings])`. 

This is a FastAPI requirement, not a Dependency Injector one. FastAPI looks for all typed arguments that don't have `Depends` directive as a part of request. If you'd like you can do: `settings = Provide[Container.settings]`.

**Comment by mxab** [comment]
Hi,
this makes sense. Thanks a lot :)
