### ISSUE TITLE
Default value for missing environment variables in yaml and ini config files

### ISSUE THREAD

**Issue by hbmshemet** [ets-labs/python-dependency-injector#459]
How could I specify a default value for the missing environment variable in the configuration provider?

For example:
pseudo code

```
config = dependency_injector.providers.Configuration()
config.from_yaml("conf.yml")

print(config.some_key.size)  -> will print ${SOME_KEY_SIZE} if envvar is missing
```

conf file
```
some_key:
     size: ${SOME_KEY_SIZE}
```

or maybe we could leave such cases with empty/none values? for e.g.
```
config.some_key.size  -> will be None
```

**Comment by rmk135** [comment]
Hi @hbmshemet. Yeah, reasonable concern. I'll check what's going on in the code.

**Comment by hbmshemet** [comment]
it would be cool if we will have smth like this:

```
some_key:
     size: ${SOME_KEY_SIZE:my_awesome_default_value}
```

**Comment by rmk135** [comment]
@hbmshemet as a short-term solution you could use `os.environ.setdefault('SOME_KEY_SIZE', 'some_value')`. Here is full example:

```python
import os
from dependency_injector import providers

config = providers.Configuration()

if __name__ == '__main__':
    os.environ.setdefault('SOME_KEY_SIZE', 'some_value')
    config.from_yaml('conf.yml')

    print(config.some_key.size())
```

Current code uses [os.path.expandvars()](https://docs.python.org/3/library/os.path.html#os.path.expandvars) to replace env variables. If I recall correctly, that's what `yaml.UnsafeLoader` uses under the hood too. The main thing here is that it does substring replacement, eg `${HOME}/path/to/somewhere` is transformed to `/home/someuser/path/to/somewhere`. It will take time to implement a parser like you suggested.

I've got an idea to provide a list of defaults into `.from_yaml(..., default_env={})` call:
```python
from dependency_injector import providers

config = providers.Configuration()
default_env = {
    'SOME_KEY_SIZE': 'some_value',
}

if __name__ == '__main__':
    config.from_yaml('conf.yml', default_env=default_env)

    print(config.some_key.size())
```

How does it look to you?

**Comment by hbmshemet** [comment]
@rmk135 thanks, `os.environ.setdefault` works for me

It is totally better than "short-solution" and it will work. I'm not sure how much effort should be spent on yours and my idea, but I can see some benefits from default values in config files.

1. All configurations in one place, easy to change
2. Human readable(no need to search and check python files)
3. We could have different default values in different yml files

**Comment by rmk135** [comment]
Well, yeah, I agree. I think I can implement it.

**Comment by rmk135** [comment]
Finished a prototype today. Seems working fine.

Value `${DEF}/path/${DEF:default}/${UNDEF}/${UNDEF:default}` is resolved to `defined/path/defined/${UNDEF}/default` with `os.environ.setdefault('DEF', 'defined')`.

Will continue on productizing this feature. It still needs more tests, docs and also would be nice to port it to ini files parsing.

**Comment by rmk135** [comment]
Hey @hbmshemet 

I've added ``${ENV:default}`` feature in release ``4.33.0``. See [changelog](https://python-dependency-injector.ets-labs.org/main/changelog.html). Thanks for bringing up the problem and providing feedback. 

Closing this issue. Feel free to re-open if needed.

Respectfully,
Roman
