### ISSUE TITLE
SSL Certificate on https://python-dependency-injector.ets-labs.org/ has expired

### ISSUE THREAD

**Issue by brianpkennedy** [ets-labs/python-dependency-injector#469]
Hi there,

Just wanted to let you know that https://python-dependency-injector.ets-labs.org/ was being blocked on my browser because your SSL cert has expired. My browser(s) give a warning and block traffic to the site without an express accepting of the stale cert.

**Comment by rmk135** [comment]
Oh, that’s bad. I need to fix it ASAP. Thanks @brianpkennedy

**Comment by rmk135** [comment]
Fixed. @brianpkennedy thanks again.

**Comment by brianpkennedy** [comment]
np. happy to help.
