### ISSUE TITLE
sonarqube "Module 'dependency_injector.containers' has no 'DeclarativeContainer' member"

### ISSUE THREAD

**Issue by mxab** [ets-labs/python-dependency-injector#472]
Hi,
I'm getting a Sonarqube warning in the container part at:
`class Container(containers.DeclarativeContainer):`

```
Module 'dependency_injector.containers' has no 'DeclarativeContainer' member, but source is unavailable. Consider adding this module to extension-pkg-allow-list if you want to perform analysis based on run-time introspection of living objects.
```

Would you recommend appling the hint or do you know if there is a better way

**Comment by rmk135** [comment]
Hi @mxab ,

Module `dependency_injector.containers` is a C extension. I read about this option over here: http://pylint.pycqa.org/en/latest/technical_reference/c_extensions.html.

Seems like using `extension-pkg-allow-list` is a reasonable way to tell pylint about C extensions. I would try that.

**Comment by mxab** [comment]
thanks
