### ISSUE TITLE
six library update to 1.16.0

### ISSUE THREAD

**Issue by ilsurih** [ets-labs/python-dependency-injector#478]
Any plans on updating six to 1.16.0? Currently version is limited to <=1.15.0

**Comment by rmk135** [comment]
Should not be a big deal. Will publish a release later today. Thanks for bringing this up!

**Comment by rmk135** [comment]
Released a version `4.35.0` with six <= 1.16.0. 

_A note for future myself or other contributor: I think it makes sense to check with six owners if they committed to follow semantic versioning. If so, we could put an upper boundary to <2.0 and prevent such problem in future._
