### ISSUE TITLE
Sentry does not seem to be logging when logger is used inside DI framework

### ISSUE THREAD

**Issue by blairg23** [ets-labs/python-dependency-injector#482]
I implemented a single `providers.Singleton` for the `logging.Logger` module (see example below). None of my exceptions have been bubbling up to `Sentry`. However, if I use the `logging.Logger` (shown as `Logger2` in the example), the exception bubbles up. Is there something further I need to do to use `logging.Logger` inside the DI framework?

---

`hl_provider`:

```
from dependency_injector import providers
from dependency_injector.containers import DeclarativeContainer
from lib.dependency_injector.custom_configuration_option import HLConfiguration
from logging import Logger

class HLProvider(DeclarativeContainer):
    config = HLConfiguration()
    logger = providers.Singleton(Logger, name="testing inside DI framework")
```

---

`provider`: 

```
from dependency_injector import providers

from functions.registrations.get.service import Service
from lib.dependency_injector.hl_provider import HLProvider

class Provider(HLProvider):
    logger = HLProvider.logger

    service = providers.Factory(
        Service,
        logger=logger,
    )
```

---

`service`:

```
from logging import Logger as Logger2
LOGGER = Logger2("testing DEV-1557")

class Service:
    def __init__(
            self,
            logger,
    ) -> None:
        self.logger = logger

    @handle_errors
    def handler(self, event):
        self.logger.debug(event)
        self.logger.exception("Testing DEV-1557 (inside DI framework, does not work)")
        LOGGER.exception("Testing DEV-1557, this one works")
```

**Comment by rmk135** [comment]
Hey @blairg23 . 

> Is there something further I need to do to use logging.Logger inside the DI framework?
- No, there are no requirements from the DI framework to make logger work. DI framework just instantiate objects and provide dependencies.

I see a potential problem in how you instantiate the logger. Try this:


```python
from logging import getLogger  # getLogger() factory method instead Logger class

class HLProvider(DeclarativeContainer):
    ...
    logger = providers.Singleton(getLogger, name="testing inside DI framework")
```

**Comment by blairg23** [comment]
This worked, thanks! Also for future reference, to use a custom logger named `CustomLoggerClass`, you just need to implement a method like this:

```
def get_logger(name):
    logging.setLoggerClass(CustomLoggerClass)
    return logging.getLogger(name=name)
```

and then similarly do this: `logger = providers.Singleton(get_logger, name="whatever')`

**Comment by rmk135** [comment]
Nice! Thanks @blairg23 . ``logging.getLogger()`` registers created logger in the global logging manager. I believe this global manager is the integration point for sentry sdk. And thanks for sharing custom logger class example.
