### ISSUE TITLE
FastAPI route Request injection + injector decorator 

### ISSUE THREAD

**Issue by stefanitsky** [ets-labs/python-dependency-injector#483]
Hi!

Problem: inject decorator doesn't work with fastapi.Request

Sample code:
```python
from __future__ import annotations

import uvicorn
from dependency_injector.wiring import Provide, inject, register_loader_containers
from dependency_injector import containers, providers
from fastapi import Depends, FastAPI, Request

app = FastAPI()


class Database:
    pass


class Container(containers.DeclarativeContainer):
    config = providers.Configuration()
    db = providers.Singleton(Database)


@app.get('/ok')
@inject
def test_ok(name: str = None, db: 'Database' = Depends(Provide[Container.db])) -> str:
    return 'ok'


# On startup error
# @app.get('/ffs')
# @inject
# def test_ffs(request: Request, db: 'Database' = Depends(Provide[Container.db])) -> str:
#     print(request.url)
#     return 'ffs'


# P.S.: also, it's the same error if Database class typing has no double quotes

if __name__ == '__main__':
    container = Container()
    register_loader_containers(container)
    container.config.from_dict({'token': 'abc123'})
    uvicorn.run(app)

```

Traceback:
```python
  Traceback (most recent call last):
  File "/Users/stefanitsky/projects/stefan-discord-bot/tetst.py", line 22, in <module>
    def test_ffs(request: Request, db: 'Database' = Depends(Provide[Container.db])) -> str:
  File "/Users/stefanitsky/Library/Caches/pypoetry/virtualenvs/stefan-discord-bot-NW7ReM4V-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 575, in decorator
    self.add_api_route(
  File "/Users/stefanitsky/Library/Caches/pypoetry/virtualenvs/stefan-discord-bot-NW7ReM4V-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 518, in add_api_route
    route = route_class(
  File "/Users/stefanitsky/Library/Caches/pypoetry/virtualenvs/stefan-discord-bot-NW7ReM4V-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 400, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/Users/stefanitsky/Library/Caches/pypoetry/virtualenvs/stefan-discord-bot-NW7ReM4V-py3.8/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 290, in get_dependant
    endpoint_signature = get_typed_signature(call)
  File "/Users/stefanitsky/Library/Caches/pypoetry/virtualenvs/stefan-discord-bot-NW7ReM4V-py3.8/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 248, in get_typed_signature
    typed_params = [
  File "/Users/stefanitsky/Library/Caches/pypoetry/virtualenvs/stefan-discord-bot-NW7ReM4V-py3.8/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 253, in <listcomp>
    annotation=get_typed_annotation(param, globalns),
  File "/Users/stefanitsky/Library/Caches/pypoetry/virtualenvs/stefan-discord-bot-NW7ReM4V-py3.8/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 265, in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
  File "pydantic/typing.py", line 62, in pydantic.typing.evaluate_forwardref
    'MutableSet',
  File "/Users/stefanitsky/.pyenv/versions/3.8.0/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Request' is not defined
```

Any ideas?

**Comment by rmk135** [comment]
Hey @stefanitsky. Thanks for demonstrating the problem and providing the sample. I’ll take a look and get back to you

**Comment by rmk135** [comment]
Hey @stefanitsky ,

So few things:

1) Remove ``from __future__ import annotations``
2) Use regular class references instead of strings for type annotations: ``db: Database`` instead of `db: 'Database'```.
3) Optionally, add ``container.wire(modules=[sys.modules[__name__]])`` to the startup code to wire already loaded modules.

Here is complete example:

```python
import sys

import uvicorn
from dependency_injector.wiring import Provide, inject, register_loader_containers
from dependency_injector import containers, providers
from fastapi import Depends, FastAPI, Request

app = FastAPI()


class Database:
    pass


class Container(containers.DeclarativeContainer):
    config = providers.Configuration()
    db = providers.Singleton(Database)


@app.get('/ok')
@inject
def test_ok(name: str = None, db: Database = Depends(Provide[Container.db])) -> str:
    return f'ok {db}'


@app.get('/ffs')
@inject
def test_ffs(request: Request, db: Database = Depends(Provide[Container.db])) -> str:
    print(request.url)
    return f'ffs {request.url} {db}'


if __name__ == '__main__':
    container = Container()
    register_loader_containers(container)
    container.wire(modules=[sys.modules[__name__]])
    container.config.from_dict({'token': 'abc123'})
    uvicorn.run(app)
```

Hope that helps!

**Comment by stefanitsky** [comment]
> Hey @stefanitsky ,
> 
> So few things:
> 
> 1. Remove `from __future__ import annotations`
> 2. Use regular class references instead of strings for type annotations: `db: Database` instead of `db: 'Database'```.
> 3. Optionally, add `container.wire(modules=[sys.modules[__name__]])` to the startup code to wire already loaded modules.
> 
> Here is complete example:
> 
> ```python
> import sys
> 
> import uvicorn
> from dependency_injector.wiring import Provide, inject, register_loader_containers
> from dependency_injector import containers, providers
> from fastapi import Depends, FastAPI, Request
> 
> app = FastAPI()
> 
> 
> class Database:
>     pass
> 
> 
> class Container(containers.DeclarativeContainer):
>     config = providers.Configuration()
>     db = providers.Singleton(Database)
> 
> 
> @app.get('/ok')
> @inject
> def test_ok(name: str = None, db: Database = Depends(Provide[Container.db])) -> str:
>     return f'ok {db}'
> 
> 
> @app.get('/ffs')
> @inject
> def test_ffs(request: Request, db: Database = Depends(Provide[Container.db])) -> str:
>     print(request.url)
>     return f'ffs {request.url} {db}'
> 
> 
> if __name__ == '__main__':
>     container = Container()
>     register_loader_containers(container)
>     container.wire(modules=[sys.modules[__name__]])
>     container.config.from_dict({'token': 'abc123'})
>     uvicorn.run(app)
> ```

Haha, thanks! `from __future__ import annotations` breaks everything...

**Comment by rmk135** [comment]
Yeah, annotations thing isn't perfect at the moment. If I recall correctly, Python 3.10 will bring a significant change where the from future from ``from __future__ import annotations`` will actually become current :) Anyway, thanks for asking for help. Let me know if you anything else. Closing the issue for now, feel free to comment if anything
