### ISSUE TITLE
Setter method calls are missing

### ISSUE THREAD

**Issue by aminclip** [ets-labs/python-dependency-injector#498]
Hi Contributors :)

I'm trying to set an optional dependency ( a logger ) by using a setter method injection, but I haven't found any way to do that using this project.

A sample implementation of it can be found here https://symfony.com/doc/current/service_container/calls.html for PHP language.

Thanks.

**Comment by rmk135** [comment]
Hi @aminclip ,

There is no setter method injection out of the box, but you can use attribute injection. Here is an example from the [documentation](https://python-dependency-injector.ets-labs.org/providers/factory.html):

```python
from dependency_injector import containers, providers


class Client:
    ...


class Service:
    def __init__(self) -> None:
        self.client = None


class Container(containers.DeclarativeContainer):

    client = providers.Factory(Client)

    service = providers.Factory(Service)
    service.add_attributes(client=client)


if __name__ == '__main__':
    container = Container()

    service = container.service()

    assert isinstance(service.client, Client)
```

Setter method are not that popular in Python in favor of regular property injections. If you need to modify or validate the injected value, you can use ``@property`` decorator.

```python
class Service:
    def __init__(self) -> None:
        self._client = None
        
    @property
    def client(self) -> object:
        return self._client

    @client.setter
    def client(self, value: object) -> None:
        # validate(value)
        self._client = value
```
