### ISSUE TITLE
Fix a typo in Factory provider docs "service.add_attributes(clent=client)"

### ISSUE THREAD

**Issue by rmk135** [ets-labs/python-dependency-injector#499]
I found a typo in ``Factory`` provider docs: https://python-dependency-injector.ets-labs.org/providers/factory.html.
Need to update ``service.add_attributes(clent=client) -> service.add_attributes(client=client)``.

**Comment by rmk135** [comment]
Hey @rajanjha786, many thanks for the help! I have updated a changelog: https://github.com/ets-labs/python-dependency-injector/commit/cc4235257c03774b472020a0d954e34d6333a2b5.

The fix is in the develop branch now and will be published with the next release.

**Comment by rajanjha786** [comment]
Thanks, @rmk135 
This was my  contribution to OS Journey :)
