### ISSUE TITLE
Provide auto-completion for class attributes

### ISSUE THREAD

**Issue by chbndrhnns** [ets-labs/python-dependency-injector#505]
For this simple example, I cannot get PyCharm to provide auto-completion beyond the first level. Is it possible somehow to make auto-completion available? 

The class constructs seem quite simple (on the outside) so I am not sure why the completion is missing here.

My expectation is to see "config" being offered.

![Screenshot 2021-09-11 at 13 06 45](https://user-images.githubusercontent.com/7534547/132945870-332d325d-ee2d-4d44-85c9-19daed18f369.png)

<details>
<summary>Click to toggle</summary>

```py
from dependency_injector import containers, providers


class Core1(containers.DeclarativeContainer):
    config = providers.Configuration(

    )


class Application(containers.DeclarativeContainer):
    core_1 = providers.Container(Core1)


def test():
    c = Application()
    assert (c.core_1.config, providers.Configuration)
    c.core_1.con
```

</details

**Comment by rmk135** [comment]
Hey @chbndrhnns ,

There are two ways how you can get typing work in this case:

1) Call container provider to get actual instance of the subcontainer:
<img width="1135" alt="Screen Shot 2021-09-12 at 8 25 04 PM" src="https://user-images.githubusercontent.com/1742049/133008056-ac316814-744d-45c4-b071-fd911f7d3a45.png">

2) Specify the type of the container in the root container:
<img width="1101" alt="Screen Shot 2021-09-12 at 8 27 16 PM" src="https://user-images.githubusercontent.com/1742049/133008082-50ee20ca-1949-4872-adba-424876b9e5a3.png">

I usually use option #2.

**Comment by chbndrhnns** [comment]
Of course, option 2 is nice. I cannot remember why I did not think of that possibility.
