### ISSUE TITLE
.provided() returns different results

### ISSUE THREAD

**Issue by wackazong** [ets-labs/python-dependency-injector#545]
I have a container structure with providers inside. For testing I acquire some of these providers via calling .provided()
```
await application.domain.client.usecase1.provided()
````
gives me the `usecase1` which I can then execute. This call returns a future and has to be awaited.

Strangely enough, when I call `override` on the container before, the call to provided does not need to be awaited anymore:
```
application.domain.client.usecase2.override(mock)
application.domain.client.usecase1.provided()
```
Now, `.provided()` delivers the object directly. Why is that and can it be avoided? This leads to inconsistencies in my tests.

**Comment by rmk135** [comment]
Hi @wackazong ,

See https://python-dependency-injector.ets-labs.org/providers/async.html#async-mode-mechanics-and-api

In your example, the async mode state by default is undefined for ``usecase1``. When you test, you override with the sync dependency and it switches the provider in sync mode. Behavior without overriding is reverse. This is an issue and I don't have an elegant solution for now.

Non-elegant solution is to enable async mode explicitly during overriding:

```python
application.domain.client.usecase2.override(mock)
application.domain.client.usecase2.enable_async_mode()
```

If you have any suggestions on the interface, please don't hesitate to let me know.

**Comment by wackazong** [comment]
Ok, I get it. Thanks. I was playing around with `.enable_async_mode()` but did not get it to work. Will try your suggestion tomorrow 🙏🏼
