### ISSUE TITLE
Builtin method 'open' not working on callable.

### ISSUE THREAD

**Issue by minkichoe** [ets-labs/python-dependency-injector#546]
Hi, I'm using this library very well, thank you.

I tried callable injection, but not working on:
```python3
class Container(containers.DeclarativeContainer):
    buffered_byte_reader_factory=providers.Callable(
        open,
        mode="rb",
    )
```

Exception: `TypeError: open() missing required argument 'file' (pos 1)`

**Comment by minkichoe** [comment]
And I want to use like `buffered_byte_reader_factory("/path/to/file").readlines()`.

**Comment by rmk135** [comment]
Hi @minkichoe ,

This is what worked for me:

```python
from dependency_injector import containers, providers


class Container(containers.DeclarativeContainer):

    buffered_byte_reader_factory = providers.Callable(
        open,
        mode="rb",
    )


if __name__ == "__main__":
    container = Container()
    lines = container.buffered_byte_reader_factory("./file.txt").readlines()
    print(lines)
```

The use case you demonstrate looks fine. Please, let me know if still need help

**Comment by minkichoe** [comment]
Thanks for your answer.
I have a mistake.

**Comment by rmk135** [comment]
No problem, thanks for asking
