### ISSUE TITLE
Python2 not support 

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [ets-labs/python-dependency-injector#562]
![image](https://user-images.githubusercontent.com/40897360/154210381-adb6fab1-a952-4b98-bf41-2a0e50c58800.png)

**Comment by chbndrhnns** [comment]
I assume that's not a bug but rather as expected.

**Comment by rmk135** [comment]
Hi @chbndrhnns ,

Wiring doesn't work with Python 2. I cannot recall what was the reason why Python 2 is not the case for wiring, but I think there were some technical impediments during the implementation.

**Comment by ZipFile** [comment]
Python 2 EOL-ed for about 5 years now, I do not think we need to support it anymore.
