### ISSUE TITLE
AttributeError: 'Provide' object has no attribute ...

### ISSUE THREAD

**Issue by vlio20** [ets-labs/python-dependency-injector#578]
I have the following scaffolding: 
![image description](https://i.ibb.co/Y3k3b7X/Screen-Shot-2022-04-06-at-21-23-53.jpg)

I have the following code in my di.py:
```python
from dependency_injector import containers, providers

from user.user_service import UserService


class Container(containers.DeclarativeContainer):

    user_service = providers.Factory(UserService)

```

And the following code in my app.py:
```python
from flask import Flask

from di.di import Container
from user.user_controller import user


def create_app():
    container = Container()
    app = Flask(__name__)
    app.container = container
    app.register_blueprint(user)

    return app
```

Here is my user_controller.py:
```python
from dependency_injector.wiring import inject, Provide
from flask import Blueprint

from di.di import Container
from user.user_service import UserService

user = Blueprint('user', __name__, url_prefix='/users')


@user.route('/', methods=['GET'])
@inject
def get_user(user_service: UserService = Provide[Container.user_service]) -> str:
    return user_service.hello() // getting an error for that line
```

The app is booted fine but then when invoking http://localhost:5000/users I am getting the following error:
```
AttributeError: 'Provide' object has no attribute 'hello'
```
It seems that the injector injects some Provide object instead of the UserService class.

Not sure what is wrong with my setup. Will appreciate some help.

**Comment by vlio20** [comment]
After 3 days of debugging the thing that solved my issue was that missed line:
```
wiring_config = containers.WiringConfiguration(modules=["user.user_controller"])
```

it was missing it the container file

**Comment by michaelkargl** [comment]
Thanks, that was just what was missing on my side as well.
Do you know why exactly this is necessary? I can't wrap my head around this wiring business.

My theory is that the `WiringConfiguration` somehow shares the Container instance registered in `app.controller` with the provided modules.
