### ISSUE TITLE
Dependency Injector with Celery Tasks

### ISSUE THREAD

**Issue by rbrazinskas** [ets-labs/python-dependency-injector#592]
Can dependency injector be used with Celery tasks? I cannot make the injector to work, it throws an exception

AttributeError: 'Provide' object has no attribute 'Foo'

**Comment by chbndrhnns** [comment]
Have you found a solution? Which one?

**Comment by theobouwman** [comment]
How can I do this?

**Comment by rbrazinskas** [comment]
Apparently you can't, because Celery workers are started and run on different processes than the dependency injector
