### ISSUE TITLE
[QUESTION] Should dependencies be injected at the endpoint level or into the method that it is explicitly used?

### ISSUE THREAD

**Issue by TomSB1423** [ets-labs/python-dependency-injector#629]
I am running a FastAPI client with dependencies needed to be used throughout my services that my endpoints invoke. Should these dependencies be passed through multiple methods until they are used, or injected into the method that uses the dependency?

If the latter is the case, how could I keep track of the wiring configuration, as I would need to add it for every single file that uses the dependency? Any advice would be appreciated. Thanks

**Comment by TomSB1423** [comment]
@chbndrhnns Sorry, I didn't specify - I'm using singleton classes, which aren't global?

**Comment by chbndrhnns** [comment]
@TomSB1423 Isn't the purpose of a singleton to be global?
