### ISSUE TITLE
unable to install on system with cp949 default locale

### ISSUE THREAD

**Issue by ebr** [ets-labs/python-dependency-injector#643]
When installing `dependency-injector` with `pip` on a Windows system where the default locale is `cp949`  ([EUC-KR](https://en.wikipedia.org/wiki/Unified_Hangul_Code)), the setup crashes as follows:

```
File "C:\Users\kang\AppData\Local\Temp\pip-install-s5l83_ea\dependency-injector_1f5595dca62448e69eff82ed9399ee9d\setup.py", line 15, in
description = readme_file.read()
^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 8665: illegal multibyte sequence
```

unclear whether this happens with any other locales.

**Comment by ebr** [comment]
hoping to fix https://github.com/invoke-ai/InvokeAI/issues/1944

**Comment by ebr** [comment]
may fix https://github.com/invoke-ai/InvokeAI/issues/1944

**Comment by rmk135** [comment]
PR merged. Thanks for the contribution!
