### ISSUE TITLE
Future of this repo?

### ISSUE THREAD

**Issue by stevenengland** [ets-labs/python-dependency-injector#688]
Hi @rmk135 Roman,

thank you for this awesome library :) Finally a serious approach towards DI in Python! I really would like to depend on this library. But therefore I would like to ask you, what the future of this repo is? Since I see no further milestones and the last commit to this repo was three month ago and a few new issues arose I am not sure if this is a normal situation or if you are slowly running out of resources?

Again: Thanks for this awesome library!!!

**Comment by rmk135** [comment]
Hi Steven @stevenengland,

I don't plan to add any significant new features in the following months, but plan to maintain the repo and library so it has up-to-date dependencies, support recent versions of Python and has critical bug-fixes implemented.

Thanks for the warm words :)

**Comment by rbuckland** [comment]
There are a number of PRs sitting in the queue. Are these going to be looked at / investigated ?

**Comment by cojua8** [comment]
Hi @rmk135 , thank you for your awesome work here.

In the other hand, have you thought of opening the repo for maintainers? There are a bunch of nice pull requests that could make the experience even better.

I'd be happy to help

**Comment by anton-petrov** [comment]
Hi @rmk135, thank you for your cool project!
I agree with the previous ones, the library requires support, for example, Python 3.12, etc.

**Comment by anton-petrov** [comment]
@rmk135 Please look at my PR #752, is everything correct? I tested locally, everything seems ok.

**Comment by MahmudulHassan5809** [comment]
@rmk135 thanks for this awesome project . 
is this project still alive . there is many pr ready merge  which will  solve many issues. May be you are very busy but if possible can you please look into this PRs please .
Thanks .

**Comment by rmk135** [comment]
All,

I know that there are quite a few PRs and issues to be answered. I have very limited availability at this time. I still love the project and believe it should be supported much better than things are going now. Having that said, the best thing I can do at the moment in my opinion is to find a maintainer and help them ramp up to support the project well.

In the meantime, I'd like to apologize to everyone for not having the support of most recent versions of Python to be released just yet. That's going to be fixed soon.

Respectfully,
Roman

**Comment by anton-petrov** [comment]
@rmk135 Let me know if you need my help with the project, especially since I actively use it in production. I'm also one of two active core maintainers of [pyenv](https://github.com/pyenv/pyenv)

**Comment by frederikdyrmose** [comment]
Hi Roman (@rmk135),

Can you please let me know if I can assist ( @anton-petrov want to as well ), as this is used in a wide range of production applications currently and is a really great project? :)

**Comment by rmk135** [comment]
Hi all!

Here's the roadmap for 2024: https://github.com/ets-labs/python-dependency-injector/issues/812

I'll go ahead and close this issue for now.
