### ISSUE TITLE
Add docs about Configuration provider

### ISSUE THREAD

**Issue by rmk135** [ets-labs/python-dependency-injector#71]

**Comment by thejohnfreeman** [comment]
Is, uh, this going to happen?

**Comment by andres-fr** [comment]
Hi! Amazing software, thanks a lot. So configs are nested dicts with `str` as keys? Or YAML-alike objects? Does the constraint apply that the dicts must be objectified (i.e. no keys starting with number etc...)?

**Comment by rmk135** [comment]
@thejohnfreeman @andres-fr 

Gentlemen,

The day has come.

http://python-dependency-injector.ets-labs.org/providers/configuration.html

Available since version `3.18`.
