### ISSUE TITLE
Is this library still alive?

### ISSUE THREAD

**Issue by alexted** [ets-labs/python-dependency-injector#742]
It's been a long time since the last commit. The author and maintainers of the project (if there are any) do not react in any way to the issues, do not contact and, in general, do not show any activity. It looks like the project is abandoned.
Is there any information - will the library be developed and maintained further?

**Comment by danieljoris** [comment]
I believe, unfortunately, is dead :(

I haven't found a good alternative yet.

**Comment by jakub-borusewicz** [comment]
@danieljoris maybe try this:
https://proofit404.github.io/dependencies/

**Comment by rmk135** [comment]
Hey guys! I indeed don't have much time to contribute to new features. One thing that is really needed is adding Python 3.12 support and I'm working on this right now.

**Comment by jakub-borusewicz** [comment]
For anybody still looking for alternative, here is library that is designed as a replacement for dependency-injector
https://that-depends.readthedocs.io/

**Comment by rmk135** [comment]
The release with Python 3.12 support is on PyPI: https://pypi.org/project/dependency-injector/4.42.0b1/

```
pip install dependency-injector==4.42.0b1
```

Please report any issues you notice by opening an issue here: https://github.com/ets-labs/python-dependency-injector/issues

I'll publish the plan for future steps a bit later. There is a lot of work to do.

**Comment by rmk135** [comment]
Hi all!

Here's the roadmap for 2024: https://github.com/ets-labs/python-dependency-injector/issues/812

I'll go ahead and close this issue for now.

**Comment by alexted** [comment]
@rmk135 Are there similar roadmaps for 2025 and 2026?
