### ISSUE TITLE
project status update needed

### ISSUE THREAD

**Issue by toinbis** [ets-labs/python-dependency-injector#763]
Hey,

love and use this framework a lot! But am worried about the future of it.

With last commit being year ago, I wonder what's the commitment from the maintainers to maintain this project? I'm using https://github.com/ets-labs/python-dependency-injector/compare/master...pachama:python-dependency-injector:master to install it, as it has some major type-related changes.

It seems more attention is needed to develop, maintain, bugfix this rather widely used project.

@rmk135  - am tagging you on this one, please share a sentence or few with a community :) Thanks a lot!

**Comment by danieljoris** [comment]
@toinbis Unfortunately, I think the project was abandoned. Since December 2022 no major updates.

**Comment by rmk135** [comment]
Hi all!

Here's the roadmap for 2024: https://github.com/ets-labs/python-dependency-injector/issues/812

I'll go ahead and close this issue for now.
