### ISSUE TITLE
Error when installing by poetry in python 3.12

### ISSUE THREAD

**Issue by DaggerJackfast** [ets-labs/python-dependency-injector#771]
I have the error when install the package with poetry in python 3.12.1
`Note: This error originates from the build backend, and is likely not a problem with poetry but with dependency-injector (4.41.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "dependency-injector (==4.41.0)"'.`

**Comment by changja88** [comment]
I have same problem.
Python 3.12 is super cool. I hope I can use dependency-injector with python 3.12 as soon as possible.
Thanks!

**Comment by yaziamoe** [comment]
I like to have it enabled for Python 3.12 too. My project is stuck using this amazing framework to python 3.11. 

Thanks in advance!

**Comment by sh-at-cs** [comment]
The PR for adding Python 3.12 support is https://github.com/ets-labs/python-dependency-injector/pull/765

**Comment by rmk135** [comment]
The release with Python 3.12 support is on PyPI: https://pypi.org/project/dependency-injector/4.42.0b1/

```
pip install dependency-injector==4.42.0b1
```

Please report any issues you notice by opening an issue here: https://github.com/ets-labs/python-dependency-injector/issues

I'll publish the plan for future steps a bit later. There is a lot of work to do.

**Comment by ZipFile** [comment]
Latest release is now fully [PEP-517](https://peps.python.org/pep-0517/)-compliant (see #829) and should be installable by modern versions of pip or alternative package mangers like Poetry. I've verified that it installs fine on Python 3.12 using Poetry. Closing.
