### ISSUE TITLE
a simplest fastapi app, di does not work

### ISSUE THREAD

**Issue by antonio-antuan** [ets-labs/python-dependency-injector#821]
I've been playing with the lib for a while. Cannot make it work :(

Python 3.12.3
dependency-injector = "^4.42.0"
fastapi = "^0.110.1"
uvicorn = "^0.29.0"

```
import uvicorn
from dependency_injector import containers, providers
from dependency_injector.wiring import Provide, inject
from fastapi import FastAPI, Depends


class X:
    def x(self) -> int:
        return 1


class Container(containers.DeclarativeContainer):

    wiring_config = containers.WiringConfiguration(modules=[__name__])

    x = providers.Factory(X)


app = FastAPI()
app.container = Container()


@app.get("/")
@inject
def root(foo: X = Depends(Provide[Container.x])):
    print(foo.x())


if __name__ == "__main__":
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=5000,
    )

```

the error that I get:
```
  File "src/dependency_injector/_cwiring.pyx", line 28, in dependency_injector._cwiring._get_sync_patched._patched
  File "/home/sergey/.config/JetBrains/PyCharm2024.2/scratches/scratch_309.py", line 30, in root
    print(foo.x())
          ^^^^^
AttributeError: 'Provide' object has no attribute 'x'
```

what am I doing wrong?

**Comment by AndBondStyle** [comment]
@antonio-antuan you're using auto-wiring, as I understand, it happens at the moment you create a `Container` instance. But you do this before your view definition, so it doesn't get injected. You can move this line:
```
app.container = Container()
```
below the `def root(...)` function and it will work. Alternatively, you can use fastapi's [lifespan hook](https://fastapi.tiangolo.com/advanced/events/) and create your container inside it (like in [this example](https://gist.github.com/AndBondStyle/3e0952291a55720f8c6bf57e5e51cc44) &mdash; note that you don't need to copy it entirely, it's just what I have at hand). This way all your views will get a chance to first get defined, and then injected when the app starts.
