### ISSUE TITLE
providers.Configurator is casting string as date

### ISSUE THREAD

**Issue by afrancoc2000** [ets-labs/python-dependency-injector#843]
I have a configuration variable for api version in my config.yaml the api version is in this format "AAAA-MM-dd" I need it as a string as it's the api version I'm using with OpenAI the thing is that it's being initialized automatically as a date, so I have to convert it back to a string in order to use it.

This is my config.yaml:

```yaml
openai:
  api_version: ${AZURE_OPENAI_API_VERSION:2023-07-01}
  ...
```

```py
class Container(containers.DeclarativeContainer):
    config = providers.Configuration(yaml_files=["./config.yaml"])

    openai_api_version = providers.Callable(
        lambda api_version: api_version if isinstance(api_version, str) else api_version.strftime("%Y-%m-%d"),
        config.openai.api_version
    )

    langchain_splitter_factory = providers.Factory(
        LangchainSemanticSplitter,
        api_version=openai_api_version,
    )    
```

The version can be either a date "2024-07-01" or a preview version like "2024-07-01-preview" and it only interpretes it as a string in the second case, unless I use the callable.

Typecasting it as a string (as_str) doesn't work either, it shouldn't automatically assume it's a date or there should be a way for me to specify the type I want it to be.

**Comment by ZipFile** [comment]
This is a default PyYAML behavior and has nothing to do with DI. Your issue is in yaml file itself, wrap `api_version` into double quotes like this:
```yaml
openai:
  api_version: "${AZURE_OPENAI_API_VERSION:-2023-07-01}"
  ...
```

**Comment by afrancoc2000** [comment]
I'll do the change thanks!
