### ISSUE TITLE
Container must be in the same package as the module for DI to work

### ISSUE THREAD

**Issue by Deviad** [ets-labs/python-dependency-injector#844]
Hi all, 
I am using version 4.44.0 and python 3.11.10.

Here is my project structure
<img width="328" alt="image" src="https://github.com/user-attachments/assets/448146f5-0e2c-435d-a4e0-a080fb45a533" />

For Dependency injection to work I either must have the Container class in the same package as the modules or I must use 
vector_document_repo: VectorDocumentRepository = Provide[DocumentContainer.vector_document_repo].provider()
So, I have to manually call provider()

Otherwise provider() won't ve called automatically under the hood. 

Is this a known issue?

```python
from dependency_injector import containers, providers
import src.rag.chroma_client as chroma_client
from src.rag.document import vector_document_repository


class DocumentContainer(containers.DeclarativeContainer):
   # TODO: Verify why this class must be located in the same package as the modules
    wiring_config = containers.WiringConfiguration(
        modules=["src.rag.document.document_controller", "src.rag.document.document_utils"]
    )

    config = providers.Configuration()

    chroma_client = providers.Resource(
        chroma_client.create_chromadb_client,
    )

    vector_document_repo = providers.Singleton(
        vector_document_repository.VectorDocumentRepository,
        chroma_client=chroma_client,
    )

    @classmethod
    def init_app(cls):
        container = cls()
        # container.wire(modules=["src.rag.document.document_controller", "src.rag.document.document_utils"])
        return container

```

**Comment by ZipFile** [comment]
Please, elaborate more on how it does not work for you. Is there any errors? How did you figured out container class should be in the same module? Are you adding [@inject](https://python-dependency-injector.ets-labs.org/wiring.html#decorator-inject) as very first decorator? Where are you instantiating your container?

Also, few more notes:

1. You're not supposed to use `Provide` marker like this: `def foo(something = Provide[Container.something].provider()): ...`. Here you're calling provider before container is properly initialized and assigning its result as a default argument value. Wiring feature looks for `Provide` markers to be able to do its job, which won't be the case in your example.
2. There is something wrong with your project setup. Looks like you're using [src layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/), but `src` is not on your `sys.path`. Are you using [editable installs](https://pip.pypa.io/en/stable/topics/local-project-installs/#editable-installs)? Check documentation of your packaging tool for more details how to configure your project ([setuptools](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout), [poetry](https://python-poetry.org/docs/pyproject/#packages), etc...)

**Comment by Deviad** [comment]
There is no explicit error, besides the fact that it could not find attribute "x" where x is the name of the method which I wanted to call. 
In essence vector_document_repo in that moment is an object of kind Provide instead of what I was waiting for, because provider() was not called. 

-- document_controller.py --
```
import os

from dependency_injector.wiring import Provide
from fastapi import HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

from src.rag.document.document_container import DocumentContainer
from src.rag.legal_agent import QwenLegalAgent
from log import logger
from src.rag.constants import PROJECT_ROOT
from src.rag.document.vector_document_repository import VectorDocumentRepository
from fastapi import APIRouter

answer_agent = QwenLegalAgent()
checker_agent = QwenLegalAgent()

templates = Jinja2Templates(directory=os.path.join(PROJECT_ROOT, "templates"))


class QueryRequest(BaseModel):
    query: str


router = APIRouter()
vector_document_repo: VectorDocumentRepository = Provide[DocumentContainer.vector_document_repo]


@router.post("/query")
async def query(request: QueryRequest):
    disclaimer = "DISCLAIMER: This is not professional legal advice. Consult a qualified attorney for your specific case."

    context = await vector_document_repo.query(request.query)
    if not context or len(context) == 0:
        return JSONResponse(content={"answer": "I don't have enough information to answer.", "disclaimer": disclaimer})
    CONFIDENCE_THRESHOLD = 0
    try:
        answer, avg_confidence = await answer_agent.generate_response(request.query, context)
        is_verified = (lambda confidence: confidence >= CONFIDENCE_THRESHOLD)(avg_confidence)

        if is_verified:
            return JSONResponse(content={
                "answer": answer,
                "confidence": avg_confidence,
                "disclaimer": disclaimer,
                # "sources": [{"text": doc[:100] + "...", "confidence": conf} for doc, conf in context[:3]]
            })
        else:
            # return JSONResponse(content={"answer": "Unable to provide a verified answer.", "disclaimer": disclaimer})
            return JSONResponse(
                content={"answer": f"Confidence level below threadshold {CONFIDENCE_THRESHOLD}", "confidence": "-1",
                         "disclaimer": disclaimer})
    except Exception as e:
        line_number = e.__traceback__.tb_lineno
        logger.error(f"Error processing query: : {line_number} : {e}")
        return JSONResponse(
            content={"answer": "An error occurred while processing your query.", "disclaimer": disclaimer})


@router.get("/", response_class=HTMLResponse)
async def serve_index(request: Request):
    try:
        return templates.TemplateResponse("index.html", {"request": request})
    except Exception as e:
        logger.error(f"Error serving index: {e}")
        raise HTTPException(status_code=404, detail="Index file not found")

```
This code works well if the container is placed inside the same package as the controller.
When a module cannot be found, the container throws an error stating clearly that the module which I provided could not be found.

**Comment by ZipFile** [comment]
Module-level injections are not supported, try:

```diff
--- issue844.py 2024-12-17 00:00:00.000000000 +0000
+++ issue844.py 2024-12-17 00:00:00.000000000 +0000
@@ -1,7 +1,7 @@
 import os
 
-from dependency_injector.wiring import Provide
-from fastapi import HTTPException, Request
+from dependency_injector.wiring import Provide, inject
+from fastapi import Depends, HTTPException, Request
 from fastapi.responses import HTMLResponse, JSONResponse
 from fastapi.templating import Jinja2Templates
 from pydantic import BaseModel
@@ -24,11 +24,14 @@
 
 
 router = APIRouter()
-vector_document_repo: VectorDocumentRepository = Provide[DocumentContainer.vector_document_repo]
 
 
 @router.post("/query")
-async def query(request: QueryRequest):
+@inject
+async def query(
+    request: QueryRequest,
+    vector_document_repo: VectorDocumentRepository = Depends(Provide[DocumentContainer.vector_document_repo]),
+):
     disclaimer = "DISCLAIMER: This is not professional legal advice. Consult a qualified attorney for your specific case."
 
     context = await vector_document_repo.query(request.query)
```

**Comment by Deviad** [comment]
Hello,
all good. 

Just as a side note, if the dependency is defined in a module outside of any method, as long as the container is in the same package it will work anyways even if it is not officially supported.
In the end I declared the dependency in a class field to be compliant with the official API.

Thanks.
